### ISSUE TITLE
AccountOptions IdentityURL null in Signin process

### ISSUE THREAD

**Issue by harsha973** [forcedotcom/SalesforceMobileSDK-Android#1004]
I am getting a crash while loggin in to the App at random cases. Crash is

     java.lang.NullPointerException
       at java.net.URI.parseURI(URI.java:353)
       at java.net.URI.<init>(URI.java:204)
       at com.salesforce.androidsdk.rest.ClientManager.peekRestClient(ClientManager.java:209)
       at com.salesforce.androidsdk.rest.ClientManager.peekRestClient(ClientManager.java:149)
       at com.salesforce.androidsdk.rest.ClientManager$AccMgrCallback.run(ClientManager.java:458)
       at android.accounts.AccountManager$11.run(AccountManager.java:1438)
       at android.os.Handler.handleCallback(Handler.java:733)
       at android.os.Handler.dispatchMessage(Handler.java:95)
       at android.os.Looper.loop(Looper.java:136)
       at android.app.ActivityThread.main(ActivityThread.java:5476)
       at java.lang.reflect.Method.invokeNative(Native Method)
       at java.lang.reflect.Method.invoke(Method.java:515)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1268)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1084)
       at dalvik.system.NativeStart.main(Native Method)

Reason I figured  when debugging SalesforceMobileSDK is at line **626 in OAuthWebviewHelper.java** class. **While saving account options identityURL is never saved in bundle**. Not sure why this is missed but it is causing my crash. 

Regards,
Sree

**Comment by bhariharan** [comment]
This is fixed [here](https://github.com/forcedotcom/SalesforceMobileSDK-Android/pull/1006).
