### ISSUE TITLE
SmartStore usage gives java.lang.UnsatisfiedLinkError

### ISSUE THREAD

**Issue by toddhalfpenny** [forcedotcom/SalesforceMobileSDK-Android#1017]
MobileSDK =  v4.0.0

When using forcedroid apps are created and built OK, but crash with the following error when trying to use the SmartStore

```
java.lang.UnsatisfiedLinkError: dalvik.system.PathClassLoader[DexPathList[[zip file "/data/app/com.oinio.linde.accura-2/base.apk"],nativeLibraryDirectories=[/data/app/com.oinio.linde.accura-2/lib/arm64, /vendor/lib64, /system/lib64]]] couldn't find "libstlport_shared.so"
at java.lang.Runtime.loadLibrary(Runtime.java:366)
at java.lang.System.loadLibrary(System.java:988)
at net.sqlcipher.database.SQLiteDatabase.loadLibs(SQLiteDatabase.java:173)
at net.sqlcipher.database.SQLiteDatabase.loadLibs(SQLiteDatabase.java:169)
at com.salesforce.androidsdk.smartstore.store.DBOpenHelper.(DBOpenHelper.java:132)
at com.salesforce.androidsdk.smartstore.store.DBOpenHelper.getOpenHelper(DBOpenHelper.java:124)
at com.salesforce.androidsdk.smartstore.app.SmartStoreSDKManager.getGlobalSmartStore(SmartStoreSDKManager.java:202)
at com.salesforce.androidsdk.smartstore.app.SmartStoreSDKManager.getGlobalSmartStore(SmartStoreSDKManager.java:184)
at com.salesforce.androidsdk.phonegap.plugin.SmartStorePlugin.getSmartStore(SmartStorePlugin.java:577)
at com.salesforce.androidsdk.phonegap.plugin.SmartStorePlugin.soupExists(SmartStorePlugin.java:306)
at com.salesforce.androidsdk.phonegap.plugin.SmartStorePlugin.access$1400(SmartStorePlugin.java:58)
at com.salesforce.androidsdk.phonegap.plugin.SmartStorePlugin$1.run(SmartStorePlugin.java:160)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
at java.lang.Thread.run(Thread.java:818)
```

See other issues for some more info;
* https://github.com/forcedotcom/SalesforceMobileSDK-CordovaPlugin/issues/138
* #970 

I am able to reproduce this using both Linux and Mac build systems and see it on a varity of emulators and real devices.

To re-create issue create a new project with forcedroid and run it up. Once logged in run the following from the JS console

```
var smartstore = cordova.require("com.salesforce.plugin.smartstore");
smartstore.soupExists('anySoup', function(res){consoles.log(res);}, function(e){console.error(e);});
```

Issue seems to be with the *jniLibs.srcDir* in the SmartStore's *build.gradle*. I have a fix ready and will create a PR shortly.

**Comment by bhariharan** [comment]
Fix is [here](https://github.com/forcedotcom/SalesforceMobileSDK-Android/pull/1036).
