### ISSUE TITLE
App crash when launching app due to View race condition -- IllegalStateException

### ISSUE THREAD

**Issue by daveespo** [forcedotcom/SalesforceMobileSDK-Android#1088]
I don't have a reliable repro case for this -- but I've had my app crash enough times to know it wasn't a freak occurence

I am upgrading my hybrid app (hosts a Visualforce page) from MobileSDK 3 to 4.1.1

I'm currently running off of the unstable branch in git

When my app launches, sometimes it immediately crashes with

````
 java.lang.IllegalStateException: Calling View methods on another thread than the UI thread.
     at com.android.webview.chromium.WebViewChromium.createThreadException(WebViewChromium.java:293)
     at com.android.webview.chromium.WebViewChromium.checkThread(WebViewChromium.java:308)
     at com.android.webview.chromium.WebViewChromium.init(WebViewChromium.java:226)
     at android.webkit.WebView.<init>(WebView.java:606)
     at android.webkit.WebView.<init>(WebView.java:542)
     at android.webkit.WebView.<init>(WebView.java:525)
     at android.webkit.WebView.<init>(WebView.java:512)
     at android.webkit.WebView.<init>(WebView.java:502)
     at com.salesforce.androidsdk.phonegap.ui.SalesforceDroidGapActivity.setVFCookies(SalesforceDroidGapActivity.java:401)
     at com.salesforce.androidsdk.phonegap.ui.SalesforceDroidGapActivity.loadVFPingPage(SalesforceDroidGapActivity.java:390)
     at com.salesforce.androidsdk.phonegap.ui.SalesforceDroidGapActivity.access$400(SalesforceDroidGapActivity.java:72)
     at com.salesforce.androidsdk.phonegap.ui.SalesforceDroidGapActivity$1$1.onSuccess(SalesforceDroidGapActivity.java:326)
     at com.salesforce.androidsdk.rest.RestClient$1.onResponse(RestClient.java:222)
     at okhttp3.RealCall$AsyncCall.execute(RealCall.java:133)
     at okhttp3.internal.NamedRunnable.run(NamedRunnable.java:32)
     at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
     at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
     at java.lang.Thread.run(Thread.java:818)
````

If I relaunch the app, it generally comes up just fine.

It appears to be most reproducible when logging into the app the first time or if the app is resumed after being paused for a long period -- presumable due to the redirection/login dance through frontdoor

**Comment by daveespo** [comment]
I switched back to the 4.1.1 tag and I'm unable to repro so this appears to be only reproducible on the unstable branch

**Comment by wmathurin** [comment]
A fix is making its way to unstable: https://github.com/forcedotcom/SalesforceMobileSDK-Android/pull/1090
