### ISSUE TITLE
React Native App Crash

### ISSUE THREAD

**Issue by rachelleTRP** [forcedotcom/SalesforceMobileSDK-Android#1096]
Getting this error when I run the react native template app on Android Studio. Not able to log in, just crashes upon start up.

`java.lang.RuntimeException: An error occurred while executing doInBackground()
                                                                                                   at android.os.AsyncTask$3.done(AsyncTask.java:309)
                                                                                                   at java.util.concurrent.FutureTask.finishCompletion(FutureTask.java:354)
                                                                                                   at java.util.concurrent.FutureTask.setException(FutureTask.java:223)
                                                                                                   at java.util.concurrent.FutureTask.run(FutureTask.java:242)
                                                                                                   at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:234)
                                                                                                   at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
                                                                                                   at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
                                                                                                   at java.lang.Thread.run(Thread.java:818)
                                                                                                Caused by: java.lang.UnsatisfiedLinkError: could find DSO to load: libreactnativejni.so
                                                                                                   at com.facebook.soloader.SoLoader.loadLibraryBySoName(SoLoader.java:213)
                                                                                                   at com.facebook.soloader.SoLoader.loadLibrary(SoLoader.java:178)
                                                                                                   at com.facebook.react.bridge.JSCJavaScriptExecutor.<clinit>(JSCJavaScriptExecutor.java:25)
                                                                                                   at com.facebook.react.bridge.JSCJavaScriptExecutor$Factory.create(JSCJavaScriptExecutor.java:20)
                                                                                                   at com.facebook.react.ReactInstanceManagerImpl$ReactContextInitAsyncTask.doInBackground(ReactInstanceManagerImpl.java:183)
                                                                                                   at com.facebook.react.ReactInstanceManagerImpl$ReactContextInitAsyncTask.doInBackground(ReactInstanceManagerImpl.java:169)
                                                                                                   at android.os.AsyncTask$2.call(AsyncTask.java:295)
                                                                                                   at java.util.concurrent.FutureTask.run(FutureTask.java:237)
                                                                                                   at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:234) 
                                                                                                   at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113) 
                                                                                                   at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588) 
                                                                                                   at java.lang.Thread.run(Thread.java:818) `

I've confirmed I'm running the server and I've pulled from the unstable branch.
Neither the stable nor unstable branch seems to work.

**Comment by wmathurin** [comment]
Did you generate your application with forcedroid ?
Please try that or have a look at the sample application here: https://github.com/forcedotcom/SmartSyncExplorerReactNative
