### ISSUE TITLE
SENDER_ID missing issue

### ISSUE THREAD

**Issue by asinha08** [forcedotcom/SalesforceMobileSDK-Android#1111]
When I create new application using forcedroid I get following issue,
Failed to install 'phonegap-plugin-push':Error: Variable(s) missing: SENDER_ID

Please NOTE, I am have to use push notification feature but how do i need to provide SENDER_ID to forcedroid.

I also tried workaround mentioned in below link... when application is launched. sales force login page is not shown (there is no javascript error).

http://salesforce.stackexchange.com/questions/113727/sender-id-error-while-creating-hybrid-app-using-forcedroid

``
Fetching plugin "https://github.com/forcedotcom/SalesforceMobileSDK-CordovaPlugin" via git clone
Repository "https://github.com/forcedotcom/SalesforceMobileSDK-CordovaPlugin" checked out to git ref "v4.0.2".
Installing "com.salesforce" for android
Dependent plugin "cordova-plugin-whitelist" already installed on android.
Fetching plugin "cordova-plugin-device" via npm
Installing "cordova-plugin-device" for android
Fetching plugin "phonegap-plugin-push" via npm
Installing "phonegap-plugin-push" for android
Failed to install 'phonegap-plugin-push':Error: Variable(s) missing: SENDER_ID
    at /usr/local/lib/node_modules/cordova/node_modules/cordova-lib/src/plugman/install.js:346:23
    at _fulfilled (/usr/local/lib/node_modules/cordova/node_modules/q/q.js:787:54)
    at self.promiseDispatch.done (/usr/local/lib/node_modules/cordova/node_modules/q/q.js:816:30)
    at Promise.promise.promiseDispatch (/usr/local/lib/node_modules/cordova/node_modules/q/q.js:749:13)
    at /usr/local/lib/node_modules/cordova/node_modules/q/q.js:557:44
    at flush (/usr/local/lib/node_modules/cordova/node_modules/q/q.js:108:17)
    at nextTickCallbackWith0Args (node.js:419:9)
    at process._tickCallback (node.js:348:13)
Failed to install 'com.salesforce':Error: Variable(s) missing: SENDER_ID
    at /usr/local/lib/node_modules/cordova/node_modules/cordova-lib/src/plugman/install.js:346:23
    at _fulfilled (/usr/local/lib/node_modules/cordova/node_modules/q/q.js:787:54)
    at self.promiseDispatch.done (/usr/local/lib/node_modules/cordova/node_modules/q/q.js:816:30)
    at Promise.promise.promiseDispatch (/usr/local/lib/node_modules/cordova/node_modules/q/q.js:749:13)
    at /usr/local/lib/node_modules/cordova/node_modules/q/q.js:557:44
    at flush (/usr/local/lib/node_modules/cordova/node_modules/q/q.js:108:17)
    at nextTickCallbackWith0Args (node.js:419:9)
    at process._tickCallback (node.js:348:13)
Error: Variable(s) missing: SENDER_ID
``

**Comment by asinha08** [comment]
I also tried workaround mentioned in below link... but when application is launched. sales force login page is not shown.

http://salesforce.stackexchange.com/questions/113727/sender-id-error-while-creating-hybrid-app-using-forcedroid

**Comment by bhariharan** [comment]
The latest version of the ```PushPlugin``` broke our plugin. We have a fix for this and it will be in our next release. Meanwhile, you should be able to uninstall and then add the latest plugin like the post mentions.

**Comment by asinha08** [comment]
As I mentioned in my query above, I tried the workaround and it is not working.

**Comment by asinha08** [comment]
Also Please let me know when next version will be available.
