### ISSUE TITLE
SmartSyncExplorer Demo : Object type 'Contact' is not supported

### ISSUE THREAD

**Issue by masterravi** [forcedotcom/SalesforceMobileSDK-Android#1113]
Whenever I login through Salesforce and make call to fetch contact list always getting error:

> 05-04 17:02:44.881 29244-30264/com.salesforce.samples.smartsyncexplorer E/SmartSyncMgr:runSync: Error during sync: 1
                                                                                                org.json.JSONException: Value [{"message":"\nEmail, Department, HomePhone from Contact limit 10000\n                                  ^\nERROR at Row:1:Column:105\nsObject type 'Contact' is not supported. If you are attempting to use a custom object, be sure to append the '__c' after the entity name. Please reference your WSDL or the describe call for the appropriate names.","errorCode":"INVALID_TYPE"}] of type org.json.JSONArray cannot be converted to JSONObject
                                                                                                    at org.json.JSON.typeMismatch(JSON.java:111)
                                                                                                    at org.json.JSONObject.<init>(JSONObject.java:160)
                                                                                                    at org.json.JSONObject.<init>(JSONObject.java:173)
                                                                                                    at com.salesforce.androidsdk.rest.RestResponse.asJSONObject(RestResponse.java:208)
                                                                                                    at com.salesforce.androidsdk.smartsync.util.SoqlSyncDownTarget.startFetch(SoqlSyncDownTarget.java:106)
                                                                                                    at com.salesforce.androidsdk.smartsync.manager.SyncManager.syncDown(SyncManager.java:470)
                                                                                                    at com.salesforce.androidsdk.smartsync.manager.SyncManager.access$000(SyncManager.java:68)
                                                                                                    at com.salesforce.androidsdk.smartsync.manager.SyncManager$1.run(SyncManager.java:253)
                                                                                                    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
                                                                                                    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
                                                                                                    at java.lang.Thread.run(Thread.java:818)

**Comment by wmathurin** [comment]
Please check the profile/permissions of the user you are logging in with.
Try it here https://workbench.developerforce.com/login.php and if you are able to run the SOQL from workbench for that user/org then it should work from the sample app as well.
