### ISSUE TITLE
Sqlcipher exception: libsqlcipher_android.so: has text relocations 

### ISSUE THREAD

**Issue by sarath-agile** [forcedotcom/SalesforceMobileSDK-Android#1208]
Please fill out the following details:

1. Version of Mobile SDK Used: 4.1.1
2. Issue found in Native App or Hybrid App: Native
3. OS Version: Android 6.0 API 23
4. Device: Emulator - Google API Intelx86 Atom System Image   
5. Steps to reproduce:    
`Try to create and use a project specific ContentProvider in the salesforce application eventhough we use  the SmartStore and SmartSync `
6. Actual behavior:
`Unable define a  ContentProvider  and use a custom SQLiteOpenHelper in it`
7. Expected Behavior:  
`It must allow us to use our own ContentProvider `
8. Error Log:  
```
Caused by: java.lang.UnsatisfiedLinkError: dlopen failed: /data/app/com.example-1/lib/x86/libsqlcipher_android.so: has text relocations
                                                     at java.lang.Runtime.loadLibrary(Runtime.java:372)
                                                     at java.lang.System.loadLibrary(System.java:1076)
                                                     at net.sqlcipher.database.SQLiteDatabase.loadLibs(SQLiteDatabase.java:174)
                                                     at net.sqlcipher.database.SQLiteDatabase.loadLibs(SQLiteDatabase.java:169)
                                                     at com.example.helper.ProjectDbOpenHelper.<init>(ProjectDbOpenHelper.java:29)
                                                     at java.lang.reflect.Constructor.newInstance(Native Method)

```
**Other Information:**  

- It was working fine for Android 5.0 API 21 in the emulator

**Comment by bhariharan** [comment]
@sarath-agile This is a `SQLCipher` issue, as outlined [here](https://github.com/sqlcipher/android-database-sqlcipher/issues/190). We have upgraded to the latest `SQLCipher` on our `unstable` branch, which has a fix for this. Give it a shot.
