### ISSUE TITLE
Socket Timeout at the time of sync down operation

### ISSUE THREAD

**Issue by ravikanasagra1** [forcedotcom/SalesforceMobileSDK-Android#1476]
I have raised this issue on Salesforce Stackexchange forum and on Google Plus forum 11+ days ago and got no solution. Kindly let me know if this is not right place as it has created lot of issue in my team's development as we have started getting multiple timeout issues. Please redirect us to correct support team. 

https://salesforce.stackexchange.com/questions/186472/socket-timeout-in-salesforce-android-sdk-random-behaviour 

More detail as given below.

Please fill out the following details:

1. Version of Mobile SDK Used: 5.2
2. Issue found in Native App or Hybrid App: Native Android
3. OS Version: 6.0 and 7.0
4. Device: Samsung Galaxy Tab S2

I have an Android application which uses Salesforce Android SDK to connect with Salesforce and fetch data. I fetch large salesforce (many) objects like Account having 100000+ records. I started some random behavior of getting socket time out error at the time of data fetch of such large objects with Sync Down operation.

Fetch operation works one after another object fetch. So, few objects successfully gets sync down in soup but for few I receive this time out error.

Is there a way to increase timeout time so that framework wait for to receive response?

In case of large data, salesforce returns 2000 records at a time and calls salesforce multiple times till all records are sync down. Is there a way to reduce this 2000 records to 1000 records?

Is there any other way to fix this error?

`E/SyncManager: Exception thrown in runSync
                                                                        java.net.SocketTimeoutException: timeout
                                                                            at okio.Okio$4.newTimeoutException(Okio.java:227)
                                                                            at okio.AsyncTimeout.exit(AsyncTimeout.java:274)
                                                                            at okio.AsyncTimeout$2.read(AsyncTimeout.java:242)
                                                                            at okio.RealBufferedSource.indexOf(RealBufferedSource.java:325)
                                                                            at okio.RealBufferedSource.indexOf(RealBufferedSource.java:314)
                                                                            at okio.RealBufferedSource.readUtf8LineStrict(RealBufferedSource.java:210)
                                                                            at okhttp3.internal.http1.Http1Codec.readResponseHeaders(Http1Codec.java:189)
                                                                            at okhttp3.internal.http.CallServerInterceptor.intercept(CallServerInterceptor.java:67)
                                                                            at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:92)
                                                                            at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:67)
                                                                            at com.salesforce.androidsdk.auth.HttpAccess$UserAgentInterceptor.intercept(HttpAccess.java:196)
                                                                            at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:92)
                                                                            at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:67)
                                                                            at com.salesforce.androidsdk.auth.HttpAccess$UserAgentInterceptor.intercept(HttpAccess.java:196)
                                                                            at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:92)
                                                                            at okhttp3.internal.connection.ConnectInterceptor.intercept(ConnectInterceptor.java:45)
                                                                            at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:92)
                                                                            at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:67)
                                                                            at okhttp3.internal.cache.CacheInterceptor.intercept(CacheInterceptor.java:93)
                                                                            at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:92)
                                                                            at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:67)
                                                                            at okhttp3.internal.http.BridgeInterceptor.intercept(BridgeInterceptor.java:93)
                                                                            at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:92)
                                                                            at okhttp3.internal.http.RetryAndFollowUpInterceptor.intercept(RetryAndFollowUpInterceptor.java:120)
                                                                            at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:92)
                                                                            at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:67)
                                                                            at com.salesforce.androidsdk.rest.RestClient$OAuthRefreshInterceptor.intercept(RestClient.java:598)
                                                                            at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:92)
                                                                            at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:67)
                                                                            at okhttp3.RealCall.getResponseWithInterceptorChain(RealCall.java:179)
                                                                            at okhttp3.RealCall.execute(RealCall.java:63)
                                                                            at com.salesforce.androidsdk.rest.RestClient.sendSync(RestClient.java:357)
                                                                            at com.salesforce.androidsdk.smartsync.manager.SyncManager.sendSyncWithSmartSyncUserAgent(SyncManager.java:557)
                                                                            at com.salesforce.androidsdk.smartsync.target.SoqlSyncDownTarget.startFetch(SoqlSyncDownTarget.java:119)
                                                                            at com.salesforce.androidsdk.smartsync.target.SoqlSyncDownTarget.startFetch(SoqlSyncDownTarget.java:114)
                                                                            at com.salesforce.androidsdk.smartsync.manager.SyncManager.syncDown(SyncManager.java:501)
                                                                            at com.salesforce.androidsdk.smartsync.manager.SyncManager.access$000(SyncManager.java:67)
                                                                            at com.salesforce.androidsdk.smartsync.manager.SyncManager$1.run(SyncManager.java:262)
                                                                            at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
                                                                            at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
                                                                            at java.lang.Thread.run(Thread.java:818)`

**Comment by wmathurin** [comment]
SOQL offers some controls for pagination (see [here](https://developer.salesforce.com/docs/atlas.en-us.soql_sosl.meta/soql_sosl/sforce_api_calls_soql_select_offset.htm)) but unfortunately it only applies to the first 2000 records.

We are using OkHttp for networking, you can get the OkHttpClient from the sync manager and change the connect and socket timeouts by doing the following:
```java
OkHttpClient client = syncManager.getRestClient().getOkHttpClient();
client.setConnectTimeout(120, TimeUnit.SECONDS); // connect timeout
client.setReadTimeout(120, TimeUnit.SECONDS);    // socket timeout
```

**Comment by ravikanasagra1** [comment]
client.**setConnectTimeout**(120, TimeUnit.SECONDS); // connect timeout
client.**setReadTimeout**(120, TimeUnit.SECONDS);    // socket timeout

Methods highlighted are not available in SDK 5.0 It sets by default value from OkHttpClient class.

**Comment by wmathurin** [comment]
Actually they are, see:
https://github.com/forcedotcom/SalesforceMobileSDK-Android/blob/v5.0.0/libs/SmartSync/src/com/salesforce/androidsdk/smartsync/manager/SyncManager.java#L698 and https://github.com/forcedotcom/SalesforceMobileSDK-Android/blob/v5.0.0/libs/SalesforceSDK/src/com/salesforce/androidsdk/rest/RestClient.java#L247

**Comment by sysmei** [comment]
Where should I place this code snippet for increasing http timeout?
