### ISSUE TITLE
Not able to login if play services not latest on android 5

### ISSUE THREAD

**Issue by harshitaahuja** [forcedotcom/SalesforceMobileSDK-Android#1498]
Please fill out the following details:

1. Version of Mobile SDK Used: latest
2. Issue found in Native App or Hybrid App:native android app
3. OS Version:5
4. Device:nexus 5
5. Steps to reproduce:login success
6. Actual behavior:not redirecting to app after login success
7. Expected Behavior:redirected to home screen after login
8. Error Log:

 Error during decryption
```
                                                                   javax.crypto.BadPaddingException: pad block corrupted
                                                                       at com.android.org.bouncycastle.jcajce.provider.symmetric.util.BaseBlockCipher$BufferedGenericBlockCipher.doFinal(BaseBlockCipher.java:1011)
                                                                       at com.android.org.bouncycastle.jcajce.provider.symmetric.util.BaseBlockCipher.engineDoFinal(BaseBlockCipher.java:849)
                                                                       at javax.crypto.Cipher.doFinal(Cipher.java:1537)
                                                                       at com.salesforce.androidsdk.analytics.security.Encryptor.decrypt(Encryptor.java:290)
                                                                       at com.salesforce.androidsdk.analytics.security.Encryptor.decrypt(Encryptor.java:153)
                                                                       at com.salesforce.androidsdk.analytics.security.Encryptor.decrypt(Encryptor.java:136)
                                                                       at com.salesforce.androidsdk.analytics.store.EventStoreManager.decrypt(EventStoreManager.java:316)
                                                                       at com.salesforce.androidsdk.analytics.store.EventStoreManager.fetchEvent(EventStoreManager.java:285)
                                                                       at com.salesforce.androidsdk.analytics.store.EventStoreManager.fetchAllEvents(EventStoreManager.java:149)
                                                                       at com.salesforce.androidsdk.analytics.SalesforceAnalyticsManager.publishAllEvents(SalesforceAnalyticsManager.java:289)
                                                                       at com.salesforce.androidsdk.analytics.AnalyticsPublisherService.handleActionPublish(AnalyticsPublisherService.java:82)
                                                                       at com.salesforce.androidsdk.analytics.AnalyticsPublisherService.onHandleIntent(AnalyticsPublisherService.java:70)
                                                                       at android.app.IntentService$ServiceHandler.handleMessage(IntentService.java:66)
                                                                       at android.os.Handler.dispatchMessage(Handler.java:102)
                                                                       at android.os.Looper.loop(Looper.java:148)
                                                                       at android.os.HandlerThread.run(HandlerThread.java:61)
```

**Comment by wmathurin** [comment]
Were you using Mobile SDK 5.2 or 5.3? 5.3 was just released yesterday and has a fix in the Encryptor.decrypt method.

**Comment by harshitaahuja** [comment]
I was using 5.2, will update to latest. Thanks.

**Comment by harshitaahuja** [comment]
After updating to version 5.3 after login blank white screen is there not redirected after salesforce activity
and if relaunching app getting error

E/AILTNPublisher: Exception thrown while constructing rest client
                                                                        com.salesforce.androidsdk.rest.ClientManager$AccountInfoNotFoundException: User is logging out
                                                                            at com.salesforce.androidsdk.rest.ClientManager.peekRestClient(ClientManager.java:161)
                                                                            at com.salesforce.androidsdk.rest.ClientManager.peekRestClient(ClientManager.java:140)
                                                                            at com.salesforce.androidsdk.analytics.AILTNPublisher.publishLogLines(AILTNPublisher.java:113)
                                                                            at com.salesforce.androidsdk.analytics.AILTNPublisher.publish(AILTNPublisher.java:98)
                                                                            at com.salesforce.androidsdk.analytics.SalesforceAnalyticsManager.publishEvents(SalesforceAnalyticsManager.java:331)
                                                                            at com.salesforce.androidsdk.analytics.SalesforceAnalyticsManager.publishAllEvents(SalesforceAnalyticsManager.java:290)
                                                                            at com.salesforce.androidsdk.analytics.AnalyticsPublisherService.handleActionPublish(AnalyticsPublisherService.java:82)
                                                                            at com.salesforce.androidsdk.analytics.AnalyticsPublisherService.onHandleIntent(AnalyticsPublisherService.java:70)
                                                                            at android.app.IntentService$ServiceHandler.handleMessage(IntentService.java:66)
                                                                            at android.os.Handler.dispatchMessage(Handler.java:102)
                                                                            at android.os.Looper.loop(Looper.java:148)
                                                                            at android.os.HandlerThread.run(HandlerThread.java:61)

**Comment by bhariharan** [comment]
@harshitaahuja Could you try a fresh install on both those devices? Based on your comment, it sounds like a device specific issue.

**Comment by bhariharan** [comment]
Please reopen if this still exists. We can't reproduce this issue at our end.
