### ISSUE TITLE
Random Crash in response consume

### ISSUE THREAD

**Issue by harshitaahuja** [forcedotcom/SalesforceMobileSDK-Android#1501]
Please fill out the following details:

1. Version of Mobile SDK Used: 5.3
2. Issue found in Native App or Hybrid App:Native
3. OS Version:4.4
4. Device:samsung SM-T561
5. Steps to reproduce: randomly on any api success
6. Actual behavior:
7. Expected Behavior:
8. Error Log:
```
java.lang.IllegalStateException: closed
                                                       at okio.InflaterSource.read(InflaterSource.java:58)
                                                       at okio.GzipSource.read(GzipSource.java:80)
                                                       at okio.Buffer.writeAll(Buffer.java:996)
                                                       at okio.RealBufferedSource.readByteArray(RealBufferedSource.java:106)
                                                       at okhttp3.ResponseBody.bytes(ResponseBody.java:135)
                                                       at com.salesforce.androidsdk.rest.RestResponse.consume(RestResponse.java:118)
                                                       at com.salesforce.androidsdk.rest.RestResponse.asBytes(RestResponse.java:153)
                                                       at com.salesforce.androidsdk.rest.RestResponse.asString(RestResponse.java:194)
                                                       at com.metacube.twg.app.controller.MyRestClient$1$1.onSuccess(MyRestClient.java:213)
                                                       at com.salesforce.androidsdk.rest.RestClient$1.onResponse(RestClient.java:355)
                                                       at okhttp3.RealCall$AsyncCall.execute(RealCall.java:135)
                                                       at okhttp3.internal.NamedRunnable.run(NamedRunnable.java:32)
                                                       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
                                                       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
                                                       at java.lang.Thread.run(Thread.java:841)
```

**Comment by wmathurin** [comment]
Could you give us more details on how you are using your RestClient?
Are they used across threads?
This could be related: https://github.com/square/okhttp/issues/1842

**Comment by wmathurin** [comment]
Based on my previous comment, we don't believe it is a Mobile SDK bug but rather has to do with the way the RestClient is being used across thread (see the linked okhttp issue for details).

**Comment by harshitaahuja** [comment]
Crash after these two exceptions
```
E/RestResponse: Content could not be written to a byte array
                                                                      java.net.SocketTimeoutException: timeout
                                                                          at okio.Okio$4.newTimeoutException(Okio.java:230)
                                                                          at okio.AsyncTimeout.exit(AsyncTimeout.java:275)
                                                                          at okio.AsyncTimeout$2.read(AsyncTimeout.java:243)
                                                                          at okio.RealBufferedSource.request(RealBufferedSource.java:67)
                                                                          at okio.RealBufferedSource.require(RealBufferedSource.java:60)
                                                                          at okio.RealBufferedSource.readHexadecimalUnsignedLong(RealBufferedSource.java:294)
                                                                          at okhttp3.internal.http1.Http1Codec$ChunkedSource.readChunkSize(Http1Codec.java:458)
                                                                          at okhttp3.internal.http1.Http1Codec$ChunkedSource.read(Http1Codec.java:438)
                                                                          at okio.RealBufferedSource.read(RealBufferedSource.java:46)
                                                                          at okio.RealBufferedSource.exhausted(RealBufferedSource.java:56)
                                                                          at okio.InflaterSource.refill(InflaterSource.java:101)
                                                                          at okio.InflaterSource.read(InflaterSource.java:62)
                                                                          at okio.GzipSource.read(GzipSource.java:80)
                                                                          at okio.Buffer.writeAll(Buffer.java:1005)
                                                                          at okio.RealBufferedSource.readByteArray(RealBufferedSource.java:107)
                                                                          at okhttp3.ResponseBody.bytes(ResponseBody.java:136)
                                                                          at com.salesforce.androidsdk.rest.RestResponse.consume(RestResponse.java:118)
                                                                          at com.salesforce.androidsdk.rest.RestResponse.consumeQuietly(RestResponse.java:141)
                                                                          at com.metacube.twg.app.controller.MyRestClient$1.onSuccess(MyRestClient.java:201)
                                                                          at com.salesforce.androidsdk.rest.RestClient$1.onResponse(RestClient.java:355)
                                                                          at okhttp3.RealCall$AsyncCall.execute(RealCall.java:153)
                                                                          at okhttp3.internal.NamedRunnable.run(NamedRunnable.java:32)
                                                                          at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1162)
                                                                          at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636)
                                                                          at java.lang.Thread.run(Thread.java:764)
```


```
java.lang.IllegalStateException: closed
                                                                            at okio.InflaterSource.read(InflaterSource.java:58)
                                                                            at okio.GzipSource.read(GzipSource.java:80)
                                                                            at okio.Buffer.writeAll(Buffer.java:1005)
                                                                            at okio.RealBufferedSource.readByteArray(RealBufferedSource.java:107)
                                                                            at okhttp3.ResponseBody.bytes(ResponseBody.java:136)
                                                                            at com.salesforce.androidsdk.rest.RestResponse.consume(RestResponse.java:118)
                                                                            at com.salesforce.androidsdk.rest.RestResponse.asBytes(RestResponse.java:153)
                                                                            at com.salesforce.androidsdk.rest.RestResponse.asString(RestResponse.java:194)
                                                                            at com.metacube.twg.app.controller.MyRestClient$1.onSuccess(MyRestClient.java:209)
                                                                            at com.salesforce.androidsdk.rest.RestClient$1.onResponse(RestClient.java:355)
                                                                            at okhttp3.RealCall$AsyncCall.execute(RealCall.java:153)
                                                                            at okhttp3.internal.NamedRunnable.run(NamedRunnable.java:32)
                                                                            at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1162)
                                                                            at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636)
                                                                            at java.lang.Thread.run(Thread.java:764)
```

**Comment by harshitaahuja** [comment]
Getting these crashes randomly again.

`RestResponse: Content could not be written to a byte array
                                                                      java.net.SocketTimeoutException: timeout
                                                                          at okio.Okio$4.newTimeoutException(Okio.java:230)
                                                                          at okio.AsyncTimeout.exit(AsyncTimeout.java:285)
                                                                          at okio.AsyncTimeout$2.read(AsyncTimeout.java:241)
                                                                          at okio.RealBufferedSource.request(RealBufferedSource.java:67)
                                                                          at okio.RealBufferedSource.require(RealBufferedSource.java:60)
                                                                          at okio.RealBufferedSource.readHexadecimalUnsignedLong(RealBufferedSource.java:294)
                                                                          at okhttp3.internal.http1.Http1Codec$ChunkedSource.readChunkSize(Http1Codec.java:458)
                                                                          at okhttp3.internal.http1.Http1Codec$ChunkedSource.read(Http1Codec.java:438)
                                                                          at okio.RealBufferedSource.read(RealBufferedSource.java:46)
                                                                          at okio.RealBufferedSource.exhausted(RealBufferedSource.java:56)
                                                                          at okio.InflaterSource.refill(InflaterSource.java:101)
                                                                          at okio.InflaterSource.read(InflaterSource.java:62)
                                                                          at okio.GzipSource.read(GzipSource.java:80)
                                                                          at okio.Buffer.writeAll(Buffer.java:1005)
                                                                          at okio.RealBufferedSource.readByteArray(RealBufferedSource.java:107)
                                                                          at okhttp3.ResponseBody.bytes(ResponseBody.java:136)
                                                                          at com.salesforce.androidsdk.rest.RestResponse.consume(RestResponse.java:118)
                                                                          at com.salesforce.androidsdk.rest.RestResponse.consumeQuietly(RestResponse.java:141)
                                                                          at com.metacube.twg.app.api.MyRestClient$1.onSuccess(MyRestClient.java:94)
                                                                          at com.salesforce.androidsdk.rest.RestClient$1.onResponse(RestClient.java:355)
                                                                          at okhttp3.RealCall$AsyncCall.execute(RealCall.java:153)
                                                                          at okhttp3.internal.NamedRunnable.run(NamedRunnable.java:32)
                                                                          at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1162)
                                                                          at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636)
                                                                          at java.lang.Thread.run(Thread.java:764)
                                                                       Caused by: java.net.SocketException: socket is closed
                                                                          at com.android.org.conscrypt.ConscryptFileDescriptorSocket$SSLInputStream.read(ConscryptFileDescriptorSocket.java:546)
                                                                          at okio.Okio$2.read(Okio.java:139)
                                                                          at okio.AsyncTimeout$2.read(AsyncTimeout.java:237)
                                                                          at okio.RealBufferedSource.request(RealBufferedSource.java:67) 
                                                                          at okio.RealBufferedSource.require(RealBufferedSource.java:60) 
                                                                          at okio.RealBufferedSource.readHexadecimalUnsignedLong(RealBufferedSource.java:294) 
                                                                          at okhttp3.internal.http1.Http1Codec$ChunkedSource.readChunkSize(Http1Codec.java:458) 
                                                                          at okhttp3.internal.http1.Http1Codec$ChunkedSource.read(Http1Codec.java:438) 
                                                                          at okio.RealBufferedSource.read(RealBufferedSource.java:46) 
                                                                          at okio.RealBufferedSource.exhausted(RealBufferedSource.java:56) 
                                                                          at okio.InflaterSource.refill(InflaterSource.java:101) 
                                                                          at okio.InflaterSource.read(InflaterSource.java:62) 
                                                                          at okio.GzipSource.read(GzipSource.java:80) 
                                                                          at okio.Buffer.writeAll(Buffer.java:1005) 
                                                                          at okio.RealBufferedSource.readByteArray(RealBufferedSource.java:107) 
                                                                          at okhttp3.ResponseBody.bytes(ResponseBody.java:136) 
                                                                          at com.salesforce.androidsdk.rest.RestResponse.consume(RestResponse.java:118) 
                                                                          at com.salesforce.androidsdk.rest.RestResponse.consumeQuietly(RestResponse.java:141) 
                                                                          at com.metacube.twg.app.api.MyRestClient$1.onSuccess(MyRestClient.java:94) 
                                                                          at com.salesforce.androidsdk.rest.RestClient$1.onResponse(RestClient.java:355) 
                                                                          at okhttp3.RealCall$AsyncCall.execute(RealCall.java:153) 
                                                                          at okhttp3.internal.NamedRunnable.run(NamedRunnable.java:32) 
                                                                          at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1162) 
                                                                          at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636) 
                                                                          at java.lang.Thread.run(Thread.java:764) `

Restclients single instance is used as provided by salesforcesdk ClientManager.getRestClient()

**Comment by bhariharan** [comment]
@harshitaahuja I'm not sure why you're getting a `SocketTimeoutException` but [this PR](https://github.com/forcedotcom/SalesforceMobileSDK-Android/pull/1592) should prevent the app from crashing on calling `consume()` in `RestClient`.
