### ISSUE TITLE
JS error when typing 'forcedroid' command in shell

### ISSUE THREAD

**Issue by pozil** [forcedotcom/SalesforceMobileSDK-Android#1564]
Issue is happening on Mobile SDK 5.3.0 on MacOS 10.12.6.

After successfully installing the SDK, typing the `forcedroid` command in the shell displays the command help but ends with a JS error:
```shell
$ forcedroid

forcedroid: command line utility for building Android mobile applications using Salesforce Mobile SDK

Usage:

forcedroid create
    --apptype=<Application Type> (native, native_kotlin, react_native, hybrid_local, hybrid_remote)
    --appname=<Application Name>
    --packagename=<App Package Identifier> (e.g. com.mycompany.myapp)
    --organization=<Organization Name> (Your company's/organization's name)
    --startpage=<App Start Page> (The start page of your remote app. Only required for hybrid_remote)
    [--outputdir=<Output directory> (Leave empty for current directory)]

 OR 

forcedroid createWithTemplate
    --templaterepouri=<Template repo URI> (e.g. https://github.com/forcedotcom/SmartSyncExplorerReactNative)]
    --appname=<Application Name>
    --packagename=<App Package Identifier> (e.g. com.mycompany.myapp)
    --organization=<Organization Name> (Your company's/organization's name)
    [--outputdir=<Output directory> (Leave empty for current directory)]

 OR 

forcedroid version

 OR 

forcedroid

We also offer:
/usr/local/lib/node_modules/forcedroid/shared/configHelper.js:98
    for (var cli of Object.values(SDK.forceclis)) {
                           ^

TypeError: Object.values is not a function
    at usage (/usr/local/lib/node_modules/forcedroid/shared/configHelper.js:98:28)
    at Object.readConfig (/usr/local/lib/node_modules/forcedroid/shared/configHelper.js:54:9)
    at Object.createApp (/usr/local/lib/node_modules/forcedroid/shared/createHelper.js:188:18)
    at Object.<anonymous> (/usr/local/lib/node_modules/forcedroid/forcedroid.js:36:14)
    at Module._compile (module.js:541:32)
    at Object.Module._extensions..js (module.js:550:10)
    at Module.load (module.js:458:32)
    at tryModuleLoad (module.js:417:12)
    at Function.Module._load (module.js:409:3)
    at Module.runMain (module.js:575:10)
```

This issue could be related to the default system version of NPM (3.10.4) on my OS.

**Comment by bhariharan** [comment]
The `npm` version should be fine (I have `3.10.5` and it works fine for me). What's your `node` version (`node -v`)? I have `v6.2.2` installed and have verified it works fine.

**Comment by pozil** [comment]
I wonder what's the issue then:

```shell
pozil-ltm1:~ pozil$ node -v
v6.2.2
pozil-ltm1:~ pozil$ npm -v
3.10.4
```

**Comment by wmathurin** [comment]
Object.values is a new feature in ES2017 and it requires node 7.0 (see https://stackoverflow.com/questions/40421825/how-to-use-object-values-on-server-side-in-node-js). 
We moved away from using such bleeding edge in our upcoming release.
But with 5.3, you need to upgrade node to 7.0 or above.
