### ISSUE TITLE
Crash on AccountInfoNotFoundException after updating to latest SDK

### ISSUE THREAD

**Issue by harshitaahuja** [forcedotcom/SalesforceMobileSDK-Android#1619]
Please fill out the following details:

1. Version of Mobile SDK Used: 6.0
2. Issue found in Native App or Hybrid App:Native
3. OS Version:7
4. Device:samsung j7
5. Steps to reproduce:
6. Actual behavior:
7. Expected Behavior:
8. Error Log: `Caused by com.salesforce.androidsdk.rest.ClientManager$AccountInfoNotFoundException: User is logging out
       at com.salesforce.androidsdk.rest.ClientManager.peekRestClient(ClientManager.java:159)
       at com.salesforce.androidsdk.rest.ClientManager.peekRestClient(ClientManager.java:138)
       at com.salesforce.androidsdk.rest.ClientManager.getRestClient(ClientManager.java:115)
       at com.salesforce.androidsdk.ui.SalesforceActivityDelegate.onResume(SalesforceActivityDelegate.java:87)
       at com.salesforce.androidsdk.ui.SalesforceActivity.onResume(SalesforceActivity.java:54)
       at android.app.Instrumentation.callActivityOnResume(Instrumentation.java:1277)
       at android.app.Activity.performResume(Activity.java:7123)
       at android.app.ActivityThread.performResumeActivity(ActivityThread.java:3821)
       at android.app.ActivityThread.handleResumeActivity(ActivityThread.java:3885)
       at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3051)
       at android.app.ActivityThread.-wrap14(ActivityThread.java)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1642)
       at android.os.Handler.dispatchMessage(Handler.java:102)
       at android.os.Looper.loop(Looper.java:154)
       at android.app.ActivityThread.main(ActivityThread.java:6776)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1518)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1408)`

**Comment by bhariharan** [comment]
@harshitaahuja It looks like you're attempting to fetch a `RestClient` instance while the user is logging out. This should not be done and will result in `AccountInfoNotFoundException` being thrown - that's expected. We need more information on when this happens in your app. What sequence of steps leads to this? Are you able to reproduce this on any of our sample apps or an app generated from `forcedroid`?

**Comment by harshitaahuja** [comment]
I cannot always reproduce this issue. It may be after session expired or when failed to refresh auth token for multiple calls.

**Comment by bhariharan** [comment]
I'm not sure I understand this statement:
> i cannot wait to redirect to login screen again. it automatically does that. so i am not able to make sure logging out is complete.
The logout is initiated by explicitly calling `SalesforceSDKManager.getInstance().logout(activity);`, but it looks like you have pending or new REST requests that are fired once the logout method has been called. I'm suggesting that once your app calls `logout(activity)`, no further REST requests should get kicked off.

**Comment by harshitaahuja** [comment]
> once your app calls logout(activity), no further REST requests should get kicked off.
I completely agree, But to make sure i should be able to show progress on screen until logout is complete and user is redirected to launch screen. But the problem i am facing to make sure that user cannot make any action after logout is tapped is that i am not making that redirection to Launch screen. It handled by `SalesforceSDKManager.getInstance().logout(activity);`, and its taking time to do that redirection, instead of instant.

**Comment by bhariharan** [comment]
@harshitaahuja The redirection to `LoginActivity` is the last step after logging out and this is intentional (to avoid an attempt to log in before log out and clean up is complete). As I mentioned above, since the logout action is user-driven, it can be driven by a screen other than `SalesforceActivity` to prevent `onResume()` being called. It can be driven from a menu item with a dialog that's not dismissed until `LoginActivity` comes up so that no other user action is possible (take a look at our sample apps). Also, any action on the app can be gated such that it would occur only if `isLoggingOut` is `false`. These are steps entirely within the app's control. Are you able to reproduce the logout crash above on any of our sample apps?
