### ISSUE TITLE
NetworkErrorException thrown when auth token expired and refresh token was null somehow

### ISSUE THREAD

**Issue by harshitaahuja** [forcedotcom/SalesforceMobileSDK-Android#1645]
Please fill out the following details:

1. Version of Mobile SDK Used: 6.0
2. Issue found in Native App or Hybrid App:Native
3. OS Version:8.0
4. Device:Pixel
5. Steps to reproduce:I left App logged in and unused for 2 days and then opened
6. Actual behavior: NetworkErrorException is thrown
7. Expected Behavior:Auth token should get refreshed
8. Error Log: `ClientManager: Exception thrown while getting auth token
                                                                               android.accounts.NetworkErrorException: java.lang.NullPointerException: Attempt to invoke virtual method 'int java.lang.String.length()' on a null object reference
                                                                                   at com.salesforce.androidsdk.rest.ClientManager$AccMgrAuthTokenProvider.refreshStaleToken(ClientManager.java:657)
                                                                                   at com.salesforce.androidsdk.rest.ClientManager$AccMgrAuthTokenProvider.getNewAuthToken(ClientManager.java:529)
                                                                                   at com.salesforce.androidsdk.rest.RestClient$OAuthRefreshInterceptor.refreshAccessToken(RestClient.java:735)
                                                                                   at com.salesforce.androidsdk.rest.RestClient$OAuthRefreshInterceptor.intercept(RestClient.java:636)
                                                                                   at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
                                                                                   at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:121)
                                                                                   at okhttp3.RealCall.getResponseWithInterceptorChain(RealCall.java:200)
                                                                                   at okhttp3.RealCall$AsyncCall.execute(RealCall.java:147)
                                                                                   at okhttp3.internal.NamedRunnable.run(NamedRunnable.java:32)
                                                                                   at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1162)
                                                                                   at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636)
                                                                                   at java.lang.Thread.run(Thread.java:764)
                                                                                Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'int java.lang.String.length()' on a null object reference
                                                                                   at okhttp3.HttpUrl.canonicalize(HttpUrl.java:1751)
                                                                                   at okhttp3.FormBody$Builder.add(FormBody.java:121)
                                                                                   at com.salesforce.androidsdk.auth.OAuth2.refreshAuthToken(OAuth2.java:338)
                                                                                   at com.salesforce.androidsdk.rest.ClientManager$AccMgrAuthTokenProvider.refreshStaleToken(ClientManager.java:619)
                                                                                   at com.salesforce.androidsdk.rest.ClientManager$AccMgrAuthTokenProvider.getNewAuthToken(ClientManager.java:529) 
                                                                                   at com.salesforce.androidsdk.rest.RestClient$OAuthRefreshInterceptor.refreshAccessToken(RestClient.java:735) 
                                                                                   at com.salesforce.androidsdk.rest.RestClient$OAuthRefreshInterceptor.intercept(RestClient.java:636) 
                                                                                   at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147) 
                                                                                   at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:121) 
                                                                                   at okhttp3.RealCall.getResponseWithInterceptorChain(RealCall.java:200) 
                                                                                   at okhttp3.RealCall$AsyncCall.execute(RealCall.java:147) 
                                                                                   at okhttp3.internal.NamedRunnable.run(NamedRunnable.java:32) 
                                                                                   at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1162) 
                                                                                   at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636) 
                                                                                   at java.lang.Thread.run(Thread.java:764) `

I debugged this in OAuth2.java method public static TokenEndpointResponse refreshAuthToken
on line formBodyBuilder.add(REFRESH_TOKEN, refreshToken); exception is thrown, caught by a general catch in ClientManager `catch (Exception e) {
                SalesforceSDKLogger.w(TAG, "Exception thrown while getting new auth token", e);
                throw new NetworkErrorException(e);
            }`
which is not expected as in this scenario Refresh token should not be null. and even if its is null... user should be logged out and it happens in refresh token expire.

**Comment by ArtemGorobets** [comment]
Hi. Still have this issue in 7.3.0 (version code 66) Android SDK.
An app can't refresh Auth token after some time of idle and throws RefreshTokenRevokedException in refreshAccessToken() method.
Refresh token policy set to "Refresh token is valid until revoked"

**Comment by as8703** [comment]
@harshitaahuja @ArtemGorobets Did you solved this problem? Please help.
