### ISSUE TITLE
 java.security.NoSuchAlgorithmException: The BC provider no longer provides an implementation for Mac.HmacSHA256.

### ISSUE THREAD

**Issue by harshitaahuja** [forcedotcom/SalesforceMobileSDK-Android#1697]
Please fill out the following details:

1. Version of Mobile SDK Used: 6.1
2. Issue found in Native App or Hybrid App: Native
3. OS Version: Android P
4. Device: Android Emulator
5. Steps to reproduce:
6. Actual behavior:
7. Expected Behavior:
8. Error Log: `E/Encryptor: No MAC transformation available
    java.security.NoSuchAlgorithmException: The BC provider no longer provides an implementation for Mac.HmacSHA256.  Please see ((TODO(flooey, b/67626877): Blog Post Link)) for more details.
        at sun.security.jca.Providers.checkBouncyCastleDeprecation(Providers.java:562)
        at sun.security.jca.Providers.checkBouncyCastleDeprecation(Providers.java:330)
        at javax.crypto.Mac.getInstance(Mac.java:313)
        at com.salesforce.androidsdk.analytics.security.Encryptor.init(Encryptor.java:87)
        at com.salesforce.androidsdk.app.SalesforceSDKManager.initInternal(SalesforceSDKManager.java:458)
        at com.salesforce.androidsdk.app.SalesforceSDKManager.init(SalesforceSDKManager.java:442)
        at com.salesforce.androidsdk.app.SalesforceSDKManager.initNative(SalesforceSDKManager.java:493)
        at com.***.***.app.MyApplication.onCreate(MyApplication.java:116)
        at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1154)
        at android.app.ActivityThread.handleBindApplication(ActivityThread.java:5874)
        at android.app.ActivityThread.access$1100(ActivityThread.java:193)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1623)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loop(Looper.java:164)
        at android.app.ActivityThread.main(ActivityThread.java:6656)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:438)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:823)`

**Comment by bhariharan** [comment]
@harshitaahuja I'm aware of this issue. We don't support `Android P` yet. This will be fixed in a future release that supports `Android P` closer to the GA release of `Android P`.

**Comment by krause-michael** [comment]
Any update on this issue?  Android P is quickly approaching release and we'd like to be ready when it hits.

**Comment by bhariharan** [comment]
@krause-michael If you don't bump up the `targetSDKVersion` to `28` or above, `Mobile SDK 6.2` should work fine on `Android P` based on preliminary testing. #safeharbor

**Comment by bhariharan** [comment]
@krause-michael We do plan on having a version of Mobile SDK that supports `Android P` keeping the current target API version right after `Android P` ships. We won't be bumping up the target API version until a few months later though. #safeharbor You're welcome to tweak our target API version and check if it works though - we're open source.

**Comment by krause-michael** [comment]
Until this SDK is moved to a non-deprecated crypto implementation, clients using this SDK will be forced to use compatibility mode on Android-P which is not ideal.  Android P shipped two days ago.  Do you have an ETA besides just a few months from now?

**Comment by bhariharan** [comment]
I'll try to have something up on `dev` soon for consumption.

**Comment by bhariharan** [comment]
This has been fixed on the `dev` branch and will be a part of our upcoming release, `7.0`.

**Comment by ravihp** [comment]
@bhariharan can we have new version with fix?

**Comment by brandonpage** [comment]
@ravihp 7.0 has been available for many months.
