### ISSUE TITLE
Login activity not starting - java.lang.RuntimeException: Unable to start activity

### ISSUE THREAD

**Issue by harshitaahuja** [forcedotcom/SalesforceMobileSDK-Android#1698]
Please fill out the following details:

1. Version of Mobile SDK Used: 6.1
2. Issue found in Native App or Hybrid App: Native
3. OS Version: P
4. Device: Android Emulator
5. Steps to reproduce:
6. Actual behavior:
7. Expected Behavior:
8. Error Log:
```
java.lang.RuntimeException: Unable to start activity ComponentInfo{com.salesforce.androidsdk.ui.LoginActivity}: java.lang.NullPointerException: Attempt to invoke virtual method 'java.io.Serializable android.os.Bundle.getSerializable(java.lang.String)' on a null object reference
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2892)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3027)
        at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:78)
        at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:101)
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:73)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1786)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loop(Looper.java:164)
        at android.app.ActivityThread.main(ActivityThread.java:6656)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:438)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:823)
     Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'java.io.Serializable android.os.Bundle.getSerializable(java.lang.String)' on a null object reference
        at com.salesforce.androidsdk.rest.ClientManager$LoginOptions.fromBundle(ClientManager.java:787)
        at com.salesforce.androidsdk.ui.LoginActivity.onCreate(LoginActivity.java:113)
        at android.app.Activity.performCreate(Activity.java:7117)
        at android.app.Activity.performCreate(Activity.java:7108)
        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1262)
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2867)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3027) 
        at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:78) 
        at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:101) 
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:73) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1786) 
        at android.os.Handler.dispatchMessage(Handler.java:106) 
        at android.os.Looper.loop(Looper.java:164) 
        at android.app.ActivityThread.main(ActivityThread.java:6656) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:438) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:823) 
```

**Comment by bhariharan** [comment]
We don't support `Android P` yet. We will support `Android P` in a future release. Please refrain from filing bugs specific to `Android P` until that time. Thanks!

**Comment by bhariharan** [comment]
@amrboxit4me It's being worked on. Stay tuned!

**Comment by bhariharan** [comment]
`Android P` support has been added on the `dev` branch and will be a part of our upcoming release, `7.0`.
