### ISSUE TITLE
Flashing screen instead of login screen

### ISSUE THREAD

**Issue by ahuvabl** [forcedotcom/SalesforceMobileSDK-Android#1724]
Please fill out the following details:

1. Version of Mobile SDK Used:  
 **5.3.0**
2. Issue found in Native App or Hybrid App:
 **Native App**
3. OS Version:
 **Android 6.0 / 7.0 /8.0**
4. Device:
 **Galaxy s7 / Galaxy s8 / Galaxy note 5...**
5. Steps to reproduce: 
- Install Bank Leumi app from play store 
- Install MyDiplomat app from play store 
6. Actual behavior:
**'flashing screen' when running mydiplomat app. The loginActivity goes into infinite loop.**
(both of the apps using the salesforce mobile sdk)
7. Expected Behavior:
Display the login screen of MyDiplomat app
8. Error Log:

```
W/ClientManager: Exception thrown while creating rest client
    android.accounts.AuthenticatorException: addAccount failed
        at android.accounts.AccountManager.convertErrorToException(AccountManager.java:2205)
        at android.accounts.AccountManager.-wrap0(AccountManager.java)
        at android.accounts.AccountManager$AmsTask$Response.onError(AccountManager.java:2041)
        at android.accounts.IAccountManagerResponse$Stub.onTransact(IAccountManagerResponse.java:69)
        at android.os.Binder.execTransact(Binder.java:573)

..............................

 W/AccountAuthenticator: addAccount(com.salesforce.androidsdk)
    java.lang.RuntimeException: Applications need to call SalesforceSDKManager.init() first.
        at bos.a(SalesforceSDKManager.java:174)
        at com.salesforce.androidsdk.auth.AuthenticatorService$a.a(AuthenticatorService.java:286)
        at com.salesforce.androidsdk.auth.AuthenticatorService$a.addAccount(AuthenticatorService.java:114)
        at android.accounts.AbstractAccountAuthenticator$Transport.addAccount(AbstractAccountAuthenticator.java:167)
        at android.accounts.IAccountAuthenticator$Stub.onTransact(IAccountAuthenticator.java:67)
        at android.os.Binder.execTransact(Binder.java:573)
```

**Comment by bhariharan** [comment]
@ahuvabl The error log says it all:
```
Applications need to call SalesforceSDKManager.init() first.
```
It looks like the application is attempting to add an account before the SDK has been initialized properly. Please contact the app developer. This forum is reserved for known issues with our code.

**Comment by ahuvabl** [comment]
I'm sorry, I was not clear enough ..
The app works well! only if trying to run it when another app that using salesforce mobile sdk is installed on same device, happens the situation I described .

The app calls first to SalesforceSDKManager.init()!

The log include also the next line:
06-26 18:29:23.886 20747-20747/net.balink.diplomat.qa I/ClientManager: **No account of type com.salesforce.androidsdk found**

**Comment by bhariharan** [comment]
@ahuvabl This line just means that user login hasn't occurred yet while attempting to fetch `RestClient` and this will trigger the login flow. It's a harmless log line:
```
06-26 18:29:23.886 20747-20747/net.balink.diplomat.qa I/ClientManager: No account of type com.salesforce.androidsdk found
```
We are able to run multiple sample apps on the same device with no issues. Feel free to try multiple sample apps from our `dev` branch. Is the `AuthenticatorService` on your app running in the same process as the main process? How did you generate your app?
