### ISSUE TITLE
Sqlcipher Error in prod ( React Native )

### ISSUE THREAD

**Issue by lpongetti** [forcedotcom/SalesforceMobileSDK-Android#1760]
Hi,
I'm using React Native and SyncDown give me error in prod environment.
```
07-31 17:24:24.132 7816-7865/com.alitalia E/art: No <init>(Ljava/lang/String;)V in java.lang.Class<net.sqlcipher.database.SQLiteDoneException>
    
    --------- beginning of crash
07-31 17:24:24.133 7816-7865/com.alitalia E/AndroidRuntime: FATAL EXCEPTION: mqt_native_modules
    Process: com.alitalia, PID: 7816
    java.lang.RuntimeException: Could not invoke SmartSyncReactBridge.syncDown
        at com.facebook.react.bridge.JavaMethodWrapper.invoke(JavaMethodWrapper.java:383)
        at com.facebook.react.bridge.JavaModuleWrapper.invoke(JavaModuleWrapper.java:160)
        at com.facebook.react.bridge.queue.NativeRunnable.run(Native Method)
        at android.os.Handler.handleCallback(Handler.java:751)
        at android.os.Handler.dispatchMessage(Handler.java:95)
        at com.facebook.react.bridge.queue.MessageQueueThreadHandler.dispatchMessage(MessageQueueThreadHandler.java:29)
        at android.os.Looper.loop(Looper.java:154)
        at com.facebook.react.bridge.queue.MessageQueueThreadImpl$3.run(MessageQueueThreadImpl.java:192)
        at java.lang.Thread.run(Thread.java:761)
     Caused by: java.lang.reflect.InvocationTargetException
        at java.lang.reflect.Method.invoke(Native Method)
        at com.facebook.react.bridge.JavaMethodWrapper.invoke(JavaMethodWrapper.java:372)
        at com.facebook.react.bridge.JavaModuleWrapper.invoke(JavaModuleWrapper.java:160) 
        at com.facebook.react.bridge.queue.NativeRunnable.run(Native Method) 
        at android.os.Handler.handleCallback(Handler.java:751) 
        at android.os.Handler.dispatchMessage(Handler.java:95) 
        at com.facebook.react.bridge.queue.MessageQueueThreadHandler.dispatchMessage(MessageQueueThreadHandler.java:29) 
        at android.os.Looper.loop(Looper.java:154) 
        at com.facebook.react.bridge.queue.MessageQueueThreadImpl$3.run(MessageQueueThreadImpl.java:192) 
        at java.lang.Thread.run(Thread.java:761) 
     Caused by: java.lang.NoSuchMethodError: no non-static method "Lnet/sqlcipher/database/SQLiteDoneException;.<init>(Ljava/lang/String;)V"
        at net.sqlcipher.database.SQLiteStatement.native_1x1_long(Native Method)
        at net.sqlcipher.database.SQLiteStatement.simpleQueryForLong(SQLiteStatement.java:125)
        at com.salesforce.androidsdk.smartstore.store.DBHelper.getNextId(DBHelper.java:233)
        at com.salesforce.androidsdk.smartstore.store.SmartStore.create(SmartStore.java:940)
        at com.salesforce.androidsdk.smartstore.store.SmartStore.upsert(SmartStore.java:1234)
        at com.salesforce.androidsdk.smartstore.store.SmartStore.upsert(SmartStore.java:1184)
        at com.salesforce.androidsdk.smartstore.store.SmartStore.upsert(SmartStore.java:1198)
        at com.salesforce.androidsdk.smartsync.util.SyncState.createSyncDown(SyncState.java:136)
        at com.salesforce.androidsdk.smartsync.manager.SyncManager.createSyncDown(SyncManager.java:302)
        at com.salesforce.androidsdk.smartsync.manager.SyncManager.syncDown(SyncManager.java:286)
        at com.salesforce.androidsdk.reactnative.bridge.SmartSyncReactBridge.syncDown(SmartSyncReactBridge.java:107)
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.facebook.react.bridge.JavaMethodWrapper.invoke(JavaMethodWrapper.java:372) 
        at com.facebook.react.bridge.JavaModuleWrapper.invoke(JavaModuleWrapper.java:160) 
        at com.facebook.react.bridge.queue.NativeRunnable.run(Native Method) 
        at android.os.Handler.handleCallback(Handler.java:751) 
        at android.os.Handler.dispatchMessage(Handler.java:95) 
        at com.facebook.react.bridge.queue.MessageQueueThreadHandler.dispatchMessage(MessageQueueThreadHandler.java:29) 
        at android.os.Looper.loop(Looper.java:154) 
        at com.facebook.react.bridge.queue.MessageQueueThreadImpl$3.run(MessageQueueThreadImpl.java:192) 
        at java.lang.Thread.run(Thread.java:761) 
    ```

**Comment by bhariharan** [comment]
@lpongetti I don't see anything related to Mobile SDK in the stack trace and I can't reproduce this with our sample app. Could you generate a new app using `forcereact@6.2.0` and verify that `syncDown` works?

**Comment by lpongetti** [comment]
Sorry, my fault, proguard was active.
