### ISSUE TITLE
Crash : No Activity found com.android.chrome if isBrowserLoginEnabled= true and chrome is disable

### ISSUE THREAD

**Issue by david-spaeth** [forcedotcom/SalesforceMobileSDK-Android#1815]
1. Version of Mobile SDK Used: 6.1.0
2. Issue found in Native App or Hybrid App: native App
3. OS Version: 5,6 And 7
4. Device: any
5. Steps to reproduce: disabling Chrom.  Set SalesforceSDKManager.getInstance().isBrowserLoginEnabled to true 
6. Actual behavior: App crash
7. Expected Behavior: No crash
8. Error Log:
Fatal Exception: android.content.ActivityNotFoundException: No Activity found to handle Intent { act=android.intent.action.VIEW dat=https://*****/... flg=0x40000000 pkg=com.android.chrome launchParam=MultiScreenLaunchParams { mDisplayId=0 mBaseDisplayId=0 mFlags=0 } (has extras) }
       at android.app.Instrumentation.checkStartActivityResult(Instrumentation.java:1844)
       at android.app.Instrumentation.execStartActivity(Instrumentation.java:1531)
       at android.app.Activity.startActivityForResult(Activity.java:4403)
       at android.app.Activity.startActivity(Activity.java:4682)
       at android.support.v4.content.ContextCompat.startActivity(Unknown Source)
       at android.support.customtabs.CustomTabsIntent.launchUrl(Unknown Source)
       at com.salesforce.androidsdk.ui.OAuthWebviewHelper.loadLoginPageInChrome(Unknown Source)
       at com.salesforce.androidsdk.ui.OAuthWebviewHelper.doLoadPage(Unknown Source)
       at com.salesforce.androidsdk.ui.OAuthWebviewHelper.loadLoginPage(Unknown Source)
       at com.salesforce.androidsdk.ui.LoginActivity.onNewIntent(Unknown Source)
       at android.app.Instrumentation.callActivityOnNewIntent(Instrumentation.java:1231)
       at android.app.Instrumentation.callActivityOnNewIntent(Instrumentation.java:1243)
       at android.app.ActivityThread.deliverNewIntents(ActivityThread.java:3121)
       at android.app.ActivityThread.performNewIntents(ActivityThread.java:3133)
       at android.app.ActivityThread.handleNewIntent(ActivityThread.java:3142)
       at android.app.ActivityThread.-wrap17(ActivityThread.java)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1721)
       at android.os.Handler.dispatchMessage(Handler.java:102)
       at android.os.Looper.loop(Looper.java:154)
       at android.app.ActivityThread.main(ActivityThread.java:6776)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1496)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1386)

**Comment by bhariharan** [comment]
This should be fixed in our upcoming release, `7.0`. We now use `Chrome Custom Tabs`, so it should work.
