### ISSUE TITLE
SDK login crash

### ISSUE THREAD

**Issue by ahuvabl** [forcedotcom/SalesforceMobileSDK-Android#1853]
Please fill out the following details:

1. Version of Mobile SDK Used: 6.2.0
2. Issue found in Native App or Hybrid App: Native
3. OS Version: All versions
4. Device: All android devices
5. Steps to reproduce: Not clear, 
6. Actual behavior: 
We have an app in production, half of our users are experiencing unexpected crashes. the crash happens in "onResume" in the activity which inherits from the Salesforce activity when the application is first created. it seems that the SDK can't find a token, checks that an account existed, finds that he did and then sees that "IsLogginOut()" is true then throws an exception which causes the app to crash.
7. Expected Behavior:  App shouldn't crash 
8. Error Log:
Caused by com.salesforce.androidsdk.rest.ClientManager$AccountInfoNotFoundException: User is logging out
       at com.salesforce.androidsdk.rest.ClientManager.peekRestClient(ClientManager.java:160)
       at com.salesforce.androidsdk.rest.ClientManager.peekRestClient(ClientManager.java:139)
       at com.salesforce.androidsdk.rest.ClientManager.getRestClient(ClientManager.java:116)
       at com.salesforce.androidsdk.ui.SalesforceActivityDelegate.onResume(SalesforceActivityDelegate.java:87)
       at com.salesforce.androidsdk.ui.SalesforceActivity.onResume(SalesforceActivity.java:54)
       at android.app.Instrumentation.callActivityOnResume(Instrumentation.java:1277)
       at android.app.Activity.performResume(Activity.java:7088)
       at android.app.ActivityThread.performResumeActivity(ActivityThread.java:3768)
       at android.app.ActivityThread.handleResumeActivity(ActivityThread.java:3832)
       at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2994)
       at android.app.ActivityThread.-wrap14(ActivityThread.java)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1631)
       at android.os.Handler.dispatchMessage(Handler.java:102)
       at android.os.Looper.loop(Looper.java:154)
       at android.app.ActivityThread.main(ActivityThread.java:6682)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1520)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1410)

**Comment by bhariharan** [comment]
@ahuvabl There's not enough information given. Please try the latest version of the Mobile SDK.
