### ISSUE TITLE
SalesforceSDKManager.logout() is Causing App to Crash

### ISSUE THREAD

**Issue by homerlex** [forcedotcom/SalesforceMobileSDK-Android#1919]
Please fill out the following details:

1. Version of Mobile SDK Used: 
7.0.0
2. Issue found in Native App or Hybrid App:
Hybrid
3. OS Version:
Windows 10
4. Device:
Nexus 9
5. Steps to reproduce:
see below
6. Actual behavior:
see below
7. Expected Behavior:
see below
8. Error Log:
see below

We have a hybrid app with an activity class that extends SalesforceDroidGapActivity.  We have a menu item on the action bar that allows the user to logout.  When SalesforceSDKManager.getInstance().logout is called the user is successfully logged out but then the app crashes with the following error:

```
E/AndroidRuntime: FATAL EXCEPTION: main
                  Process: com.logout.tester, PID: 26632
                  android.content.ActivityNotFoundException: Unable to find explicit activity class {com.logout.tester/com.salesforce.androidsdk.phonegap.ui.SalesforceDroidGapActivity}; have you declared this activity in your AndroidManifest.xml?
                      at android.app.Instrumentation.checkStartActivityResult(Instrumentation.java:1805)
                      at android.app.Instrumentation.execStartActivity(Instrumentation.java:1523)
                      at android.app.ContextImpl.startActivity(ContextImpl.java:791)
                      at android.app.ContextImpl.startActivity(ContextImpl.java:768)
                      at android.content.ContextWrapper.startActivity(ContextWrapper.java:356)
                      at com.salesforce.androidsdk.app.SalesforceSDKManager.startLoginPage(SalesforceSDKManager.java:779)
                      at com.salesforce.androidsdk.app.SalesforceSDKManager.startSwitcherActivityIfRequired(SalesforceSDKManager.java:800)
                      at com.salesforce.androidsdk.app.SalesforceSDKManager.notifyLogoutComplete(SalesforceSDKManager.java:1002)
                      at com.salesforce.androidsdk.app.SalesforceSDKManager.access$300(SalesforceSDKManager.java:107)
                      at com.salesforce.androidsdk.app.SalesforceSDKManager$4.run(SalesforceSDKManager.java:986)
                      at android.accounts.AccountManager$Future2Task$1.run(AccountManager.java:2140)
                      at android.os.Handler.handleCallback(Handler.java:751)
                      at android.os.Handler.dispatchMessage(Handler.java:95)
                      at android.os.Looper.loop(Looper.java:154)
                      at android.app.ActivityThread.main(ActivityThread.java:6119)
                      at java.lang.reflect.Method.invoke(Native Method)
                      at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:886)
                      at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:776)
```

Here is what our activity class looks like:
```
package com.logout.tester;

import android.view.Menu;
import android.view.MenuInflater;
import android.view.MenuItem;

import com.salesforce.androidsdk.app.SalesforceSDKManager;
import com.salesforce.androidsdk.phonegap.ui.SalesforceDroidGapActivity;
import com.salesforce.androidsdk.phonegap.ui.SalesforceWebViewClientHelper;

public class LogoutActivity extends SalesforceDroidGapActivity {

    @Override
    public boolean onCreateOptionsMenu(Menu menu){
        MenuInflater inflater = getMenuInflater();
        inflater.inflate(R.menu.boe, menu);
        return super.onCreateOptionsMenu(menu);
    }

    @Override
    public boolean onOptionsItemSelected(MenuItem item){
        switch(item.getItemId()){
            case R.id.action_logout:
                SalesforceSDKManager.getInstance().logout(this,true);
                return true;
            case R.id.action_refresh:
                this.refresh(SalesforceWebViewClientHelper.getAppHomeUrl(this));
                return true;
            default:
                return super.onOptionsItemSelected(item);
        }
    }
}
```

I have attached the entire app folder so that you can run this and duplicate.

[app.zip](https://github.com/forcedotcom/SalesforceMobileSDK-Android/files/3213717/app.zip)

**Comment by wmathurin** [comment]
We will look into it.

**Comment by bhariharan** [comment]
@homerlex How are you calling `SalesforceHybridSDKManager.init(...)`? Are you passing in the subclass of `SalesforceDroidGapActivity` there?

**Comment by homerlex** [comment]
I'm not calling `SalesforceHybridSDKManager.init` from anywhere (as you can see from the source I attached to the original post).  Where is this supposed to be done?  I'm having trouble finding samples where you subclass `SalesforceDroidGapActivity`

**Comment by bhariharan** [comment]
@homerlex Open up `HybridApp.java` in your generated app. You'll find the following line there:
```
SalesforceHybridSDKManager.initHybrid(getApplicationContext());
```
You need to replace that with this line:
```
SalesforceHybridSDKManager.init(context, <youractivity>.class, LoginActivity.class);
```
This should fix the issue.

**Comment by homerlex** [comment]
The only HybridApp.java that I am seeing is in platforms/android/SalesforceHybrid/src/com/salesforce/androidsdk/phonegap/app.  So I created an "App" class in my app folder to do the initialization and it worked with the init call that you suggested.  Thanks for that.

Are there samples (or docs) anywhere that show how to properly subclass `SalesforceDroidGapActivity` ?

**Comment by bhariharan** [comment]
Not a whole lot of specific documentation on that subject, unfortunately. We will take a look at improving that section of the doc.
