### ISSUE TITLE
Android - Hybrid Application crash after specific hours.

### ISSUE THREAD

**Issue by MathurAM** [forcedotcom/SalesforceMobileSDK-Android#1949]
Please fill out the following details:

**Version of Mobile SDK Used:**
Salesforce Mobile SDK 6.0.0

**Issue found in Native App or Hybrid App:**
Hybrid App

**OS Version:**
Android 8.0, 9.0

**Device:**
Samsung S8, S9, S10

**Steps to reproduce:**
-> Login to the application
-> Let the application stay on the background mode for ~24hrs.

**Actual behavior:**
The app is crashing upon starting after ~24hrs

**Expected Behavior:**
The App should show the start page for your Org.

**Error Log:**
2019-07-09 11:24:34.652 8932-8932/com.demo I/SfDroidGapActivity: refresh called
2019-07-09 11:24:35.540 8932-9051/com.demo I/ClientManager: Need new access token
2019-07-09 11:24:35.544 8932-9050/com.demo I/ClientManager: Need new access token
2019-07-09 11:24:35.549 8932-9050/com.demo I/ClientManager: User is logging out
    com.salesforce.androidsdk.rest.ClientManager$AccountInfoNotFoundException: User is logging out
        at com.salesforce.androidsdk.rest.ClientManager.peekRestClient(ClientManager.java:159)
        at com.salesforce.androidsdk.rest.ClientManager$AccMgrAuthTokenProvider.getNewAuthToken(ClientManager.java:524)
        at com.salesforce.androidsdk.rest.RestClient$OAuthRefreshInterceptor.refreshAccessToken(RestClient.java:735)
        at com.salesforce.androidsdk.rest.RestClient$OAuthRefreshInterceptor.intercept(RestClient.java:636)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:121)
        at okhttp3.RealCall.getResponseWithInterceptorChain(RealCall.java:200)
        at okhttp3.RealCall$AsyncCall.execute(RealCall.java:147)
        at okhttp3.internal.NamedRunnable.run(NamedRunnable.java:32)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
        at java.lang.Thread.run(Thread.java:764)
2019-07-09 11:24:35.551 8932-9050/com.demo E/AndroidRuntime: FATAL EXCEPTION: OkHttp Dispatcher
    Process: com.demo, PID: 8932
    com.salesforce.androidsdk.rest.ClientManager$AccountInfoNotFoundException: User is logging out
        at com.salesforce.androidsdk.rest.ClientManager.peekRestClient(ClientManager.java:159)
        at com.salesforce.androidsdk.rest.ClientManager$AccMgrAuthTokenProvider.getNewAuthToken(ClientManager.java:524)
        at com.salesforce.androidsdk.rest.RestClient$OAuthRefreshInterceptor.refreshAccessToken(RestClient.java:735)
        at com.salesforce.androidsdk.rest.RestClient$OAuthRefreshInterceptor.intercept(RestClient.java:636)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:121)
        at okhttp3.RealCall.getResponseWithInterceptorChain(RealCall.java:200)
        at okhttp3.RealCall$AsyncCall.execute(RealCall.java:147)
        at okhttp3.internal.NamedRunnable.run(NamedRunnable.java:32)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
        at java.lang.Thread.run(Thread.java:764)
2019-07-09 11:24:35.586 8932-8932/com.demo D/CordovaActivity: Paused the activity.
2019-07-09 11:24:35.613 8932-9050/com.demo I/Process: Sending signal. PID: 8932 SIG: 9

**Comment by wmathurin** [comment]
6.0 was released at the end of 2017, could you try with a more (or the most) recent version of the Mobile SDK: 7.1.2 ?

**Comment by MathurAM** [comment]
@wmathurin If I look into the logs I can see that the crash is due to an exception raised by `peekRestClient` function of class [ClientManager](https://github.com/forcedotcom/SalesforceMobileSDK-Android/blob/dev/libs/SalesforceSDK/src/com/salesforce/androidsdk/rest/ClientManager.java#L220), now this exception is not handled by [SalesforceDroidGapActivity](https://github.com/forcedotcom/SalesforceMobileSDK-Android/blob/master/libs/SalesforceHybrid/src/com/salesforce/androidsdk/phonegap/ui/SalesforceDroidGapActivity.java) class.

**peekRestClient-Method** throwing exection:

![peekRestClient-Method](https://user-images.githubusercontent.com/8548015/61693110-99be0e00-ad4c-11e9-9f1b-abce7990b6fb.png)

**SalesforceDroidGapActivity-Class** not handling exection:

![SalesforceDroidGapActivity-Class](https://user-images.githubusercontent.com/8548015/61693097-91fe6980-ad4c-11e9-81e8-2cfb077f4f69.png)

**Comment by wmathurin** [comment]
What is the refresh token policy for your connected app?
Is it valid until revoked or something else.
For more info: see https://developer.salesforce.com/docs/atlas.en-us.packagingGuide.meta/packagingGuide/connected_app_manage_edit.htm

**Comment by brandonpage** [comment]
No response on this in months, please reopen if the issue exits on Mobile SDK 7.3.0.
