### ISSUE TITLE
OkHttp interceptor leak when getting new token

### ISSUE THREAD

**Issue by smithaaron** [forcedotcom/SalesforceMobileSDK-Android#1955]
Please fill out the following details:

1. Version of Mobile SDK Used: 7.2
2. Issue found in Native App or Hybrid App: Native
3. OS Version: Android 9
4. Device: All
5. Steps to reproduce: call getRestClient after accessToken expiry but before refreshToken expiry
6. Actual behavior: Crash
7. Expected Behavior: Not crash
8. Error Log:
2019-07-26 17:03:54.746 11474-11683/com.abc.qa I/ClientManager: Need new access token`
2019-07-26 17:03:55.159 11474-11683/com.abc.qa E/AndroidRuntime: FATAL EXCEPTION: AsyncTask #1
    Process: com.abc.qa, PID: 11474
    java.lang.RuntimeException: An error occurred while executing doInBackground()
        at android.os.AsyncTask$3.done(AsyncTask.java:354)
        at java.util.concurrent.FutureTask.finishCompletion(FutureTask.java:383)
        at java.util.concurrent.FutureTask.setException(FutureTask.java:252)
        at java.util.concurrent.FutureTask.run(FutureTask.java:271)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
        at java.lang.Thread.run(Thread.java:764)
     Caused by: java.lang.IllegalStateException: cannot make a new request because the previous response is still open: please call response.close()
        at okhttp3.internal.connection.Transmitter.newExchange$okhttp(Transmitter.kt:156)
        at okhttp3.internal.connection.ConnectInterceptor.intercept(ConnectInterceptor.kt:35)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:112)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:87)
        at okhttp3.internal.cache.CacheInterceptor.intercept(CacheInterceptor.kt:82)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:112)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:87)
        at okhttp3.internal.http.BridgeInterceptor.intercept(BridgeInterceptor.kt:84)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:112)
        at okhttp3.internal.http.RetryAndFollowUpInterceptor.intercept(RetryAndFollowUpInterceptor.kt:71)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:112)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:87)
        at com.salesforce.androidsdk.rest.RestClient$OAuthRefreshInterceptor.intercept(RestClient.java:676)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:112)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:87)
        at okhttp3.RealCall.getResponseWithInterceptorChain(RealCall.kt:184)
        at okhttp3.RealCall.execute(RealCall.kt:66)
        at com.salesforce.androidsdk.rest.RestClient.sendSync(RestClient.java:369)
        at com.salesforce.androidsdk.analytics.AILTNPublisher.publishLogLines(AILTNPublisher.java:135)
        at com.salesforce.androidsdk.analytics.AILTNPublisher.publish(AILTNPublisher.java:98)
        at com.salesforce.androidsdk.analytics.SalesforceAnalyticsManager.publishEvents(SalesforceAnalyticsManager.java:315)
        at com.salesforce.androidsdk.analytics.SalesforceAnalyticsManager.publishAllEvents(SalesforceAnalyticsManager.java:274)
        at com.salesforce.androidsdk.analytics.AnalyticsPublisherService.handleActionPublish(AnalyticsPublisherService.java:75)
        at com.salesforce.androidsdk.analytics.AnalyticsPublisherService.onHandleWork(AnalyticsPublisherService.java:63)
        at androidx.core.app.JobIntentService$CommandProcessor.doInBackground(JobIntentService.java:392)
        at androidx.core.app.JobIntentService$CommandProcessor.doInBackground(JobIntentService.java:383)
        at android.os.AsyncTask$2.call(AsyncTask.java:333)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167) 
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641) 
        at java.lang.Thread.run(Thread.java:764) `

Further info: According to [this issue](https://github.com/square/okhttp/issues/4986) this problem is caused by a leak in an interceptor. From OkHttp 3.14 onwards the leak is detected and reported. We're using Okhttp 4.0.1 in our app.

**Comment by bhariharan** [comment]
We'll take a look. Thanks for reporting.

**Comment by bhariharan** [comment]
Fixed [here](https://github.com/forcedotcom/SalesforceMobileSDK-Android/pull/1993). This will be in `Mobile SDK 8.0`.
