### ISSUE TITLE
Application using the mobile SDK crashes during the login process

### ISSUE THREAD

**Issue by five-zero-four-zero** [forcedotcom/SalesforceMobileSDK-Android#1963]
1. Version of Mobile SDK Used: 7.2.0
2. Issue found in Native App or Hybrid App: The application using the mobile SDK crashes during the login process.
3. OS Version: 8.1.0
4. Device: Samsung Galaxy Tab A (2017)
5. Steps to reproduce: After entering a username and password, then the verification code and pressing "Allow", the Android application will crash with the stacktrace below:

```
Encryptor: Error during asymmetric decryption
Encryptor: javax.crypto.IllegalBlockSizeException
Encryptor: 	at android.security.keystore.AndroidKeyStoreCipherSpiBase.engineDoFinal(AndroidKeyStoreCipherSpiBase.java:519)
Encryptor: 	at javax.crypto.Cipher.doFinal(Cipher.java:1741)
Encryptor: 	at com.salesforce.androidsdk.analytics.security.Encryptor.decryptWithPrivateKey(Encryptor.java:365)
Encryptor: 	at com.salesforce.androidsdk.analytics.security.Encryptor.decryptWithRSABytes(Encryptor.java:318)
Encryptor: 	at com.salesforce.androidsdk.analytics.security.Encryptor.decryptWithRSA(Encryptor.java:299)
Encryptor: 	at com.salesforce.androidsdk.security.SalesforceKeyGenerator.generateUniqueId(SalesforceKeyGenerator.java:222)
Encryptor: 	at com.salesforce.androidsdk.security.SalesforceKeyGenerator.getUniqueId(SalesforceKeyGenerator.java:90)
Encryptor: 	at com.salesforce.androidsdk.security.SalesforceKeyGenerator.getUniqueId(SalesforceKeyGenerator.java:79)
Encryptor: 	at com.salesforce.androidsdk.security.SalesforceKeyGenerator.generateEncryptionKey(SalesforceKeyGenerator.java:203)
Encryptor: 	at com.salesforce.androidsdk.security.SalesforceKeyGenerator.getEncryptionKey(SalesforceKeyGenerator.java:102)
Encryptor: 	at com.salesforce.androidsdk.app.SalesforceSDKManager.getEncryptionKey(SalesforceSDKManager.java:1129)
Encryptor: 	at com.salesforce.androidsdk.rest.ClientManager.createNewAccount(ClientManager.java:330)
Encryptor: 	at com.salesforce.androidsdk.ui.OAuthWebviewHelper.addAccount(OAuthWebviewHelper.java:645)
Encryptor: 	at com.salesforce.androidsdk.ui.OAuthWebviewHelper$BaseFinishAuthFlowTask.onPostExecute(OAuthWebviewHelper.java:583)
Encryptor: 	at com.salesforce.androidsdk.ui.OAuthWebviewHelper$BaseFinishAuthFlowTask.onPostExecute(OAuthWebviewHelper.java:513)
Encryptor: 	at android.os.AsyncTask.finish(AsyncTask.java:695)
Encryptor: 	at android.os.AsyncTask.-wrap1(Unknown Source:0)
Encryptor: 	at android.os.AsyncTask$InternalHandler.handleMessage(AsyncTask.java:712)
Encryptor: 	at android.os.Handler.dispatchMessage(Handler.java:106)
Encryptor: 	at android.os.Looper.loop(Looper.java:164)
Encryptor: 	at android.app.ActivityThread.main(ActivityThread.java:7000)
Encryptor: 	at java.lang.reflect.Method.invoke(Native Method)
Encryptor: 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:441)
Encryptor: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1408)
Encryptor: Caused by: android.security.KeyStoreException: Unknown error
Encryptor: 	at android.security.KeyStore.getKeyStoreException(KeyStore.java:1139)
Encryptor: 	at android.security.keystore.KeyStoreCryptoOperationChunkedStreamer.doFinal(KeyStoreCryptoOperationChunkedStreamer.java:224)
Encryptor: 	at android.security.keystore.AndroidKeyStoreCipherSpiBase.engineDoFinal(AndroidKeyStoreCipherSpiBase.java:506)
Encryptor: 	... 23 more
SalesforceKeyGenerator: Exception thrown while getting encryption key
SalesforceKeyGenerator: java.lang.NullPointerException: Attempt to invoke virtual method 'byte[] java.lang.String.getBytes(java.nio.charset.Charset)' on a null object reference
SalesforceKeyGenerator: 	at com.salesforce.androidsdk.security.SalesforceKeyGenerator.generateEncryptionKey(SalesforceKeyGenerator.java:204)
SalesforceKeyGenerator: 	at com.salesforce.androidsdk.security.SalesforceKeyGenerator.getEncryptionKey(SalesforceKeyGenerator.java:102)
SalesforceKeyGenerator: 	at com.salesforce.androidsdk.app.SalesforceSDKManager.getEncryptionKey(SalesforceSDKManager.java:1129)
SalesforceKeyGenerator: 	at com.salesforce.androidsdk.rest.ClientManager.createNewAccount(ClientManager.java:330)
SalesforceKeyGenerator: 	at com.salesforce.androidsdk.ui.OAuthWebviewHelper.addAccount(OAuthWebviewHelper.java:645)
SalesforceKeyGenerator: 	at com.salesforce.androidsdk.ui.OAuthWebviewHelper$BaseFinishAuthFlowTask.onPostExecute(OAuthWebviewHelper.java:583)
SalesforceKeyGenerator: 	at com.salesforce.androidsdk.ui.OAuthWebviewHelper$BaseFinishAuthFlowTask.onPostExecute(OAuthWebviewHelper.java:513)
SalesforceKeyGenerator: 	at android.os.AsyncTask.finish(AsyncTask.java:695)
SalesforceKeyGenerator: 	at android.os.AsyncTask.-wrap1(Unknown Source:0)
SalesforceKeyGenerator: 	at android.os.AsyncTask$InternalHandler.handleMessage(AsyncTask.java:712)
SalesforceKeyGenerator: 	at android.os.Handler.dispatchMessage(Handler.java:106)
SalesforceKeyGenerator: 	at android.os.Looper.loop(Looper.java:164)
SalesforceKeyGenerator: 	at android.app.ActivityThread.main(ActivityThread.java:7000)
SalesforceKeyGenerator: 	at java.lang.reflect.Method.invoke(Native Method)
SalesforceKeyGenerator: 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:441)
SalesforceKeyGenerator: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1408)
AndroidRuntime: FATAL EXCEPTION: main
AndroidRuntime: Process: com.mav3rik.parks, PID: 11549
AndroidRuntime: java.lang.NullPointerException
AndroidRuntime: 	at java.util.concurrent.ConcurrentHashMap.putVal(ConcurrentHashMap.java:1019)
AndroidRuntime: 	at java.util.concurrent.ConcurrentHashMap.put(ConcurrentHashMap.java:1014)
AndroidRuntime: 	at com.salesforce.androidsdk.security.SalesforceKeyGenerator.getEncryptionKey(SalesforceKeyGenerator.java:103)
AndroidRuntime: 	at com.salesforce.androidsdk.app.SalesforceSDKManager.getEncryptionKey(SalesforceSDKManager.java:1129)
AndroidRuntime: 	at com.salesforce.androidsdk.rest.ClientManager.createNewAccount(ClientManager.java:330)
AndroidRuntime: 	at com.salesforce.androidsdk.ui.OAuthWebviewHelper.addAccount(OAuthWebviewHelper.java:645)
AndroidRuntime: 	at com.salesforce.androidsdk.ui.OAuthWebviewHelper$BaseFinishAuthFlowTask.onPostExecute(OAuthWebviewHelper.java:583)
AndroidRuntime: 	at com.salesforce.androidsdk.ui.OAuthWebviewHelper$BaseFinishAuthFlowTask.onPostExecute(OAuthWebviewHelper.java:513)
AndroidRuntime: 	at android.os.AsyncTask.finish(AsyncTask.java:695)
AndroidRuntime: 	at android.os.AsyncTask.-wrap1(Unknown Source:0)
AndroidRuntime: 	at android.os.AsyncTask$InternalHandler.handleMessage(AsyncTask.java:712)
AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:106)
AndroidRuntime: 	at android.os.Looper.loop(Looper.java:164)
AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:7000)
AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
AndroidRuntime: 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:441)
AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1408)
```

6. Actual behavior: The application using the mobile SDK crashes during the login process.
7. Expected Behavior: The application should launch the react native views.
8. Error Log:

```
Encryptor: Error during asymmetric decryption
Encryptor: javax.crypto.IllegalBlockSizeException
Encryptor: 	at android.security.keystore.AndroidKeyStoreCipherSpiBase.engineDoFinal(AndroidKeyStoreCipherSpiBase.java:519)
Encryptor: 	at javax.crypto.Cipher.doFinal(Cipher.java:1741)
Encryptor: 	at com.salesforce.androidsdk.analytics.security.Encryptor.decryptWithPrivateKey(Encryptor.java:365)
Encryptor: 	at com.salesforce.androidsdk.analytics.security.Encryptor.decryptWithRSABytes(Encryptor.java:318)
Encryptor: 	at com.salesforce.androidsdk.analytics.security.Encryptor.decryptWithRSA(Encryptor.java:299)
Encryptor: 	at com.salesforce.androidsdk.security.SalesforceKeyGenerator.generateUniqueId(SalesforceKeyGenerator.java:222)
Encryptor: 	at com.salesforce.androidsdk.security.SalesforceKeyGenerator.getUniqueId(SalesforceKeyGenerator.java:90)
Encryptor: 	at com.salesforce.androidsdk.security.SalesforceKeyGenerator.getUniqueId(SalesforceKeyGenerator.java:79)
Encryptor: 	at com.salesforce.androidsdk.security.SalesforceKeyGenerator.generateEncryptionKey(SalesforceKeyGenerator.java:203)
Encryptor: 	at com.salesforce.androidsdk.security.SalesforceKeyGenerator.getEncryptionKey(SalesforceKeyGenerator.java:102)
Encryptor: 	at com.salesforce.androidsdk.app.SalesforceSDKManager.getEncryptionKey(SalesforceSDKManager.java:1129)
Encryptor: 	at com.salesforce.androidsdk.rest.ClientManager.createNewAccount(ClientManager.java:330)
Encryptor: 	at com.salesforce.androidsdk.ui.OAuthWebviewHelper.addAccount(OAuthWebviewHelper.java:645)
Encryptor: 	at com.salesforce.androidsdk.ui.OAuthWebviewHelper$BaseFinishAuthFlowTask.onPostExecute(OAuthWebviewHelper.java:583)
Encryptor: 	at com.salesforce.androidsdk.ui.OAuthWebviewHelper$BaseFinishAuthFlowTask.onPostExecute(OAuthWebviewHelper.java:513)
Encryptor: 	at android.os.AsyncTask.finish(AsyncTask.java:695)
Encryptor: 	at android.os.AsyncTask.-wrap1(Unknown Source:0)
Encryptor: 	at android.os.AsyncTask$InternalHandler.handleMessage(AsyncTask.java:712)
Encryptor: 	at android.os.Handler.dispatchMessage(Handler.java:106)
Encryptor: 	at android.os.Looper.loop(Looper.java:164)
Encryptor: 	at android.app.ActivityThread.main(ActivityThread.java:7000)
Encryptor: 	at java.lang.reflect.Method.invoke(Native Method)
Encryptor: 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:441)
Encryptor: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1408)
Encryptor: Caused by: android.security.KeyStoreException: Unknown error
Encryptor: 	at android.security.KeyStore.getKeyStoreException(KeyStore.java:1139)
Encryptor: 	at android.security.keystore.KeyStoreCryptoOperationChunkedStreamer.doFinal(KeyStoreCryptoOperationChunkedStreamer.java:224)
Encryptor: 	at android.security.keystore.AndroidKeyStoreCipherSpiBase.engineDoFinal(AndroidKeyStoreCipherSpiBase.java:506)
Encryptor: 	... 23 more
SalesforceKeyGenerator: Exception thrown while getting encryption key
SalesforceKeyGenerator: java.lang.NullPointerException: Attempt to invoke virtual method 'byte[] java.lang.String.getBytes(java.nio.charset.Charset)' on a null object reference
SalesforceKeyGenerator: 	at com.salesforce.androidsdk.security.SalesforceKeyGenerator.generateEncryptionKey(SalesforceKeyGenerator.java:204)
SalesforceKeyGenerator: 	at com.salesforce.androidsdk.security.SalesforceKeyGenerator.getEncryptionKey(SalesforceKeyGenerator.java:102)
SalesforceKeyGenerator: 	at com.salesforce.androidsdk.app.SalesforceSDKManager.getEncryptionKey(SalesforceSDKManager.java:1129)
SalesforceKeyGenerator: 	at com.salesforce.androidsdk.rest.ClientManager.createNewAccount(ClientManager.java:330)
SalesforceKeyGenerator: 	at com.salesforce.androidsdk.ui.OAuthWebviewHelper.addAccount(OAuthWebviewHelper.java:645)
SalesforceKeyGenerator: 	at com.salesforce.androidsdk.ui.OAuthWebviewHelper$BaseFinishAuthFlowTask.onPostExecute(OAuthWebviewHelper.java:583)
SalesforceKeyGenerator: 	at com.salesforce.androidsdk.ui.OAuthWebviewHelper$BaseFinishAuthFlowTask.onPostExecute(OAuthWebviewHelper.java:513)
SalesforceKeyGenerator: 	at android.os.AsyncTask.finish(AsyncTask.java:695)
SalesforceKeyGenerator: 	at android.os.AsyncTask.-wrap1(Unknown Source:0)
SalesforceKeyGenerator: 	at android.os.AsyncTask$InternalHandler.handleMessage(AsyncTask.java:712)
SalesforceKeyGenerator: 	at android.os.Handler.dispatchMessage(Handler.java:106)
SalesforceKeyGenerator: 	at android.os.Looper.loop(Looper.java:164)
SalesforceKeyGenerator: 	at android.app.ActivityThread.main(ActivityThread.java:7000)
SalesforceKeyGenerator: 	at java.lang.reflect.Method.invoke(Native Method)
SalesforceKeyGenerator: 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:441)
SalesforceKeyGenerator: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1408)
AndroidRuntime: FATAL EXCEPTION: main
AndroidRuntime: Process: com.mav3rik.parks, PID: 11549
AndroidRuntime: java.lang.NullPointerException
AndroidRuntime: 	at java.util.concurrent.ConcurrentHashMap.putVal(ConcurrentHashMap.java:1019)
AndroidRuntime: 	at java.util.concurrent.ConcurrentHashMap.put(ConcurrentHashMap.java:1014)
AndroidRuntime: 	at com.salesforce.androidsdk.security.SalesforceKeyGenerator.getEncryptionKey(SalesforceKeyGenerator.java:103)
AndroidRuntime: 	at com.salesforce.androidsdk.app.SalesforceSDKManager.getEncryptionKey(SalesforceSDKManager.java:1129)
AndroidRuntime: 	at com.salesforce.androidsdk.rest.ClientManager.createNewAccount(ClientManager.java:330)
AndroidRuntime: 	at com.salesforce.androidsdk.ui.OAuthWebviewHelper.addAccount(OAuthWebviewHelper.java:645)
AndroidRuntime: 	at com.salesforce.androidsdk.ui.OAuthWebviewHelper$BaseFinishAuthFlowTask.onPostExecute(OAuthWebviewHelper.java:583)
AndroidRuntime: 	at com.salesforce.androidsdk.ui.OAuthWebviewHelper$BaseFinishAuthFlowTask.onPostExecute(OAuthWebviewHelper.java:513)
AndroidRuntime: 	at android.os.AsyncTask.finish(AsyncTask.java:695)
AndroidRuntime: 	at android.os.AsyncTask.-wrap1(Unknown Source:0)
AndroidRuntime: 	at android.os.AsyncTask$InternalHandler.handleMessage(AsyncTask.java:712)
AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:106)
AndroidRuntime: 	at android.os.Looper.loop(Looper.java:164)
AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:7000)
AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
AndroidRuntime: 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:441)
AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1408)
```

**Comment by brandonpage** [comment]
Hi @five-zero-four-zero,

Is this issue reproducible?

**Comment by bhariharan** [comment]
@five-zero-four-zero This is fixed [here](https://github.com/forcedotcom/SalesforceMobileSDK-Android/pull/1962) and will be in our next release (`7.3.0`).
