### ISSUE TITLE
SSL Error: Untrusted Certificate Authority

### ISSUE THREAD

**Issue by Manish-Kr09** [forcedotcom/SalesforceMobileSDK-Android#1971]
Please fill out the following details:

1. Version of Mobile SDK Used: 6.0
2. Issue found in Native App or Hybrid App: Hybrid App
3. OS Version: 9/10
4. Device: Samsung A920F/Google Pixel 3a
5. Steps to reproduce: Run the app on corporate network
6. Actual behavior: SSL Error: Untrusted Certificate Authority
7. Expected Behavior: Should load login screen 
8. Error Log: 
```
TIME: 08-23 10:44:58.423, LEVEL: DEBUG, TAG: ResourceReaderHelper, MESSAGE: Asset not found: www/globalstore.jsonTIME: 08-23 10:44:58.429, LEVEL: DEBUG, TAG: ResourceReaderHelper, MESSAGE: Asset not found: www/globalsyncs.json√TIME: 08-23 10:44:58.443, LEVEL: INFO, TAG: ClientManager, MESSAGE: No user account found, EXCEPTION: com.salesforce.androidsdk.rest.ClientManager$AccountInfoNotFoundException: No user account found
	at com.salesforce.androidsdk.rest.ClientManager.peekRestClient(ClientManager.java:154)
	at com.salesforce.androidsdk.rest.ClientManager.peekRestClient(ClientManager.java:138)
	at com.salesforce.androidsdk.phonegap.ui.SalesforceDroidGapActivity.onResume(SalesforceDroidGapActivity.java:215)
	at com.salesforce.androidsdk.ui.SalesforceActivityDelegate.onResume(SalesforceActivityDelegate.java:103)
	at com.salesforce.androidsdk.phonegap.ui.SalesforceDroidGapActivity.onResume(SalesforceDroidGapActivity.java:204)
	at android.app.Instrumentation.callActivityOnResume(Instrumentation.java:1446)
	at android.app.Activity.performResume(Activity.java:7939)
	at android.app.ActivityThread.performResumeActivity(ActivityThread.java:4193)
	at android.app.ActivityThread.handleResumeActivity(ActivityThread.java:4235)
	at android.app.servertransaction.ResumeActivityItem.execute(ResumeActivityItem.java:52)
	at android.app.servertransaction.TransactionExecutor.executeLifecycleState(TransactionExecutor.java:176)
	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:97)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2016)
	at android.os.Handler.dispatchMessage(Handler.java:107)
	at android.os.Looper.loop(Looper.java:214)
	at android.app.ActivityThread.main(ActivityThread.java:7343)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:933)
TIME: 08-23 10:44:58.444, LEVEL: WARN, TAG: BootConfig, MESSAGE: unauthenticatedStartPage set for local app, but it will never be used.tTIME: 08-23 10:44:58.450, LEVEL: INFO, TAG: ClientManager, MESSAGE: No account of type com.xyz.MYxyzApp.login foundjTIME: 08-23 10:44:58.639, LEVEL: DEBUG, TAG: LoginActivity, MESSAGE: User agent login flow being triggered√TIME: 08-23 10:46:05.589, LEVEL: INFO, TAG: ClientManager, MESSAGE: No user account found, EXCEPTION: com.salesforce.androidsdk.rest.ClientManager$AccountInfoNotFoundException: No user account found
	at com.salesforce.androidsdk.rest.ClientManager.peekRestClient(ClientManager.java:154)
	at com.salesforce.androidsdk.rest.ClientManager.peekRestClient(ClientManager.java:138)
	at com.salesforce.androidsdk.phonegap.ui.SalesforceDroidGapActivity.onResume(SalesforceDroidGapActivity.java:215)
	at com.salesforce.androidsdk.ui.SalesforceActivityDelegate.onResume(SalesforceActivityDelegate.java:103)
	at com.salesforce.androidsdk.phonegap.ui.SalesforceDroidGapActivity.onResume(SalesforceDroidGapActivity.java:204)
	at android.app.Instrumentation.callActivityOnResume(Instrumentation.java:1446)
	at android.app.Activity.performResume(Activity.java:7939)
	at android.app.ActivityThread.performResumeActivity(ActivityThread.java:4193)
	at android.app.ActivityThread.handleResumeActivity(ActivityThread.java:4235)
	at android.app.servertransaction.ResumeActivityItem.execute(ResumeActivityItem.java:52)
	at android.app.servertransaction.TransactionExecutor.executeLifecycleState(TransactionExecutor.java:176)
	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:97)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2016)
	at android.os.Handler.dispatchMessage(Handler.java:107)
	at android.os.Looper.loop(Looper.java:214)
	at android.app.ActivityThread.main(ActivityThread.java:7343)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:933)
TIME: 08-23 10:46:05.589, LEVEL: WARN, TAG: BootConfig, MESSAGE: unauthenticatedStartPage set for local app, but it will never be used.tTIME: 08-23 10:46:05.592, LEVEL: INFO, TAG: ClientManager, MESSAGE: No account of type com.xyz.MYxyzApp.login found√TIME: 08-23 10:46:09.533, LEVEL: INFO, TAG: ClientManager, MESSAGE: No user account found, EXCEPTION: com.salesforce.androidsdk.rest.ClientManager$AccountInfoNotFoundException: No user account found
	at com.salesforce.androidsdk.rest.ClientManager.peekRestClient(ClientManager.java:154)
	at com.salesforce.androidsdk.rest.ClientManager.peekRestClient(ClientManager.java:138)
	at com.salesforce.androidsdk.phonegap.ui.SalesforceDroidGapActivity.onResume(SalesforceDroidGapActivity.java:215)
	at com.salesforce.androidsdk.ui.SalesforceActivityDelegate.onResume(SalesforceActivityDelegate.java:103)
	at com.salesforce.androidsdk.phonegap.ui.SalesforceDroidGapActivity.onResume(SalesforceDroidGapActivity.java:204)
	at android.app.Instrumentation.callActivityOnResume(Instrumentation.java:1446)
	at android.app.Activity.performResume(Activity.java:7939)
	at android.app.ActivityThread.performResumeActivity(ActivityThread.java:4193)
	at android.app.ActivityThread.handleResumeActivity(ActivityThread.java:4235)
	at android.app.servertransaction.ResumeActivityItem.execute(ResumeActivityItem.java:52)
	at android.app.servertransaction.TransactionExecutor.executeLifecycleState(TransactionExecutor.java:176)
	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:97)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2016)
	at android.os.Handler.dispatchMessage(Handler.java:107)
	at android.os.Looper.loop(Looper.java:214)
	at android.app.ActivityThread.main(ActivityThread.java:7343)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:933)
TIME: 08-23 10:46:09.533, LEVEL: WARN, TAG: BootConfig, MESSAGE: unauthenticatedStartPage set for local app, but it will never be used.tTIME: 08-23 10:46:09.534, LEVEL: INFO, TAG: ClientManager, MESSAGE: No account of type com.xyz.MYxyzApp.login foundîTIME: 08-23 10:46:12.157, LEVEL: ERROR, TAG: OAuthWebViewHelper, MESSAGE: Received SSL error for server: SSL Error: Untrusted Certificate Authority.√TIME: 08-23 10:46:18.220, LEVEL: INFO, TAG: ClientManager, MESSAGE: No user account found, EXCEPTION: com.salesforce.androidsdk.rest.ClientManager$AccountInfoNotFoundException: No user account found
	at com.salesforce.androidsdk.rest.ClientManager.peekRestClient(ClientManager.java:154)
	at com.salesforce.androidsdk.rest.ClientManager.peekRestClient(ClientManager.java:138)
	at com.salesforce.androidsdk.phonegap.ui.SalesforceDroidGapActivity.onResume(SalesforceDroidGapActivity.java:215)
	at com.salesforce.androidsdk.ui.SalesforceActivityDelegate.onResume(SalesforceActivityDelegate.java:103)
	at com.salesforce.androidsdk.phonegap.ui.SalesforceDroidGapActivity.onResume(SalesforceDroidGapActivity.java:204)
	at android.app.Instrumentation.callActivityOnResume(Instrumentation.java:1446)
	at android.app.Activity.performResume(Activity.java:7939)
	at android.app.ActivityThread.performResumeActivity(ActivityThread.java:4193)
	at android.app.ActivityThread.handleResumeActivity(ActivityThread.java:4235)
	at android.app.servertransaction.ResumeActivityItem.execute(ResumeActivityItem.java:52)
	at android.app.servertransaction.TransactionExecutor.executeLifecycleState(TransactionExecutor.java:176)
	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:97)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2016)
	at android.os.Handler.dispatchMessage(Handler.java:107)
	at android.os.Looper.loop(Looper.java:214)
	at android.app.ActivityThread.main(ActivityThread.java:7343)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:933)
TIME: 08-23 10:46:18.221, LEVEL: WARN, TAG: BootConfig, MESSAGE: unauthenticatedStartPage set for local app, but it will never be used.tTIME: 08-23 10:46:18.222, LEVEL: INFO, TAG: ClientManager, MESSAGE: No account of type com.xyz.MYxyzApp.login foundjTIME: 08-23 10:46:18.279, LEVEL: DEBUG, TAG: LoginActivity, MESSAGE: User agent login flow being triggeredîTIME: 08-23 10:46:22.833, LEVEL: ERROR, TAG: OAuthWebViewHelper, MESSAGE: Received SSL error for server: SSL Error: Untrusted Certificate Authority.
```

**Comment by bhariharan** [comment]
A couple of observations:

- This stack trace indicates that the app is a `hybrid local` app, but you've misconfigured `bootconfig` to include an `unauthenticatedStartPage` value.
```
TIME: 08-23 10:46:09.533, LEVEL: WARN, TAG: BootConfig, MESSAGE: unauthenticatedStartPage set for local app, but it will never be used.tTIME: 08-23 10:46:09.534, LEVEL: INFO, TAG: ClientManager, MESSAGE: No account of type com.xyz.MYxyzApp.login foundîTIME: 08-23 10:46:12.157, LEVEL: ERROR, TAG: OAuthWebViewHelper, MESSAGE: Received SSL error for server: SSL Error: Untrusted Certificate Authority.√TIME: 08-23 10:46:18.220, LEVEL: INFO, TAG: ClientManager, MESSAGE: No user account found, EXCEPTION: com.salesforce.androidsdk.rest.ClientManager$AccountInfoNotFoundException: No user account found
```
- This error indicates a problem with the server - it's a callback within our `WebView` when it communicates with the server.
```
MESSAGE: Received SSL error for server: SSL Error: Untrusted Certificate Authority.
```

Open Questions/Things to Try:
- Which server are you attempting to connect to? Verify that the server is compliant with `TLS 1.2`, `PFS`, etc.
- Which device are you using? Verify that it's a newer device that uses `TLS 1.2` for network requests.

**Comment by coolmk09** [comment]
Hey @bhariharan, Here is my boot config file
{
    "remoteAccessConsumerKey": "************-consumer key ****************",
    "oauthRedirectURI": "*** - Custom redirect URL *************",
    "oauthScopes": ["web", "api"],
    "isLocal": true,
    "startPage": "index.html",
    "errorPage": "Error.html",
    **"shouldAuthenticate": true,**
    "attemptOfflineLoad": true
}
It's using should authenticate false, For SSL error as per logs I am not getting it, I am checking it. 
The interesting point here is It's working fine when using salesforce1 or android browser directly. I believe salesforce 1 is using SF SDK which we are using (there might be difference of version), Is there anything different in SDK used by Salesforce1 and Mobile SDK available at github?

**Comment by bhariharan** [comment]
@coolmk09 Sure, I can leave the issue open, but I highly doubt that this is an issue with `Mobile SDK` code. It's more likely a configuration issue, either with the client or the server. The issue you're seeing is within a webview, which we don't control. Besides, like you mentioned, `Salesforce1` is using `Mobile SDK` as well, and since it works with that, it's probably a connected app configuration issue with your custom connected app. Could you try the following steps and let me know if that works:

- Generate a new `hybrid_local` app with `forcedroid`.
- Run the generated app and attempt to authenticate to your org.

If that works, next try the following steps:

- Generate a new `hybrid_local` app with `forcedroid`.
- Replace the consumer key and callback URL in `bootconfig.json` with your custom app's values.
- Run the generated app and attempt to authenticate to your org.

Let me know if this works.
