### ISSUE TITLE
the SDK crashed when sending a file 

### ISSUE THREAD

**Issue by tsengvn** [forcedotcom/SalesforceMobileSDK-Android#1996]
Please fill out the following details:

1. Version of Mobile SDK Used: 
com.salesforce.service:chat-ui:3.1.0
com.squareup.okhttp3:okhttp:3.12.4

2. Issue found in Native App or Hybrid App:
Native App

3. OS Version:
Any OS version

4. Device:
Any devices

5. Steps to reproduce:
- Set the device language to Thai or Chinese
- Chat with agent
- Send a file to agent

6. Actual behavior:
- App will be crashed

7. Expected Behavior:
- Should not be crashed

8. Error Log:

```
Fatal Exception: java.lang.IllegalArgumentException: Unexpected char 0xe15 at 37 in Content-Disposition value: form-data; name="file"; filename="16 ต.ค. 2019 09:23:26 +0700.jpg"
       at okhttp3.Headers.checkValue(SourceFile:272)
       at okhttp3.Headers.of(SourceFile:224)
       at com.salesforce.android.chat.core.internal.filetransfer.FileUploadRequestComposer.createRequestBody(SourceFile:114)
       at com.salesforce.android.chat.core.internal.filetransfer.FileUploadRequestComposer.createRequest(SourceFile:121)
       at com.salesforce.android.chat.core.internal.filetransfer.InternalFileTransferAssistant.buildFileUploadRequest(SourceFile:150)
       at com.salesforce.android.chat.core.internal.filetransfer.InternalFileTransferAssistant.uploadFile(SourceFile:131)
       at com.salesforce.android.chat.ui.internal.filetransfer.ImageSender$1.consume(SourceFile:86)
       at com.salesforce.android.chat.ui.internal.filetransfer.ImageSender$1.consume(SourceFile:84)
       at com.salesforce.android.service.common.utilities.functional.Optional.ifPresent(SourceFile:77)
       at com.salesforce.android.chat.ui.internal.filetransfer.ImageSender.onFinalImageRendered(SourceFile:84)
       at com.salesforce.android.chat.ui.internal.filetransfer.ImageProcessor.notifyListeners(SourceFile:138)
       at com.salesforce.android.chat.ui.internal.filetransfer.ImageProcessor.access$500(SourceFile:49)
       at com.salesforce.android.chat.ui.internal.filetransfer.ImageProcessor$4.handleResult(SourceFile:118)
       at com.salesforce.android.chat.ui.internal.filetransfer.ImageProcessor$4.handleResult(SourceFile:116)
       at com.salesforce.android.service.common.utilities.control.BasicAsync.setResult(SourceFile:243)
       at com.salesforce.android.service.common.utilities.threading.JobQueue$JobAsync.access$001(SourceFile:136)
       at com.salesforce.android.service.common.utilities.threading.JobQueue$JobAsync$1.run(SourceFile:150)
       at android.os.Handler.handleCallback(Handler.java:873)
       at android.os.Handler.dispatchMessage(Handler.java:99)
       at android.os.Looper.loop(Looper.java:214)
       at android.app.ActivityThread.main(ActivityThread.java:7050)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:965)




Fatal Exception: java.lang.IllegalArgumentException: Unexpected char 0x6708 at 39 in Content-Disposition value: form-data; name="file"; filename="21 10月 2019 17:40:30 +0800.jpg"
       at okhttp3.Headers.checkValue(Headers.java:272)
       at okhttp3.Headers.of(Headers.java:224)
       at com.salesforce.android.chat.core.internal.filetransfer.FileUploadRequestComposer.createRequestBody(FileUploadRequestComposer.java:114)
       at com.salesforce.android.chat.core.internal.filetransfer.FileUploadRequestComposer.createRequest(FileUploadRequestComposer.java:121)
       at com.salesforce.android.chat.core.internal.filetransfer.InternalFileTransferAssistant.buildFileUploadRequest(InternalFileTransferAssistant.java:150)
       at com.salesforce.android.chat.core.internal.filetransfer.InternalFileTransferAssistant.uploadFile(InternalFileTransferAssistant.java:131)
       at com.salesforce.android.chat.ui.internal.filetransfer.ImageSender$1.consume(ImageSender.java:86)
       at com.salesforce.android.chat.ui.internal.filetransfer.ImageSender$1.consume(ImageSender.java:84)
       at com.salesforce.android.service.common.utilities.functional.Optional.ifPresent(Optional.java:77)
       at com.salesforce.android.chat.ui.internal.filetransfer.ImageSender.onFinalImageRendered(ImageSender.java:84)
       at com.salesforce.android.chat.ui.internal.filetransfer.ImageProcessor.notifyListeners(ImageProcessor.java:138)
       at com.salesforce.android.chat.ui.internal.filetransfer.ImageProcessor.access$500(ImageProcessor.java:49)
       at com.salesforce.android.chat.ui.internal.filetransfer.ImageProcessor$4.handleResult(ImageProcessor.java:118)
       at com.salesforce.android.chat.ui.internal.filetransfer.ImageProcessor$4.handleResult(ImageProcessor.java:116)
       at com.salesforce.android.service.common.utilities.control.BasicAsync.setResult(BasicAsync.java:243)
       at com.salesforce.android.service.common.utilities.threading.JobQueue$JobAsync.access$001(JobQueue.java:136)
       at com.salesforce.android.service.common.utilities.threading.JobQueue$JobAsync$1.run(JobQueue.java:150)
       at android.os.Handler.handleCallback(Handler.java:907)
       at android.os.Handler.dispatchMessage(Handler.java:105)
       at android.os.Looper.loop(Looper.java:216)
       at android.app.ActivityThread.main(ActivityThread.java:7625)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:524)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:987)
```

**Comment by bhariharan** [comment]
@tsengvn This is not the right forum to post `ServiceSDK` bugs, `MobileSDK` is a different product.
