### ISSUE TITLE
Crash after login

### ISSUE THREAD

**Issue by aishlin** [forcedotcom/SalesforceMobileSDK-Android#2001]
Please fill out the following details:

1. Version of Mobile SDK Used: 
```
    implementation 'com.salesforce.service:servicesdk:222.0.1'
    implementation('com.salesforce.mobilesdk:SalesforceSDK:7.3.0') {
        transitive = true
    }
```
2. Issue found in Native App or Hybrid App:
Native App
3. OS Version:
Android9
4. Device: SM-G965F
5. Steps to reproduce: Login to saleforce, wait for a while and crash appears
6. Actual behavior: Crash
7. Expected Behavior: Avoid crashing
8. Error Log:
```
 java.lang.RuntimeException: An error occurred while executing doInBackground()
        at android.os.AsyncTask$3.done(AsyncTask.java:354)
        at java.util.concurrent.FutureTask.finishCompletion(FutureTask.java:383)
        at java.util.concurrent.FutureTask.setException(FutureTask.java:252)
        at java.util.concurrent.FutureTask.run(FutureTask.java:271)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
        at java.lang.Thread.run(Thread.java:764)
     Caused by: java.lang.IllegalStateException: cannot make a new request because the previous response is still open: please call response.close()
        at okhttp3.internal.connection.Transmitter.newExchange$okhttp(Transmitter.kt:156)
        at okhttp3.internal.connection.ConnectInterceptor.intercept(ConnectInterceptor.kt:35)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:112)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:87)
        at okhttp3.internal.cache.CacheInterceptor.intercept(CacheInterceptor.kt:82)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:112)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:87)
        at okhttp3.internal.http.BridgeInterceptor.intercept(BridgeInterceptor.kt:84)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:112)
        at okhttp3.internal.http.RetryAndFollowUpInterceptor.intercept(RetryAndFollowUpInterceptor.kt:71)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:112)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:87)
        at com.salesforce.androidsdk.rest.RestClient$OAuthRefreshInterceptor.intercept(RestClient.java:676)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:112)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:87)
        at okhttp3.RealCall.getResponseWithInterceptorChain(RealCall.kt:184)
        at okhttp3.RealCall.execute(RealCall.kt:66)
        at com.salesforce.androidsdk.rest.RestClient.sendSync(RestClient.java:369)
        at com.salesforce.androidsdk.analytics.AILTNPublisher.publishLogLines(AILTNPublisher.java:135)
        at com.salesforce.androidsdk.analytics.AILTNPublisher.publish(AILTNPublisher.java:98)
        at com.salesforce.androidsdk.analytics.SalesforceAnalyticsManager.publishEvents(SalesforceAnalyticsManager.java:315)
        at com.salesforce.androidsdk.analytics.SalesforceAnalyticsManager.publishAllEvents(SalesforceAnalyticsManager.java:274)
        at com.salesforce.androidsdk.analytics.AnalyticsPublisherService.handleActionPublish(AnalyticsPublisherService.java:75)
        at com.salesforce.androidsdk.analytics.AnalyticsPublisherService.onHandleWork(AnalyticsPublisherService.java:63)
        at androidx.core.app.JobIntentService$CommandProcessor.doInBackground(JobIntentService.java:392)
        at androidx.core.app.JobIntentService$CommandProcessor.doInBackground(JobIntentService.java:383)
        at android.os.AsyncTask$2.call(AsyncTask.java:333)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167) 
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641) 
        at java.lang.Thread.run(Thread.java:764) 
```

**Comment by murilodag** [comment]
Same here for Salesforce 8.1.0.

**Comment by RacZo** [comment]
Same here using Android SDK v8.1.0 and native_kotlin on a Pixel 4XL with Android 10.

**Comment by wmathurin** [comment]
This [commit](https://github.com/forcedotcom/SalesforceMobileSDK-Android/commit/a1187cf10fd029888f34f32de3fedc4c666735bf) should fix the issue. It will be in our next version of the Mobile SDK (9.0).
