### ISSUE TITLE
After updating salesforcemobile sdk v7.3.0, my app crashes when receiving a push notification.

### ISSUE THREAD

**Issue by hmuronaka** [forcedotcom/SalesforceMobileSDK-Android#2018]
Please fill out the following details:

1. Version of Mobile SDK Used: 
salesforce mobile sdk v7.3.0

2. Issue found in Native App or Hybrid App:
native android app

3. OS Version:
android v7.0.0

4. Device:
SG-05G

5. Steps to reproduce:

I updated my app's salesforce mobile sdk from v6.2.0 to v7.3.0.
after updating, the app crashes when the app receive push notification every time.

6. Actual behavior:
The app crashes when the app receive push notification.

7. Expected Behavior:
The app can receive push notification and doesn’t crash.

8. Error Log:
```
E/AndroidRuntime: FATAL EXCEPTION: Firebase-SFDCFcmListenerService
    Process: —, PID: 25132
    java.lang.IllegalStateException: Default FirebaseApp is not initialized in this process —. Make sure to call FirebaseApp.initializeApp(Context) first.
        at com.google.firebase.FirebaseApp.getInstance(com.google.firebase:firebase-common@@17.1.0:186)
        at com.google.firebase.messaging.MessagingAnalytics.zza(com.google.firebase:firebase-messaging@@19.0.1:75)
        at com.google.firebase.messaging.MessagingAnalytics.logNotificationReceived(com.google.firebase:firebase-messaging@@19.0.1:2)
        at com.google.firebase.messaging.FirebaseMessagingService.zzc(com.google.firebase:firebase-messaging@@19.0.1:50)
        at com.google.firebase.messaging.zzg.run(com.google.firebase:firebase-messaging@@19.0.1:2)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607)
        at com.google.android.gms.common.util.concurrent.zza.run(Unknown Source)
        at java.lang.Thread.run(Thread.java:762)
```
9: Question
- Does SalesforceMobileSDK v7.3.0 need Firebase and initialize?
- How can I solve this problem.

**Comment by hmuronaka** [comment]
Although Isetted up Firebase (google-services.json)..., is this the correct way to use it?

**Comment by bhariharan** [comment]
@hmuronaka You should NOT use `google-services.json` for apps built on Mobile SDK. This will cause conflicts. Instead, you need to set up your project key in our `bootconfig.xml` (or `bootconfig.json`, if you're building a hybrid app).

- Our development guide has a detailed walkthrough of how to set up push notifications for Android. Take a look [here](https://developer.salesforce.com/docs/atlas.en-us.noversion.mobile_sdk.meta/mobile_sdk/push_android_code.htm).
- I would also recommend using the latest version, `Mobile SDK 8.0.0`.

Feel free to reopen this issue if you are still facing issues after following the examples in our development guide.
