### ISSUE TITLE
App throwing Error during asymmetric decryption error, crashing first time after throwing it

### ISSUE THREAD

**Issue by oolufemi** [forcedotcom/SalesforceMobileSDK-Android#2023]
Please fill out the following details:

1. Version of Mobile SDK Used: 8.0.0
2. Issue found in Native App or Hybrid App: Native
3. OS Version: Android 10
4. Device: Galaxy Samsung S10
5. Steps to reproduce: 
Install App, enter login info and tap login, tap allow - App crashes
6. Actual behavior:
App crashes (first time), it persists the login and next time it doesn't crash but keeps throwing same error in background. I have got access to 2 S10 phones, I constantly get this on one of them while the other works. I have already tries 7.3.0 version but it has a different problem hence the reason I'm going for latest.
7. Expected Behaviour: 
8. Error Log:
2020-01-06 14:12:24.768 25355-25355/? E/Encryptor: Error during asymmetric decryption
```
    javax.crypto.IllegalBlockSizeException
        at android.security.keystore.AndroidKeyStoreCipherSpiBase.engineDoFinal(AndroidKeyStoreCipherSpiBase.java:519)
        at javax.crypto.Cipher.doFinal(Cipher.java:2055)
        at com.salesforce.androidsdk.analytics.security.Encryptor.decryptWithPrivateKey(Encryptor.java:365)
        at com.salesforce.androidsdk.analytics.security.Encryptor.decryptWithRSABytes(Encryptor.java:318)
        at com.salesforce.androidsdk.analytics.security.Encryptor.decryptWithRSA(Encryptor.java:299)
        at com.salesforce.androidsdk.security.SalesforceKeyGenerator.generateUniqueId(SalesforceKeyGenerator.java:191)
        at com.salesforce.androidsdk.security.SalesforceKeyGenerator.getUniqueId(SalesforceKeyGenerator.java:90)
        at com.salesforce.androidsdk.security.SalesforceKeyGenerator.getUniqueId(SalesforceKeyGenerator.java:79)
        at com.salesforce.androidsdk.security.SalesforceKeyGenerator.generateEncryptionKey(SalesforceKeyGenerator.java:172)
        at com.salesforce.androidsdk.security.SalesforceKeyGenerator.getEncryptionKey(SalesforceKeyGenerator.java:105)
        at com.salesforce.androidsdk.app.SalesforceSDKManager.getEncryptionKey(SalesforceSDKManager.java:1108)
        at com.salesforce.androidsdk.rest.ClientManager.createNewAccount(ClientManager.java:323)
        at com.salesforce.androidsdk.ui.OAuthWebviewHelper.addAccount(OAuthWebviewHelper.java:645)
        at com.salesforce.androidsdk.ui.OAuthWebviewHelper$BaseFinishAuthFlowTask.onPostExecute(OAuthWebviewHelper.java:583)
        at com.salesforce.androidsdk.ui.OAuthWebviewHelper$BaseFinishAuthFlowTask.onPostExecute(OAuthWebviewHelper.java:513)
        at android.os.AsyncTask.finish(AsyncTask.java:755)
        at android.os.AsyncTask.access$900(AsyncTask.java:192)
        at android.os.AsyncTask$InternalHandler.handleMessage(AsyncTask.java:772)
        at android.os.Handler.dispatchMessage(Handler.java:107)
        at android.os.Looper.loop(Looper.java:237)
        at android.app.ActivityThread.main(ActivityThread.java:7762)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1047)
     Caused by: android.security.KeyStoreException: Unknown error
        at android.security.KeyStore.getKeyStoreException(KeyStore.java:1489)
        at android.security.keystore.KeyStoreCryptoOperationChunkedStreamer.doFinal(KeyStoreCryptoOperationChunkedStreamer.java:224)
        at android.security.keystore.AndroidKeyStoreCipherSpiBase.engineDoFinal(AndroidKeyStoreCipherSpiBase.java:506)
        at javax.crypto.Cipher.doFinal(Cipher.java:2055) 
        at com.salesforce.androidsdk.analytics.security.Encryptor.decryptWithPrivateKey(Encryptor.java:365) 
        at com.salesforce.androidsdk.analytics.security.Encryptor.decryptWithRSABytes(Encryptor.java:318) 
        at com.salesforce.androidsdk.analytics.security.Encryptor.decryptWithRSA(Encryptor.java:299) 
        at com.salesforce.androidsdk.security.SalesforceKeyGenerator.generateUniqueId(SalesforceKeyGenerator.java:191) 
        at com.salesforce.androidsdk.security.SalesforceKeyGenerator.getUniqueId(SalesforceKeyGenerator.java:90) 
        at com.salesforce.androidsdk.security.SalesforceKeyGenerator.getUniqueId(SalesforceKeyGenerator.java:79) 
        at com.salesforce.androidsdk.security.SalesforceKeyGenerator.generateEncryptionKey(SalesforceKeyGenerator.java:172) 
        at com.salesforce.androidsdk.security.SalesforceKeyGenerator.getEncryptionKey(SalesforceKeyGenerator.java:105) 
        at com.salesforce.androidsdk.app.SalesforceSDKManager.getEncryptionKey(SalesforceSDKManager.java:1108) 
        at com.salesforce.androidsdk.rest.ClientManager.createNewAccount(ClientManager.java:323) 
        at com.salesforce.androidsdk.ui.OAuthWebviewHelper.addAccount(OAuthWebviewHelper.java:645) 
        at com.salesforce.androidsdk.ui.OAuthWebviewHelper$BaseFinishAuthFlowTask.onPostExecute(OAuthWebviewHelper.java:583) 
        at com.salesforce.androidsdk.ui.OAuthWebviewHelper$BaseFinishAuthFlowTask.onPostExecute(OAuthWebviewHelper.java:513) 
        at android.os.AsyncTask.finish(AsyncTask.java:755) 
        at android.os.AsyncTask.access$900(AsyncTask.java:192) 
        at android.os.AsyncTask$InternalHandler.handleMessage(AsyncTask.java:772) 
        at android.os.Handler.dispatchMessage(Handler.java:107) 
        at android.os.Looper.loop(Looper.java:237) 
        at android.app.ActivityThread.main(ActivityThread.java:7762) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1047) 
2020-01-06 14:12:24.769 25355-25355/? E/SalesforceKeyGenerator: Exception thrown while getting encryption key
    java.lang.NullPointerException: Attempt to invoke virtual method 'byte[] java.lang.String.getBytes(java.nio.charset.Charset)' on a null object reference
        at com.salesforce.androidsdk.security.SalesforceKeyGenerator.generateEncryptionKey(SalesforceKeyGenerator.java:173)
        at com.salesforce.androidsdk.security.SalesforceKeyGenerator.getEncryptionKey(SalesforceKeyGenerator.java:105)
        at com.salesforce.androidsdk.app.SalesforceSDKManager.getEncryptionKey(SalesforceSDKManager.java:1108)
        at com.salesforce.androidsdk.rest.ClientManager.createNewAccount(ClientManager.java:323)
        at com.salesforce.androidsdk.ui.OAuthWebviewHelper.addAccount(OAuthWebviewHelper.java:645)
        at com.salesforce.androidsdk.ui.OAuthWebviewHelper$BaseFinishAuthFlowTask.onPostExecute(OAuthWebviewHelper.java:583)
        at com.salesforce.androidsdk.ui.OAuthWebviewHelper$BaseFinishAuthFlowTask.onPostExecute(OAuthWebviewHelper.java:513)
        at android.os.AsyncTask.finish(AsyncTask.java:755)
        at android.os.AsyncTask.access$900(AsyncTask.java:192)
        at android.os.AsyncTask$InternalHandler.handleMessage(AsyncTask.java:772)
        at android.os.Handler.dispatchMessage(Handler.java:107)
        at android.os.Looper.loop(Looper.java:237)
        at android.app.ActivityThread.main(ActivityThread.java:7762)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1047)
2020-01-06 14:12:24.771 25355-25355/? D/AccountManager: addAccountExplicitly()Account 
2020-01-06 14:12:24.773 5748-8268/? D/DeviceAccountPolicy: loadAccounts() : userId  = 0
```

**Comment by bhariharan** [comment]
@oolufemi This is typically indicative of a corrupted/inaccessible `Keystore` on that particular device. A few questions:
- Are you able to reproduce this issue on other devices?
- Was this an upgrade or a fresh installation of the app? If this was an upgrade, could you uninstall and install your app?
- Are you able to reproduce the same error with one of our sample apps on this device?

**Comment by oolufemi** [comment]
Hi @bhariharan 

Are you able to reproduce this issue on other devices?
_Not all, in all tried on 3 devices. 
Device1, Samsung Galaxy  S10 -  had the issue
Device2, Samsung Galaxy  S10 -  Didn't have the issue
Device2,  google pixel 3 -  Didn't have the issue_

Was this an upgrade or a fresh installation of the app? If this was an upgrade, could you uninstall and install your app?
_It was a fresh installation_

Are you able to reproduce the same error with one of our sample apps on this device?
_I haven't tried this out_

**Comment by oolufemi** [comment]
@bhariharan 

I tried again and I didn't get that issue but got the below. Note that we have push notifications configured and it worked fine in 7.1.2.

Process: kimble.timeandexpenses2, PID: 2800
    java.lang.IllegalStateException: Default FirebaseApp is not initialized in this process kxxx.app. Make sure to call FirebaseApp.initializeApp(Context) first.
        at com.google.firebase.FirebaseApp.getInstance(com.google.firebase:firebase-common@@19.2.0:183)
        at com.google.firebase.iid.FirebaseInstanceId.getInstance(com.google.firebase:firebase-iid@@20.0.1:1)
        at com.google.firebase.iid.zzat.<init>(com.google.firebase:firebase-iid@@20.0.1:16)
        at com.google.firebase.iid.zzat.<init>(com.google.firebase:firebase-iid@@20.0.1:1)
        at com.google.firebase.iid.FirebaseInstanceId.<init>(com.google.firebase:firebase-iid@@20.0.1:15)
        at com.google.firebase.iid.FirebaseInstanceId.<init>(com.google.firebase:firebase-iid@@20.0.1:7)
        at com.google.firebase.iid.zzak.create(com.google.firebase:firebase-iid@@20.0.1:6)
        at com.google.firebase.components.ComponentRuntime.lambda$new$0(com.google.firebase:firebase-common@@19.2.0:70)
        at com.google.firebase.components.ComponentRuntime$$Lambda$1.get(Unknown Source:4)
        at com.google.firebase.components.Lazy.get(com.google.firebase:firebase-common@@19.2.0:55)
        at com.google.firebase.components.ComponentRuntime.initializeEagerComponents(com.google.firebase:firebase-common@@19.2.0:159)
        at com.google.firebase.FirebaseApp.initializeAllApis(com.google.firebase:firebase-common@@19.2.0:561)
        at com.google.firebase.FirebaseApp.initializeApp(com.google.firebase:firebase-common@@19.2.0:303)
        at com.salesforce.androidsdk.push.PushMessaging.initializeFirebaseIfNeeded(PushMessaging.java:166)
        at com.salesforce.androidsdk.push.PushMessaging.register(PushMessaging.java:101)
        at com.salesforce.androidsdk.ui.OAuthWebviewHelper.addAccount(OAuthWebviewHelper.java:673)
        at com.salesforce.androidsdk.ui.OAuthWebviewHelper$BaseFinishAuthFlowTask.onPostExecute(OAuthWebviewHelper.java:583)
        at com.salesforce.androidsdk.ui.OAuthWebviewHelper$BaseFinishAuthFlowTask.onPostExecute(OAuthWebviewHelper.java:513)
        at android.os.AsyncTask.finish(AsyncTask.java:755)
        at android.os.AsyncTask.access$900(AsyncTask.java:192)
        at android.os.AsyncTask$InternalHandler.handleMessage(AsyncTask.java:772)
        at android.os.Handler.dispatchMessage(Handler.java:107)
        at android.os.Looper.loop(Looper.java:237)
        at android.app.ActivityThread.main(ActivityThread.java:7762)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1047)

**Comment by oolufemi** [comment]
Are you able to reproduce the same error with one of our sample apps on this device?
_I have now tried this and it worked fine, used the RestExplorer App_

**Comment by bhariharan** [comment]
@oolufemi This seems like a device-specific issue with that particular `Samsung Galaxy S10`. Perhaps a "Factory Reset" of this device would fix the Keystore corruption issues.

**Comment by oolufemi** [comment]
@bhariharan 

The other device with the Samsung Galaxy S10 is also now having the same problem, crashing and throwing the error below. All we did was uninstall, install the previous version, uninstall it and reinstall. I understand the Keystore could be corrupt but it looks like it's the app thats doing it. 

**Do you think this corruption could some how be happening during transitioning through versions even after uninstalling?** Our current app is on 7.1.2 and this one is on 8.0.0 

Also the current app needs this change because we started having issues with the 7.1.2 version in this same area for Android 10

**Comment by bhariharan** [comment]
@oolufemi It could be something app-specific too, given that it's not reproducible in our sample apps. Most of the `Keystore` code is in [this class](https://github.com/forcedotcom/SalesforceMobileSDK-Android/blob/master/libs/SalesforceSDK/src/com/salesforce/androidsdk/security/KeyStoreWrapper.java#L215). It's pretty simple code, but maybe uninstalling the app is the key here. Maybe the keys with the same name aren't wiped from the `Keystore` when uninstalled. You can try adding a couple of lines of code when your app starts up to explicitly remove existing app keys from the `Keystore` and see if that helps?

**Comment by oolufemi** [comment]
@bhariharan I will have a look thanks

**Comment by oolufemi** [comment]
Hi @bhariharan 

I tried clearing the app's keystore, logging out no luck.

I have just gotten this issue with an Android 9 user who installed the app for the first time on their device. 
It seems to be an Android issue causing this, see https://issuetracker.google.com/issues/73020934
https://issuetracker.google.com/issues/36708951
https://issuetracker.google.com/issues/37075898

I think you need to have another look at this. 

Cheers

**Comment by bhariharan** [comment]
@oolufemi Thanks for bringing this to my attention. It appears that there might be some known issues with `BouncyCastle` and `Keystore` on older versions of `Android`. The good news is that on newer versions, `Android` has switched to using `Conscrypt` instead of `BouncyCastle`. This should address the problem eventually. We aren't seeing these errors in any other internal or external apps either. There might be an app-specific aspect to this. We might need to evaluate your use cases.

**Comment by AxesandGrinds** [comment]
This is not app-specific. This is your Salesforce authentication SDK at fault. I get the same decryption error that's crashing my  OnePlus Nord N10 5G. But it's not crashing on my Samsung Galaxy S21 Ultra. This is crazy. It's purely an issue when user opens app, it crashes.

**Comment by AxesandGrinds** [comment]
> @oolufemi Thanks for bringing this to my attention. It appears that there might be some known issues with `BouncyCastle` and `Keystore` on older versions of `Android`. The good news is that on newer versions, `Android` has switched to using `Conscrypt` instead of `BouncyCastle`. This should address the problem eventually. We aren't seeing these errors in any other internal or external apps either. There might be an app-specific aspect to this. We might need to evaluate your use cases.

This is not app-specific. This is your Salesforce authentication SDK at fault. I get the same decryption error that's crashing my OnePlus Nord N10 5G. But it's not crashing on my Samsung Galaxy S21 Ultra. This is crazy. It's purely an issue when user opens app, it crashes.
