### ISSUE TITLE
ClassNotFoundException: Didn't find class "androidx.legacy.widget.Space"

### ISSUE THREAD

**Issue by davidmigloz** [forcedotcom/SalesforceMobileSDK-Android#2040]
1. Version of Mobile SDK Used: `com.salesforce.service:chat-ui:4.1.0`
2. Issue found in Native App or Hybrid App: Android native
3. OS Version: Any Android version that we support (>Android 4.4)
4. Device: Multiple manufactures 
5. Steps to reproduce:
  - Start a chat
  - onSessionStateChange: Verification
  - onSessionStateChange: Initializing
  - onSessionStateChange: Connecting
  - onSessionStateChange: InQueue
  - onSessionStateChange: Connected
  - -> Crash
6. Actual behavior: the app crashes when the user is connected with the customer care agent
7. Expected Behavior: the app shouldn't crash and the chat should work
8. Error Log:
```
Fatal Exception: java.lang.RuntimeException: Unable to start activity ComponentInfo{com.xxx/com.salesforce.android.chat.ui.internal.chatfeed.ChatFeedActivity}: android.view.InflateException: Binary XML file line #52: Binary XML file line #36: Error inflating class androidx.legacy.widget.Space
       at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3430)
       at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3614)
       at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:86)
       at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:108)
       at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:68)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2199)
       at android.os.Handler.dispatchMessage(Handler.java:112)
       at android.os.Looper.loop(Looper.java:216)
       at android.app.ActivityThread.main(ActivityThread.java:7625)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:524)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:987)
Caused by android.view.InflateException: Binary XML file line #52: Binary XML file line #36: Error inflating class androidx.legacy.widget.Space
Caused by android.view.InflateException: Binary XML file line #36: Error inflating class androidx.legacy.widget.Space
Caused by java.lang.ClassNotFoundException: Didn't find class "androidx.legacy.widget.Space" on path: DexPathList[[zip file "/data/app/com.xxx-tjKR1FlqbJGDl899fuxKgw==/base.apk", zip file "/data/app/com.xxx-tjKR1FlqbJGDl899fuxKgw==/split_config.arm64_v8a.apk", zip file "/data/app/com.xxx-tjKR1FlqbJGDl899fuxKgw==/split_config.xxhdpi.apk"],nativeLibraryDirectories=[/data/app/com.xxx-tjKR1FlqbJGDl899fuxKgw==/lib/arm64, /data/app/com.xxx-tjKR1FlqbJGDl899fuxKgw==/base.apk!/lib/arm64-v8a, /data/app/com.xxx-tjKR1FlqbJGDl899fuxKgw==/split_config.arm64_v8a.apk!/lib/arm64-v8a, /data/app/com.xxx-tjKR1FlqbJGDl899fuxKgw==/split_config.xxhdpi.apk!/lib/arm64-v8a, /system/lib64, /product/lib64]]
       at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:134)
       at java.lang.ClassLoader.loadClass(ClassLoader.java:379)
       at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
       at android.view.LayoutInflater.createView(LayoutInflater.java:613)
       at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:801)
       at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:741)
       at android.view.LayoutInflater.rInflate(LayoutInflater.java:874)
       at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:835)
       at android.view.LayoutInflater.parseInclude(LayoutInflater.java:1006)
       at android.view.LayoutInflater.rInflate(LayoutInflater.java:870)
       at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:835)
       at android.view.LayoutInflater.rInflate(LayoutInflater.java:877)
       at android.view.LayoutInflater.parseInclude(LayoutInflater.java:974)
       at android.view.LayoutInflater.rInflate(LayoutInflater.java:870)
       at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:835)
       at android.view.LayoutInflater.inflate(LayoutInflater.java:515)
       at android.view.LayoutInflater.inflate(LayoutInflater.java:423)
       at android.view.LayoutInflater.inflate(LayoutInflater.java:374)
       at androidx.appcompat.app.AppCompatDelegateImpl.setContentView(AppCompatDelegateImpl.java:555)
       at androidx.appcompat.app.AppCompatActivity.setContentView(AppCompatActivity.java:161)
       at com.salesforce.android.chat.ui.internal.chatfeed.ChatFeedActivityDelegate.onCreate(ChatFeedActivityDelegate.java:140)
       at com.salesforce.android.chat.ui.internal.chatfeed.ChatFeedActivity.onCreate(ChatFeedActivity.java:59)
       at android.app.Activity.performCreate(Activity.java:7458)
       at android.app.Activity.performCreate(Activity.java:7448)
       at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1286)
       at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3409)
       at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3614)
       at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:86)
       at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:108)
       at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:68)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2199)
       at android.os.Handler.dispatchMessage(Handler.java:112)
       at android.os.Looper.loop(Looper.java:216)
       at android.app.ActivityThread.main(ActivityThread.java:7625)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:524)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:987)
```

App details:
- buildToolsVersion: "29.0.2"
- minSdkVersion    : 21
- targetSdkVersion : 29
- compileSdkVersion: 29
- android gradle plugin: 3.5.3

**Comment by bhariharan** [comment]
ServiceSDK's Chat is a different product. You have the wrong Github forum.

**Comment by davidmigloz** [comment]
Where should I submit the bug report? 
I used to submit them to this repository (https://github.com/forcedotcom/ServiceSDK-Android), but they don't accept issues anymore...

**Comment by bhariharan** [comment]
You'll need to open a case with Salesforce.

**Comment by davidmigloz** [comment]
Could you provide me with the link where to open the case? I'm a bit lost.
Thanks for your help.

**Comment by bhariharan** [comment]
[This article](https://help.salesforce.com/articleView?id=workcom_contact_support.htm&type=5) should help.

**Comment by davidmigloz** [comment]
Thanks!

**Comment by abhishek-rupeek** [comment]
Facing same issue, any update on this?
