### ISSUE TITLE
java.lang.ClassNotFoundException: Didn't find class "com.google.firebase.iid.FirebaseInstanceIdService"

### ISSUE THREAD

**Issue by geekandt** [forcedotcom/SalesforceMobileSDK-Android#2047]
Please fill out the following details:

1. Version of Mobile SDK Used: 7.3.0
2. Issue found in Native App or Hybrid App: Native App
3. OS Version: Android 5 and up
4. Device: All devices
5. Steps to reproduce:
We are upgrading to the latest firebase to take advantage of the firebase messaging in the app but 
 the app crashes when trying to register push notifications. Is SalesforceMobileSDK and new firebase are not compatible? If yes, could you please let me know when latest firebase will be available in Salesforce?
6. Actual behavior:
Get crashes for trying to register push notifications. Not sure if it’s some library incompatibilities
7. Expected Behavior:
No crashes. Receives push notifs
8. Error Log:
```
Process: com.transurban.linktgo.staging, PID: 21709
java.lang.NoClassDefFoundError: Failed resolution of: Lcom/salesforce/android/connectedapp/internal/PushNotificationRefreshService;
at com.salesforce.android.connectedapp.SalesforceConnectedApp.create(SalesforceConnectedApp.java:68)
at au.com.transurban.mobiletoll.presentation.presenters.components.UserSupportConfigComponent.registerForPushNotifications(UserSupportConfigComponent.kt:162)
at au.com.transurban.mobiletoll.presentation.presenters.components.UserSupportComponent$authenticate$1.authenticatedRestClient(UserSupportComponent.kt:210)
at com.salesforce.androidsdk.rest.ClientManager$AccMgrCallback.run(ClientManager.java:457)
at android.accounts.AccountManager$18.run(AccountManager.java:2179)
at android.os.Handler.handleCallback(Handler.java:790)
at android.os.Handler.dispatchMessage(Handler.java:99)
at android.os.Looper.loop(Looper.java:164)
at android.app.ActivityThread.main(ActivityThread.java:6494)
at java.lang.reflect.Method.invoke(Native Method)
at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:438)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:807)
Caused by: java.lang.ClassNotFoundException: com.salesforce.android.connectedapp.internal.PushNotificationRefreshService
at java.lang.VMClassLoader.findLoadedClass(Native Method)
at java.lang.ClassLoader.findLoadedClass(ClassLoader.java:738)
at java.lang.ClassLoader.loadClass(ClassLoader.java:363)
at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
at com.salesforce.android.connectedapp.SalesforceConnectedApp.create(SalesforceConnectedApp.java:68) 
at au.com.transurban.mobiletoll.presentation.presenters.components.UserSupportConfigComponent.registerForPushNotifications(UserSupportConfigComponent.kt:162) 
at au.com.transurban.mobiletoll.presentation.presenters.components.UserSupportComponent$authenticate$1.authenticatedRestClient(UserSupportComponent.kt:210) 
at com.salesforce.androidsdk.rest.ClientManager$AccMgrCallback.run(ClientManager.java:457) 
at android.accounts.AccountManager$18.run(AccountManager.java:2179) 
at android.os.Handler.handleCallback(Handler.java:790) 
at android.os.Handler.dispatchMessage(Handler.java:99) 
at android.os.Looper.loop(Looper.java:164) 
at android.app.ActivityThread.main(ActivityThread.java:6494) 
at java.lang.reflect.Method.invoke(Native Method) 
at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:438) 
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:807) 
Caused by: java.lang.NoClassDefFoundError: Failed resolution of: Lcom/google/firebase/iid/FirebaseInstanceIdService;
at com.salesforce.android.connectedapp.SalesforceConnectedApp.create(SalesforceConnectedApp.java:68) 
at au.com.transurban.mobiletoll.presentation.presenters.components.UserSupportConfigComponent.registerForPushNotifications(UserSupportConfigComponent.kt:162) 
at au.com.transurban.mobiletoll.presentation.presenters.components.UserSupportComponent$authenticate$1.authenticatedRestClient(UserSupportComponent.kt:210) 
at com.salesforce.androidsdk.rest.ClientManager$AccMgrCallback.run(ClientManager.java:457) 
at android.accounts.AccountManager$18.run(AccountManager.java:2179) 
at android.os.Handler.handleCallback(Handler.java:790) 
at android.os.Handler.dispatchMessage(Handler.java:99) 
at android.os.Looper.loop(Looper.java:164) 
at android.app.ActivityThread.main(ActivityThread.java:6494) 
at java.lang.reflect.Method.invoke(Native Method) 
at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:438) 
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:807) 
Caused by: java.lang.ClassNotFoundException: Didn't find class "com.google.firebase.iid.FirebaseInstanceIdService" on path: DexPathList[[zip file "/data/app/com.transurban.linktgo.staging-JAu8ggnucBDVcdcUe1YO2A==/base.apk"],nativeLibraryDirectories=[/data/app/com.transurban.linktgo.staging-JAu8ggnucBDVcdcUe1YO2A==/lib/arm64, /data/app/com.transurban.linktgo.staging-JAu8ggnucBDVcdcUe1YO2A==/base.apk!/lib/arm64-v8a, /system/lib64, /vendor/lib64]]
at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:125)
at java.lang.ClassLoader.loadClass(ClassLoader.java:379)
at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
at com.salesforce.android.connectedapp.SalesforceConnectedApp.create(SalesforceConnectedApp.java:68) 
at au.com.transurban.mobiletoll.presentation.presenters.components.UserSupportConfigComponent.registerForPushNotifications(UserSupportConfigComponent.kt:162) 
at au.com.transurban.mobiletoll.presentation.presenters.components.UserSupportComponent$authenticate$1.authenticatedRestClient(UserSupportComponent.kt:210) 
at com.salesforce.androidsdk.rest.ClientManager$AccMgrCallback.run(ClientManager.java:457) 
at android.accounts.AccountManager$18.run(AccountManager.java:2179) 
at android.os.Handler.handleCallback(Handler.java:790) 
at android.os.Handler.dispatchMessage(Handler.java:99) 
at android.os.Looper.loop(Looper.java:164) 
at android.app.ActivityThread.main(ActivityThread.java:6494) 
at java.lang.reflect.Method.invoke(Native Method) 
at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:438) 
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:807)
```

**Comment by geekandt** [comment]
Update:
Tried the previous version of com.google.firebase:firebase-messaging:17.3.0 and 19.0.1
Still crashed

**Comment by bhariharan** [comment]
Did you mean `Mobile SDK 8.1.0`? We haven't published a versionn `8.0.1`. Also, are you explicitly including `Firebase` in your app? You should be able to use it directly through `Mobile SDK` - it's already a dependency. Declaring it explicitly in your app could cause conflicts.

**Comment by geekandt** [comment]
Sorry correction, we are using Mobile SDK 7.0.0 currently.

We cannot use core MobileSDK 8.1 because our app is still using lollipop. I’ve tried migrating to 7.3.0 but the issue above with compatibility happened.

So just to clarify:

Service SDK has latest version 8.0.1
SalesforceMobileSDK has latest 8.1.0 which we cannot use because it forces API 23 Marshmallow and our min is API 21 so we are using 7.0.0 instead.

The 2 above are compatible because both using Firebase 17.x.x

Now SalesforceSDK 7.3.0 which I wanted to use is using later Firebase SDK which makes it incompatible with ServiceSDK 8.0.1.

**Comment by bhariharan** [comment]
@geekandt `Mobile SDK 7.3.0` supports `Firebase 19.0.1` (see [here](https://github.com/forcedotcom/SalesforceMobileSDK-Android/blob/v7.3.0/libs/SalesforceSDK/build.gradle#L19)). You should be able to use this out of the box, without having to include your own version of `Firebase`. It looks like you're running into issues with `ServiceSDK` integration. You will need to open a case with `Salesforce` to discuss that and follow up with the `ServiceSDK` team to support that version of `Firebase`. I'm closing this issue, since this forum is reserved for bugs/issues with `Mobile SDK` code.

**Comment by geekandt** [comment]
@bhariharan hi, is there a way to remove this issue ? I accidentally added the name of the app and removed it. However, I think its still keeps the history and can still be searched. Can you please remove this issue? Thanks so much
