### ISSUE TITLE
App crashed once

### ISSUE THREAD

**Issue by murilodag** [forcedotcom/SalesforceMobileSDK-Android#2078]
Please fill out the following details:

1. Version of Mobile SDK Used: 8.1.0
2. Issue found in Native App or Hybrid App: native
3. OS Version: 8.1.0
4. Device: LGE Nexos 5X
5. Steps to reproduce: Dev team was not able to reproduce
6. Actual behavior: App crashed only once for this specific user
7. Expected Behavior: App should not crash
8. Error Log: 
```
Fatal Exception: java.lang.NullPointerException: uriString
       at android.net.Uri$StringUri.<init>(Uri.java:476)
       at android.net.Uri$StringUri.<init>(Uri.java)
       at android.net.Uri.parse(Uri.java:438)
       at com.salesforce.androidsdk.auth.idp.SPRequestHandler.launchIDPApp(SPRequestHandler.java:91)
       at com.salesforce.androidsdk.ui.LoginActivity.onIDPLoginClick(LoginActivity.java:365)
       at com.salesforce.androidsdk.ui.LoginActivity.onNewIntent(LoginActivity.java:182)
       at android.app.Activity.performNewIntent(Activity.java:7021)
       at android.app.Instrumentation.callActivityOnNewIntent(Instrumentation.java:1309)
       at android.app.Instrumentation.callActivityOnNewIntent(Instrumentation.java:1321)
       at android.app.ActivityThread.deliverNewIntents(ActivityThread.java:2932)
       at android.app.ActivityThread.performNewIntents(ActivityThread.java:2948)
       at android.app.ActivityThread.handleNewIntent(ActivityThread.java:2964)
       at android.app.ActivityThread.-wrap14(ActivityThread.java)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1667)
       at android.os.Handler.dispatchMessage(Handler.java:106)
       at android.os.Looper.loop(Looper.java:164)
       at android.app.ActivityThread.main(ActivityThread.java:6494)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:438)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:807)
```
![image](https://user-images.githubusercontent.com/2996649/84059529-c42ab100-a988-11ea-8b69-e9cbb83bdbd1.png)

**Comment by bhariharan** [comment]
Thanks for reporting. This can only occur if the `Login with IDP` button within the login screen is clicked with an incorrect/incomplete IDP configuration, and that button's visibility is set to `GONE` by default.

**Comment by murilodag** [comment]
Hello @bhariharan, the app does not have IDP enabled.
Do you know how the user could've accessed it?
