### ISSUE TITLE
Crash on com.salesforce.androidsdk.rest.ClientManager$AccountInfoNotFoundException: No user account found

### ISSUE THREAD

**Issue by irisariana05** [forcedotcom/SalesforceMobileSDK-Android#2079]
Please fill out the following details:

1. Version of Mobile SDK Used: 7.3.0
2. Issue found in Native App or Hybrid App: React native
- React Native 0.60.5
- React 16.8.6
- react-native-force "git+https://github.com/forcedotcom/SalesforceMobileSDK-ReactNative.git#v7.3.0"
3. OS Version: android 9
4. Device: LG (Model LM-G820QM5)
5. Steps to reproduce:
In my app I have a Logout button, when the user clicks it I just call the oauth.logout(); method from react-native-force library
6. Actual behavior: After the user clicks the logout button the app crashes
7. Expected Behavior: If the user logouts, the SDK have to clean the user session and the app redirects to login 
8. Error Log:
```
2020-06-10 15:57:06.272 11180-11180/com.xx.mobtok I/ClientManager: No user account found
    com.salesforce.androidsdk.rest.ClientManager$AccountInfoNotFoundException: No user account found
        at com.salesforce.androidsdk.rest.ClientManager.peekRestClient(ClientManager.java:155)
        at com.salesforce.androidsdk.rest.ClientManager.peekRestClient(ClientManager.java:139)
        at com.salesforce.androidsdk.reactnative.ui.SalesforceReactActivity.onResume(SalesforceReactActivity.java:104)
        at com.salesforce.androidsdk.ui.SalesforceActivityDelegate.onResume(SalesforceActivityDelegate.java:103)
        at com.salesforce.androidsdk.reactnative.ui.SalesforceReactActivity.onResume(SalesforceReactActivity.java:97)
        at com.oktana.mobtok.MainActivity.onResume(MainActivity.java:79)
        at android.app.Instrumentation.callActivityOnResume(Instrumentation.java:1413)
        at android.app.Activity.performResume(Activity.java:7307)
        at android.app.ActivityThread.performResumeActivity(ActivityThread.java:3850)
        at android.app.ActivityThread.handleResumeActivity(ActivityThread.java:3890)
        at android.app.servertransaction.ResumeActivityItem.execute(ResumeActivityItem.java:51)
        at android.app.servertransaction.TransactionExecutor.executeLifecycleState(TransactionExecutor.java:145)
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:70)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1847)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loop(Looper.java:205)
        at android.app.ActivityThread.main(ActivityThread.java:6892)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:860)
2020-06-10 15:57:06.273 11180-11180/com.xx.mobtok I/SFReactActivity: onResumeNotLoggedIn - should not authenticate
2020-06-10 15:57:06.312 11180-11180/com.xx.mobtok I/Timeline: Timeline: Activity_idle id: android.os.BinderProxy@590b1d8 time:663241
```

I am not sure if this setting could affect this behavior, but in my MainActivity which extends SalesforceReactActivity, I have the shouldAuthenticate return false; 

Please let me know what could be the problem or if I need to check any configuration in my android or react native project. 

Thank you!

**Comment by bhariharan** [comment]
@irisariana05 Could you re-generate your project with the latest version, i.e. `Mobile SDK 8.1.0`, and try again? Looking at your stack trace and following the code path, I'm not sure if this could happen on the latest code base. I couldn't reproduce this in our sample app either. Feel free to reopen this issue if it still exists in the latest version of `Mobile SDK`.

**Comment by davidjbrossard** [comment]
@bhariharan I got the same stack trace while following the [hybrid mobile trail](https://trailhead.salesforce.com/en/content/learn/modules/mobile_sdk_hybrid/mobilesdk_hybrid_getting_started?trail_id=mobile_sdk_intro):

`I/ClientManager: No user account found
    com.salesforce.androidsdk.rest.ClientManager$AccountInfoNotFoundException: No user account found
        at com.salesforce.androidsdk.rest.ClientManager.peekRestClient(ClientManager.java:155)
        at com.salesforce.androidsdk.rest.ClientManager.peekRestClient(ClientManager.java:139)
        at com.salesforce.androidsdk.phonegap.ui.SalesforceDroidGapActivity.onResume(SalesforceDroidGapActivity.java:155)
        at com.salesforce.androidsdk.ui.SalesforceActivityDelegate.onResume(SalesforceActivityDelegate.java:103)
        at com.salesforce.androidsdk.phonegap.ui.SalesforceDroidGapActivity.onResume(SalesforceDroidGapActivity.java:145)
        at android.app.Instrumentation.callActivityOnResume(Instrumentation.java:1456)
        at android.app.Activity.performResume(Activity.java:8124)
        at android.app.ActivityThread.performResumeActivity(ActivityThread.java:4343)
        at android.app.ActivityThread.handleResumeActivity(ActivityThread.java:4385)
        at android.app.servertransaction.ResumeActivityItem.execute(ResumeActivityItem.java:52)
        at android.app.servertransaction.TransactionExecutor.executeLifecycleState(TransactionExecutor.java:176)
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:97)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2044)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loop(Looper.java:223)
        at android.app.ActivityThread.main(ActivityThread.java:7476)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:549)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:939)
W/BootConfig: unauthenticatedStartPage set for local app, but it will never be used.`

**Comment by bhariharan** [comment]
@davidjbrossard That just means you haven't authenticated yet, but are trying to access an authenticated resource.

**Comment by davidjbrossard** [comment]
That makes sense now because my connected app info was not up to date yet.
Thanks!
