### ISSUE TITLE
Unable to resume activity : AccountInfoNotFoundException: authtoken

### ISSUE THREAD

**Issue by akshayajeevan** [forcedotcom/SalesforceMobileSDK-Android#2099]
Please fill out the following details:

1. Version of Mobile SDK Used: 8.0.0
2. Issue found in Native App or Hybrid App: Hybrid
3. OS Version: Android 9
4. Device: Samsung Galaxy Tab Active2
5. Steps to reproduce: Unknown (getting this error on crash report)
6. Actual behavior: App crash
7. Expected Behavior: App should not crash
8. Error Log:
```
Fatal Exception: java.lang.RuntimeException: Unable to resume activity {com.xyz/com.salesforce.androidsdk.phonegap.ui.SalesforceDroidGapActivity}: com.salesforce.androidsdk.rest.ClientManager$AccountInfoNotFoundException: authtoken
       at android.app.ActivityThread.performResumeActivity(ActivityThread.java:4041)
       at android.app.ActivityThread.handleResumeActivity(ActivityThread.java:4073)
       at android.app.servertransaction.ResumeActivityItem.execute(ResumeActivityItem.java:51)
       at android.app.servertransaction.TransactionExecutor.executeLifecycleState(TransactionExecutor.java:145)
       at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:70)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1972)
       at android.os.Handler.dispatchMessage(Handler.java:106)
       at android.os.Looper.loop(Looper.java:214)
       at android.app.ActivityThread.main(ActivityThread.java:7179)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:494)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:975)
```
Can you please let me know any use-case, when account / authtoken will be null which throws this error.

Thanks!

**Comment by bhariharan** [comment]
This exception is thrown when the account has been removed, either due to token revocation or for other reasons. In this case, it's possible that the stored account might have been corrupted and `authToken` is `null` as a side-effect. Feel free to reopen this if you can reproduce it in any of our sample apps with the latest version of `Mobile SDK`.
