### ISSUE TITLE
Push notification not working, Salesfoces _SDK  - Firebase project ID is required to communicate with Firebase server

### ISSUE THREAD

**Issue by VSoull** [forcedotcom/SalesforceMobileSDK-Android#2110]
Please fill out the following details:

1. Version of Mobile SDK Used: 
 SalesforceMobileSDK-Android v 8.1

2. Issue found in :
  React Native

3. OS Version:
Mac OX - Catalina 10.15

4. Device:
 Nokia 8.1 Android version 10

5. Steps to reproduce:
  Login in application.
  After login, the firebase init  fails and the user it s not register in Salesforce for push notification.
  Connection between salesforce and firebase fails, direct connection between application and firebase  it s working.

6. Actual behavior:
    User can t be seen as register for push notification.

7. Expected Behavior:
   User should be seen as register for push notifications, user should receive push notification from salesforce

8. Error Log:

    We get this error: 
```
  java.lang.IllegalStateException: FirebaseApp with name'Project Name xxxx ' doesn't exist. Available app names: [DEFAULT]
        at com.google.firebase.FirebaseApp.getInstance(com.google.firebase:firebase-common@@19.3.0:218)
        at com.salesforce.androidsdk.push.PushMessaging.initializeFirebaseIfNeeded(PushMessaging.java:170)
        at com.salesforce.androidsdk.push.PushMessaging.register(PushMessaging.java:102)
        at com.salesforce.androidsdk.ui.OAuthWebviewHelper.addAccount(OAuthWebviewHelper.java:673)
        at com.salesforce.androidsdk.ui.OAuthWebviewHelper$BaseFinishAuthFlowTask.onPostExecute(OAuthWebviewHelper.java:583)
        at com.salesforce.androidsdk.ui.OAuthWebviewHelper$BaseFinishAuthFlowTask.onPostExecute(OAuthWebviewHelper.java:513)
        at android.os.AsyncTask.finish(AsyncTask.java:755)
        at android.os.AsyncTask.access$900(AsyncTask.java:192)
        at android.os.AsyncTask$InternalHandler.handleMessage(AsyncTask.java:772)
        at android.os.Handler.dispatchMessage(Handler.java:107)
        at android.os.Looper.loop(Looper.java:214)
        at android.app.ActivityThread.main(ActivityThread.java:7397)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:935)
2020-08-09 18:37:28.462 25452-25768/xxxxxxxxxxxxxxxx E/RegIntentService: Error during FCM registration
    java.lang.IllegalArgumentException: Please set your project ID. A valid Firebase project ID is required to communicate with Firebase server APIs: It identifies your project with Google.
        at com.google.android.gms.common.internal.Preconditions.checkNotEmpty(Unknown Source:8)
        at com.google.firebase.iid.FirebaseInstanceId.checkRequiredFirebaseOptions(com.google.firebase:firebase-iid@@20.2.3:52)
        at com.google.firebase.iid.FirebaseInstanceId.getInstance(com.google.firebase:firebase-iid@@20.2.3:2)
        at com.salesforce.androidsdk.push.SFDCRegistrationIntentService.onHandleWork(SFDCRegistrationIntentService.java:62)
        at androidx.core.app.JobIntentService$CommandProcessor.doInBackground(JobIntentService.java:392)
        at androidx.core.app.JobIntentService$CommandProcessor.doInBackground(JobIntentService.java:383)
        at android.os.AsyncTask$3.call(AsyncTask.java:378)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
        at java.lang.Thread.run(Thread.java:919)3. OS Version:
```

the connection between application and firebase it s working and we get push notifications in app, the google-services.json it's valid and the project_id it s valid.
    
We found that in 

package com.salesforce.androidsdk.push; 

  if we change in method 

public static void initializeFirebaseIfNeeded(Context context)

the FirebaseOptions builder from : 

        final FirebaseOptions firebaseOptions = new FirebaseOptions.Builder()
                 .setGcmSenderId(pushClientId)
                 .setApplicationId(context.getPackageName()).build();

to 
  
               final FirebaseOptions firebaseOptions = new FirebaseOptions.Builder()
                 .setGcmSenderId(pushClientId)
               .setProjectId("xxxxxx")
               .setApiKey("xxxxxxxxxx")
              .setApplicationId("xxxxxxxx").build();

The initialization of Firebase takes place and the user it s registered to salesforce and we get push notification.

**Comment by bhariharan** [comment]
@VSoull Are you using a newer version of `Firebase`? As long as you're using the version that comes with the SDK, i.e. `'com.google.firebase:firebase-messaging:20.1.0'`, push notifications should work fine. I have verified this with our internal apps. We are aware that fields such as `projectId` are required for newer versions, and we will be adding those in a future version. For now, please ensure that you're using `'com.google.firebase:firebase-messaging:20.1.0'`.

**Comment by VSoull** [comment]
@bhariharan  with 'com.google.firebase:firebase-messaging:20.1.0' we get the same error, can you provide me a link to your documentation page or an example? i don t find any info regarding android push notification firebase versions sdk etc on your salesforce docs, using react-native-firebase version 5 we get other issues on iOS and it s already deprecated:
This is what we use on react native now: 
 "@react-native-firebase/app": "^8.3.0",
    "@react-native-firebase/messaging": "^7.6.1",

and for build.gradle:  
   
    implementation 'com.google.firebase:firebase-analytics:17.2.2'
    implementation 'com.google.firebase:firebase-messaging:20.1.0'

Thank you

**Comment by bhariharan** [comment]
@VSoull I'm guessing `ReactNative` pulls in a newer version behind the scenes that'e breaking this. For now, please use Gradle excludes to exclude the version of `Firebase` that's coming from `ReactNative` and use this version instead. We will upgrade the version of `Firebase` in a future release.

**Comment by romanravkov** [comment]
@VSoull Could you tell me how did you fix your issue? I got the same
