### ISSUE TITLE
Getting Exception after Resync React Native  -- Failed to save sync state

### ISSUE THREAD

**Issue by dileepkantapop** [forcedotcom/SalesforceMobileSDK-Android#2160]
My use-case first i will SyncDown data. then after changing in local, i will SyncUp and Preform ReSync operation after removing local data. So at the time of ReSync throwing below exception in Android
`
2021-02-05 23:30:20.633 9190-9561/com.packageName.app E/AndroidRuntime: FATAL EXCEPTION: pool-13-thread-1
    Process: com.packageName.app, PID: 9190
    com.salesforce.androidsdk.mobilesync.manager.SyncManager$MobileSyncException: Failed to save sync state
        at com.salesforce.androidsdk.mobilesync.util.SyncState.save(SyncState.java:375)
        at com.salesforce.androidsdk.mobilesync.manager.SyncTask.updateSync(SyncTask.java:141)
        at com.salesforce.androidsdk.mobilesync.manager.SyncTask.run(SyncTask.java:96)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
        at java.lang.Thread.run(Thread.java:764)
`

Can anyone please help me how to fix this?

React native: 0.63.2
SalesforceMobileSDk: 8.3.0
Android Studio: 4.1.1

**Comment by wmathurin** [comment]
To see mobile sync in action, a good starting point is to use the MobileSyncExplorer template by doing 
```shell
forcereact createwithtemplate --templaterepouri=MobileSyncExplorerReactNative
```
Is it what you did?

**Comment by dileepkantapop** [comment]
Yes i did that. 

In iOS I won't see any issue with Sync and ReSync.

**Comment by wmathurin** [comment]
How did you remove the local data?
From the exception, it looks like it could not find the sync state entry (see https://github.com/forcedotcom/SalesforceMobileSDK-Android/blob/dev/libs/MobileSync/src/com/salesforce/androidsdk/mobilesync/util/SyncState.java#L373).

**Comment by wmathurin** [comment]
Closing since further details were never provided.
