### ISSUE TITLE
Fatal Exception: net.sqlcipher.database.SQLiteException: error code 8: attempt to write a readonly database when auto logout

### ISSUE THREAD

**Issue by as8703** [forcedotcom/SalesforceMobileSDK-Android#2163]
1. Version of Mobile SDK Used: 8.2.0
2. Issue found in Native App or Hybrid App: Native
3. OS Version: 8.1.0
4. Device: TC 25
5. Steps to reproduce: Automatically logged out when the token expires.
6. Actual behavior: Crashing 
7. Expected Behavior: Should not crash
8. Error Log:
```
Fatal Exception: net.sqlcipher.database.SQLiteException: error code 8: attempt to write a readonly database
       at net.sqlcipher.database.SQLiteStatement.native_execute(SQLiteStatement.java)
       at net.sqlcipher.database.SQLiteStatement.execute(SQLiteStatement.java:61)
       at net.sqlcipher.database.SQLiteDatabase.updateWithOnConflict(SQLiteDatabase.java:2401)
       at net.sqlcipher.database.SQLiteDatabase.update(SQLiteDatabase.java:2328)
       at com.salesforce.androidsdk.smartstore.store.DBHelper.update(DBHelper.java:412)
       at com.salesforce.androidsdk.smartstore.store.SmartStore.update(SmartStore.java:1256)
       at com.salesforce.androidsdk.smartstore.store.SmartStore.update(SmartStore.java:1214)
       at com.salesforce.androidsdk.mobilesync.util.SyncState.save(SyncState.java:373)
       at com.salesforce.androidsdk.mobilesync.manager.SyncTask.updateSync(SyncTask.java:138)
       at com.salesforce.androidsdk.mobilesync.manager.SyncTask.run(SyncTask.java:95)
       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1162)
       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636)
       at java.lang.Thread.run(Thread.java:764)
```

**Comment by bhariharan** [comment]
We have fixed a few bugs around this in recent releases. Please try our latest release, `9.0.0`.

**Comment by as8703** [comment]
Looks like it is fixed.
