### ISSUE TITLE
PushMessaging.java line 130

### ISSUE THREAD

**Issue by johnjeremih** [forcedotcom/SalesforceMobileSDK-Android#2171]
Please fill out the following details:

I'm  geting this errror

OS Version:
8.1.0
Device:
 Galaxy J7 Prime

Error Log:
```
Fatal Exception: java.lang.IllegalArgumentException: Please set your project ID. A valid Firebase project ID is required to communicate with Firebase server APIs: It identifies your project with Google.
       at com.google.android.gms.common.internal.Preconditions.checkNotEmpty(:8)
       at com.google.firebase.iid.FirebaseInstanceId.checkRequiredFirebaseOptions(com.google.firebase:firebase-iid@@21.0.1:2)
       at com.google.firebase.iid.FirebaseInstanceId.getInstance(com.google.firebase:firebase-iid@@21.0.1:2)
       at com.salesforce.androidsdk.push.PushMessaging.unregister(PushMessaging.java:130)
       at com.salesforce.androidsdk.app.SalesforceSDKManager.unregisterPush(SalesforceSDKManager.java:823)
       at com.salesforce.androidsdk.app.SalesforceSDKManager.logout(SalesforceSDKManager.java:901)
       at com.salesforce.androidsdk.app.SalesforceSDKManager.logout(SalesforceSDKManager.java:868)
```

**Comment by bhariharan** [comment]
We've fixed this in a recent version. Please upgrade to the latest version, `9.0.0`.

**Comment by johnjeremih** [comment]
Thank, I will check

**Comment by llyrProximity** [comment]
Hey, I'm quite new to Android. I'm also getting this error. I updated to version 9.0.0 this morning.

**Comment by johnjeremih** [comment]
I still have the same problem @bbirman

**Comment by johnjeremih** [comment]
I also get this error when login out
`W/PushMessaging: Package info could not be retrieved
    android.content.res.Resources$NotFoundException: String resource ID #0x0
        at android.content.res.Resources.getText(Resources.java:367)
        at android.content.res.Resources.getString(Resources.java:460)
        at android.content.Context.getString(Context.java:639)
        at com.salesforce.androidsdk.push.PushMessaging.getAppNameForFirebase(PushMessaging.java:180)
        at com.salesforce.androidsdk.push.PushMessaging.initializeFirebaseIfNeeded(PushMessaging.java:153)
        at com.salesforce.androidsdk.push.PushMessaging.unregister(PushMessaging.java:128)
        at com.salesforce.androidsdk.app.SalesforceSDKManager.unregisterPush(SalesforceSDKManager.java:833)
        at com.salesforce.androidsdk.app.SalesforceSDKManager.logout(SalesforceSDKManager.java:911)
        at com.salesforce.androidsdk.app.SalesforceSDKManager.logout(SalesforceSDKManager.java:878)
`

**Comment by llyrProximity** [comment]
For me, the way round it was to use a different version messaging from fire base in the gradle file

implementation 'com.google.firebase:firebase-messaging:20.1.0'
The SDK does't currently support the newer version.

**Comment by johnjeremih** [comment]
@llyrProximity  the last version that I have is 21.0.1.

**Comment by llyrProximity** [comment]
Change it to implementation 'com.google.firebase:firebase-messaging:20.1.0', worked for me

**Comment by bhariharan** [comment]
Yes, we don't support newer versions of `Firebase` at this time, you'll need to use `20.1.0`.
