### ISSUE TITLE
Transmitter.kt line 157

### ISSUE THREAD

**Issue by johnjeremih** [forcedotcom/SalesforceMobileSDK-Android#2172]
I have two errors
![image](https://user-images.githubusercontent.com/4177453/110031781-53d97200-7d05-11eb-9787-e00fc44d0ef5.png)
```
Fatal Exception: java.lang.RuntimeException: An error occurred while executing doInBackground()
       at android.os.AsyncTask$4.done(AsyncTask.java:399)
       at java.util.concurrent.FutureTask.finishCompletion(FutureTask.java:383)
       at java.util.concurrent.FutureTask.setException(FutureTask.java:252)
       at java.util.concurrent.FutureTask.run(FutureTask.java:271)
       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
       at java.lang.Thread.run(Thread.java:919)

Caused by java.lang.IllegalStateException: cannot make a new request because the previous response is still open: please call response.close()
       at okhttp3.internal.connection.Transmitter.newExchange$okhttp(Transmitter.kt:157)
       at okhttp3.internal.connection.ConnectInterceptor.intercept(ConnectInterceptor.kt:35)
       at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:112)
       at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:87)
       at okhttp3.internal.cache.CacheInterceptor.intercept(CacheInterceptor.kt:82)
       at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:112)
       at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:87)
       at okhttp3.internal.http.BridgeInterceptor.intercept(BridgeInterceptor.kt:84)
       at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:112)
       at okhttp3.internal.http.RetryAndFollowUpInterceptor.intercept(RetryAndFollowUpInterceptor.kt:71)
       at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:112)
       at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:87)
       at com.salesforce.androidsdk.rest.RestClient$OAuthRefreshInterceptor.intercept(RestClient.java:676)
       at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:112)
       at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:87)
       at okhttp3.RealCall.getResponseWithInterceptorChain(RealCall.kt:194)
       at okhttp3.RealCall.execute(RealCall.kt:67)
       at com.google.firebase.perf.network.FirebasePerfOkHttpClient.execute(com.google.firebase:firebase-perf@@19.0.5:5)
       at com.salesforce.androidsdk.rest.RestClient.sendSync(RestClient.java:369)
       at com.salesforce.androidsdk.analytics.AILTNPublisher.publishLogLines(AILTNPublisher.java:135)
       at com.salesforce.androidsdk.analytics.AILTNPublisher.publish(AILTNPublisher.java:98)
       at com.salesforce.androidsdk.analytics.SalesforceAnalyticsManager.publishEvents(SalesforceAnalyticsManager.java:315)
       at com.salesforce.androidsdk.analytics.SalesforceAnalyticsManager.publishAllEvents(SalesforceAnalyticsManager.java:274)
       at com.salesforce.androidsdk.analytics.AnalyticsPublisherService.handleActionPublish(AnalyticsPublisherService.java:75)
       at com.salesforce.androidsdk.analytics.AnalyticsPublisherService.onHandleWork(AnalyticsPublisherService.java:63)
       at androidx.core.app.JobIntentService$CommandProcessor.doInBackground(JobIntentService.java:392)
       at androidx.core.app.JobIntentService$CommandProcessor.doInBackground(JobIntentService.java:383)
       at android.os.AsyncTask$3.call(AsyncTask.java:378)
       at java.util.concurrent.FutureTask.run(FutureTask.java:266)
       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
       at java.lang.Thread.run(Thread.java:919)
```

**Comment by wmathurin** [comment]
We need more information:
- mobile sdk version
- type of app (native, hybrid, react native)
- repro steps

**Comment by johnjeremih** [comment]
> We need more information:
> 
> * mobile sdk version
> * type of app (native, hybrid, react native)
> * repro steps

Mobile sdk - version is 29
type of app - native
repo - "com.salesforce.mobilesdk:SalesforceSDK:7.2.3"

**Comment by wmathurin** [comment]
Also we didn't have a 7.2.3 release. We went from 7.2.0 to 7.3.0.

**Comment by wmathurin** [comment]
Closing issue - waiting to hear back with details about SDK.
