### ISSUE TITLE
Crash when attempts to login from specific devices

### ISSUE THREAD

**Issue by rehabMohamed** [forcedotcom/SalesforceMobileSDK-Android#2173]
Please fill out the following details:

1. Version of Mobile SDK Used: 8.3.0
2. Issue found in Native App or Hybrid App: Native
3. OS Version: 6.0
4. Device: (Lenovo TAB3 7) and (HUAWEI P9 lite)
5. Steps to reproduce: trying to open the login screen
6. Actual behavior: app crashes when opening the login screen
7. Expected Behavior: login screen shows without crash
8. Error Log:
Fatal Exception: java.lang.RuntimeException: Unable to start activity ComponentInfo{org.mahgoub.app/com.salesforce.androidsdk.ui.LoginActivity}: android.content.res.Resources$NotFoundException: Resource ID #0x7f0e0000
       at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2583)
       at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2665)
       at android.app.ActivityThread.-wrap11(ActivityThread.java)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1499)
       at android.os.Handler.dispatchMessage(Handler.java:111)
       at android.os.Looper.loop(Looper.java:207)
       at android.app.ActivityThread.main(ActivityThread.java:5765)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:789)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:679)
       
Caused by android.content.res.Resources$NotFoundException: Resource ID #0x7f0e0000
       at android.content.res.Resources.getValue(Resources.java:1544)
       at android.content.res.Resources.getDrawable(Resources.java:918)
       at android.content.Context.getDrawable(Context.java:463)
       at com.android.internal.widget.ToolbarWidgetWrapper.setIcon(ToolbarWidgetWrapper.java:322)
       at com.android.internal.widget.ActionBarOverlayLayout.setIcon(ActionBarOverlayLayout.java:737)
       at com.android.internal.policy.PhoneWindow.setDefaultIcon(PhoneWindow.java:1708)
       at android.app.Activity.initWindowDecorActionBar(Activity.java:2177)
       at android.app.Activity.setContentView(Activity.java:2192)
       at com.salesforce.androidsdk.ui.LoginActivity.onCreate(LoginActivity.java:120)
       at android.app.Activity.performCreate(Activity.java:6309)
       at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1113)
       at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2530)
       at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2665)
       at android.app.ActivityThread.-wrap11(ActivityThread.java)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1499)
       at android.os.Handler.dispatchMessage(Handler.java:111)
       at android.os.Looper.loop(Looper.java:207)
       at android.app.ActivityThread.main(ActivityThread.java:5765)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:789)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:679)

**Comment by rehabMohamed** [comment]
it happens with all devices running Android 6.0. This is the full stack trace
03-11 17:03:40.623 4567-4567/org.mahgoub.app E/KeyStoreWrapper: Could not generate key pair
    java.security.ProviderException: Failed to generate self-signed certificate
        at android.security.keystore.AndroidKeyStoreKeyPairGeneratorSpi.generateKeyPair(AndroidKeyStoreKeyPairGeneratorSpi.java:504)
        at java.security.KeyPairGenerator$KeyPairGeneratorImpl.generateKeyPair(KeyPairGenerator.java:276)
        at com.salesforce.androidsdk.security.KeyStoreWrapper.createKeysIfNecessary(KeyStoreWrapper.java:239)
        at com.salesforce.androidsdk.security.KeyStoreWrapper.getPublicKey(KeyStoreWrapper.java:183)
        at com.salesforce.androidsdk.security.KeyStoreWrapper.getRSAPublicKey(KeyStoreWrapper.java:119)
        at com.salesforce.androidsdk.security.KeyStoreWrapper.getRSAPublicKey(KeyStoreWrapper.java:88)
        at com.salesforce.androidsdk.security.SalesforceKeyGenerator.generateUniqueId(SalesforceKeyGenerator.java:239)
        at com.salesforce.androidsdk.security.SalesforceKeyGenerator.getUniqueId(SalesforceKeyGenerator.java:90)
        at com.salesforce.androidsdk.security.SalesforceKeyGenerator.getUniqueId(SalesforceKeyGenerator.java:79)
        at com.salesforce.androidsdk.security.PasscodeManager.<init>(PasscodeManager.java:120)
        at com.salesforce.androidsdk.app.SalesforceSDKManager.getPasscodeManager(SalesforceSDKManager.java:522)
        at com.salesforce.androidsdk.ui.SalesforceActivityDelegate.onCreate(SalesforceActivityDelegate.java:60)
        at org.mahgoub.app.base.SalesForceBaseActivity.onCreate(SalesForceBaseActivity.kt:16)
        at org.mahgoub.app.login.LoginDoneActivity.onCreate(LoginDoneActivity.kt:23)
        at android.app.Activity.performCreate(Activity.java:6237)
        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1107)
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2369)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2476)
        at android.app.ActivityThread.-wrap11(ActivityThread.java)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1344)
        at android.os.Handler.dispatchMessage(Handler.java:102)
        at android.os.Looper.loop(Looper.java:148)
        at android.app.ActivityThread.main(ActivityThread.java:5417)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)
     Caused by: java.lang.IllegalArgumentException: invalid date string: Unparseable date: "g``a`a``````GMT+00:00" (at offset 0)
        at com.android.org.bouncycastle.asn1.ASN1UTCTime.<init>(ASN1UTCTime.java:115)
        at com.android.org.bouncycastle.asn1.DERUTCTime.<init>(DERUTCTime.java:23)
        at com.android.org.bouncycastle.asn1.x509.Time.<init>(Time.java:67)
        at android.security.keystore.AndroidKeyStoreKeyPairGeneratorSpi.generateSelfSignedCertificateWithFakeSignature(AndroidKeyStoreKeyPairGeneratorSpi.java:618)
        at android.security.keystore.AndroidKeyStoreKeyPairGeneratorSpi.generateSelfSignedCertificate(AndroidKeyStoreKeyPairGeneratorSpi.java:553)
        at android.security.keystore.AndroidKeyStoreKeyPairGeneratorSpi.generateKeyPair(AndroidKeyStoreKeyPairGeneratorSpi.java:502)
        at java.security.KeyPairGenerator$KeyPairGeneratorImpl.generateKeyPair(KeyPairGenerator.java:276) 
        at com.salesforce.androidsdk.security.KeyStoreWrapper.createKeysIfNecessary(KeyStoreWrapper.java:239) 
        at com.salesforce.androidsdk.security.KeyStoreWrapper.getPublicKey(KeyStoreWrapper.java:183) 
        at com.salesforce.androidsdk.security.KeyStoreWrapper.getRSAPublicKey(KeyStoreWrapper.java:119) 
        at com.salesforce.androidsdk.security.KeyStoreWrapper.getRSAPublicKey(KeyStoreWrapper.java:88) 
        at com.salesforce.androidsdk.security.SalesforceKeyGenerator.generateUniqueId(SalesforceKeyGenerator.java:239) 
        at com.salesforce.androidsdk.security.SalesforceKeyGenerator.getUniqueId(SalesforceKeyGenerator.java:90) 
        at com.salesforce.androidsdk.security.SalesforceKeyGenerator.getUniqueId(SalesforceKeyGenerator.java:79) 
        at com.salesforce.androidsdk.security.PasscodeManager.<init>(PasscodeManager.java:120) 
        at com.salesforce.androidsdk.app.SalesforceSDKManager.getPasscodeManager(SalesforceSDKManager.java:522) 
        at com.salesforce.androidsdk.ui.SalesforceActivityDelegate.onCreate(SalesforceActivityDelegate.java:60) 
        at org.mahgoub.app.base.SalesForceBaseActivity.onCreate(SalesForceBaseActivity.kt:16) 
        at org.mahgoub.app.login.LoginDoneActivity.onCreate(LoginDoneActivity.kt:23) 
        at android.app.Activity.performCreate(Activity.java:6237) 
        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1107) 
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2369) 
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2476) 
        at android.app.ActivityThread.-wrap11(ActivityThread.java) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1344) 
        at android.os.Handler.dispatchMessage(Handler.java:102) 
        at android.os.Looper.loop(Looper.java:148) 
        at android.app.ActivityThread.main(ActivityThread.java:5417) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616) 
03-11 17:03:40.626 4567-4567/org.mahgoub.app E/KeyStoreWrapper: Could not retrieve public key
    java.lang.NullPointerException: Attempt to invoke virtual method 'java.security.PublicKey java.security.cert.Certificate.getPublicKey()' on a null object reference
        at com.salesforce.androidsdk.security.KeyStoreWrapper.getPublicKey(KeyStoreWrapper.java:185)
        at com.salesforce.androidsdk.security.KeyStoreWrapper.getRSAPublicKey(KeyStoreWrapper.java:119)
        at com.salesforce.androidsdk.security.KeyStoreWrapper.getRSAPublicKey(KeyStoreWrapper.java:88)
        at com.salesforce.androidsdk.security.SalesforceKeyGenerator.generateUniqueId(SalesforceKeyGenerator.java:239)
        at com.salesforce.androidsdk.security.SalesforceKeyGenerator.getUniqueId(SalesforceKeyGenerator.java:90)
        at com.salesforce.androidsdk.security.SalesforceKeyGenerator.getUniqueId(SalesforceKeyGenerator.java:79)
        at com.salesforce.androidsdk.security.PasscodeManager.<init>(PasscodeManager.java:120)
        at com.salesforce.androidsdk.app.SalesforceSDKManager.getPasscodeManager(SalesforceSDKManager.java:522)
        at com.salesforce.androidsdk.ui.SalesforceActivityDelegate.onCreate(SalesforceActivityDelegate.java:60)
        at org.mahgoub.app.base.SalesForceBaseActivity.onCreate(SalesForceBaseActivity.kt:16)
        at org.mahgoub.app.login.LoginDoneActivity.onCreate(LoginDoneActivity.kt:23)
        at android.app.Activity.performCreate(Activity.java:6237)
        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1107)
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2369)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2476)
        at android.app.ActivityThread.-wrap11(ActivityThread.java)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1344)
        at android.os.Handler.dispatchMessage(Handler.java:102)
        at android.os.Looper.loop(Looper.java:148)
        at android.app.ActivityThread.main(ActivityThread.java:5417)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)
03-11 17:03:40.793 4567-4567/org.mahgoub.app E/KeyStoreWrapper: Could not generate key pair
    java.security.ProviderException: Failed to generate self-signed certificate
        at android.security.keystore.AndroidKeyStoreKeyPairGeneratorSpi.generateKeyPair(AndroidKeyStoreKeyPairGeneratorSpi.java:504)
        at java.security.KeyPairGenerator$KeyPairGeneratorImpl.generateKeyPair(KeyPairGenerator.java:276)
        at com.salesforce.androidsdk.security.KeyStoreWrapper.createKeysIfNecessary(KeyStoreWrapper.java:239)
        at com.salesforce.androidsdk.security.KeyStoreWrapper.getPublicKey(KeyStoreWrapper.java:183)
        at com.salesforce.androidsdk.security.KeyStoreWrapper.getRSAPublicKey(KeyStoreWrapper.java:119)
        at com.salesforce.androidsdk.security.KeyStoreWrapper.getRSAPublicKey(KeyStoreWrapper.java:88)
        at com.salesforce.androidsdk.security.SalesforceKeyGenerator.generateUniqueId(SalesforceKeyGenerator.java:239)
        at com.salesforce.androidsdk.security.SalesforceKeyGenerator.getUniqueId(SalesforceKeyGenerator.java:90)
        at com.salesforce.androidsdk.security.SalesforceKeyGenerator.getUniqueId(SalesforceKeyGenerator.java:79)
        at com.salesforce.androidsdk.security.PasscodeManager.<init>(PasscodeManager.java:121)
        at com.salesforce.androidsdk.app.SalesforceSDKManager.getPasscodeManager(SalesforceSDKManager.java:522)
        at com.salesforce.androidsdk.ui.SalesforceActivityDelegate.onCreate(SalesforceActivityDelegate.java:60)
        at org.mahgoub.app.base.SalesForceBaseActivity.onCreate(SalesForceBaseActivity.kt:16)
        at org.mahgoub.app.login.LoginDoneActivity.onCreate(LoginDoneActivity.kt:23)
        at android.app.Activity.performCreate(Activity.java:6237)
        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1107)
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2369)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2476)
        at android.app.ActivityThread.-wrap11(ActivityThread.java)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1344)
        at android.os.Handler.dispatchMessage(Handler.java:102)
        at android.os.Looper.loop(Looper.java:148)
        at android.app.ActivityThread.main(ActivityThread.java:5417)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)
     Caused by: java.lang.IllegalArgumentException: invalid date string: Unparseable date: "g``a`a``````GMT+00:00" (at offset 0)
        at com.android.org.bouncycastle.asn1.ASN1UTCTime.<init>(ASN1UTCTime.java:115)
        at com.android.org.bouncycastle.asn1.DERUTCTime.<init>(DERUTCTime.java:23)
        at com.android.org.bouncycastle.asn1.x509.Time.<init>(Time.java:67)
        at android.security.keystore.AndroidKeyStoreKeyPairGeneratorSpi.generateSelfSignedCertificateWithFakeSignature(AndroidKeyStoreKeyPairGeneratorSpi.java:618)
        at android.security.keystore.AndroidKeyStoreKeyPairGeneratorSpi.generateSelfSignedCertificate(AndroidKeyStoreKeyPairGeneratorSpi.java:553)
        at android.security.keystore.AndroidKeyStoreKeyPairGeneratorSpi.generateKeyPair(AndroidKeyStoreKeyPairGeneratorSpi.java:502)
        at java.security.KeyPairGenerator$KeyPairGeneratorImpl.generateKeyPair(KeyPairGenerator.java:276) 
        at com.salesforce.androidsdk.security.KeyStoreWrapper.createKeysIfNecessary(KeyStoreWrapper.java:239) 
        at com.salesforce.androidsdk.security.KeyStoreWrapper.getPublicKey(KeyStoreWrapper.java:183) 
        at com.salesforce.androidsdk.security.KeyStoreWrapper.getRSAPublicKey(KeyStoreWrapper.java:119) 
        at com.salesforce.androidsdk.security.KeyStoreWrapper.getRSAPublicKey(KeyStoreWrapper.java:88) 
        at com.salesforce.androidsdk.security.SalesforceKeyGenerator.generateUniqueId(SalesforceKeyGenerator.java:239) 
        at com.salesforce.androidsdk.security.SalesforceKeyGenerator.getUniqueId(SalesforceKeyGenerator.java:90) 
        at com.salesforce.androidsdk.security.SalesforceKeyGenerator.getUniqueId(SalesforceKeyGenerator.java:79) 
        at com.salesforce.androidsdk.security.PasscodeManager.<init>(PasscodeManager.java:121) 
        at com.salesforce.androidsdk.app.SalesforceSDKManager.getPasscodeManager(SalesforceSDKManager.java:522) 
        at com.salesforce.androidsdk.ui.SalesforceActivityDelegate.onCreate(SalesforceActivityDelegate.java:60) 
        at org.mahgoub.app.base.SalesForceBaseActivity.onCreate(SalesForceBaseActivity.kt:16) 
        at org.mahgoub.app.login.LoginDoneActivity.onCreate(LoginDoneActivity.kt:23) 
        at android.app.Activity.performCreate(Activity.java:6237) 
        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1107) 
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2369) 
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2476) 
        at android.app.ActivityThread.-wrap11(ActivityThread.java) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1344) 
        at android.os.Handler.dispatchMessage(Handler.java:102) 
        at android.os.Looper.loop(Looper.java:148) 
        at android.app.ActivityThread.main(ActivityThread.java:5417) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616) 
03-11 17:03:40.795 4567-4567/org.mahgoub.app E/KeyStoreWrapper: Could not retrieve public key
    java.lang.NullPointerException: Attempt to invoke virtual method 'java.security.PublicKey java.security.cert.Certificate.getPublicKey()' on a null object reference
        at com.salesforce.androidsdk.security.KeyStoreWrapper.getPublicKey(KeyStoreWrapper.java:185)
        at com.salesforce.androidsdk.security.KeyStoreWrapper.getRSAPublicKey(KeyStoreWrapper.java:119)
        at com.salesforce.androidsdk.security.KeyStoreWrapper.getRSAPublicKey(KeyStoreWrapper.java:88)
        at com.salesforce.androidsdk.security.SalesforceKeyGenerator.generateUniqueId(SalesforceKeyGenerator.java:239)
        at com.salesforce.androidsdk.security.SalesforceKeyGenerator.getUniqueId(SalesforceKeyGenerator.java:90)
        at com.salesforce.androidsdk.security.SalesforceKeyGenerator.getUniqueId(SalesforceKeyGenerator.java:79)
        at com.salesforce.androidsdk.security.PasscodeManager.<init>(PasscodeManager.java:121)
        at com.salesforce.androidsdk.app.SalesforceSDKManager.getPasscodeManager(SalesforceSDKManager.java:522)
        at com.salesforce.androidsdk.ui.SalesforceActivityDelegate.onCreate(SalesforceActivityDelegate.java:60)
        at org.mahgoub.app.base.SalesForceBaseActivity.onCreate(SalesForceBaseActivity.kt:16)
        at org.mahgoub.app.login.LoginDoneActivity.onCreate(LoginDoneActivity.kt:23)
        at android.app.Activity.performCreate(Activity.java:6237)
        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1107)
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2369)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2476)
        at android.app.ActivityThread.-wrap11(ActivityThread.java)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1344)
        at android.os.Handler.dispatchMessage(Handler.java:102)
        at android.os.Looper.loop(Looper.java:148)
        at android.app.ActivityThread.main(ActivityThread.java:5417)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)
03-11 17:03:40.916 4567-4567/org.mahgoub.app E/KeyStoreWrapper: Could not generate key pair
    java.security.ProviderException: Failed to generate self-signed certificate
        at android.security.keystore.AndroidKeyStoreKeyPairGeneratorSpi.generateKeyPair(AndroidKeyStoreKeyPairGeneratorSpi.java:504)
        at java.security.KeyPairGenerator$KeyPairGeneratorImpl.generateKeyPair(KeyPairGenerator.java:276)
        at com.salesforce.androidsdk.security.KeyStoreWrapper.createKeysIfNecessary(KeyStoreWrapper.java:239)
        at com.salesforce.androidsdk.security.KeyStoreWrapper.getPublicKey(KeyStoreWrapper.java:183)
        at com.salesforce.androidsdk.security.KeyStoreWrapper.getRSAPublicKey(KeyStoreWrapper.java:119)
        at com.salesforce.androidsdk.security.KeyStoreWrapper.getRSAPublicKey(KeyStoreWrapper.java:88)
        at com.salesforce.androidsdk.security.SalesforceKeyGenerator.generateUniqueId(SalesforceKeyGenerator.java:239)
        at com.salesforce.androidsdk.security.SalesforceKeyGenerator.getUniqueId(SalesforceKeyGenerator.java:90)
        at com.salesforce.androidsdk.security.SalesforceKeyGenerator.getUniqueId(SalesforceKeyGenerator.java:79)
        at com.salesforce.androidsdk.security.PasscodeManager.<init>(PasscodeManager.java:122)
        at com.salesforce.androidsdk.app.SalesforceSDKManager.getPasscodeManager(SalesforceSDKManager.java:522)
        at com.salesforce.androidsdk.ui.SalesforceActivityDelegate.onCreate(SalesforceActivityDelegate.java:60)
        at org.mahgoub.app.base.SalesForceBaseActivity.onCreate(SalesForceBaseActivity.kt:16)
        at org.mahgoub.app.login.LoginDoneActivity.onCreate(LoginDoneActivity.kt:23)
        at android.app.Activity.performCreate(Activity.java:6237)
        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1107)
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2369)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2476)
        at android.app.ActivityThread.-wrap11(ActivityThread.java)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1344)
        at android.os.Handler.dispatchMessage(Handler.java:102)
        at android.os.Looper.loop(Looper.java:148)
        at android.app.ActivityThread.main(ActivityThread.java:5417)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)
     Caused by: java.lang.IllegalArgumentException: invalid date string: Unparseable date: "g``a`a``````GMT+00:00" (at offset 0)
        at com.android.org.bouncycastle.asn1.ASN1UTCTime.<init>(ASN1UTCTime.java:115)
        at com.android.org.bouncycastle.asn1.DERUTCTime.<init>(DERUTCTime.java:23)
        at com.android.org.bouncycastle.asn1.x509.Time.<init>(Time.java:67)
        at android.security.keystore.AndroidKeyStoreKeyPairGeneratorSpi.generateSelfSignedCertificateWithFakeSignature(AndroidKeyStoreKeyPairGeneratorSpi.java:618)
        at android.security.keystore.AndroidKeyStoreKeyPairGeneratorSpi.generateSelfSignedCertificate(AndroidKeyStoreKeyPairGeneratorSpi.java:553)
        at android.security.keystore.AndroidKeyStoreKeyPairGeneratorSpi.generateKeyPair(AndroidKeyStoreKeyPairGeneratorSpi.java:502)
        at java.security.KeyPairGenerator$KeyPairGeneratorImpl.generateKeyPair(KeyPairGenerator.java:276) 
        at com.salesforce.androidsdk.security.KeyStoreWrapper.createKeysIfNecessary(KeyStoreWrapper.java:239) 
        at com.salesforce.androidsdk.security.KeyStoreWrapper.getPublicKey(KeyStoreWrapper.java:183) 
        at com.salesforce.androidsdk.security.KeyStoreWrapper.getRSAPublicKey(KeyStoreWrapper.java:119) 
        at com.salesforce.androidsdk.security.KeyStoreWrapper.getRSAPublicKey(KeyStoreWrapper.java:88) 
        at com.salesforce.androidsdk.security.SalesforceKeyGenerator.generateUniqueId(SalesforceKeyGenerator.java:239) 
        at com.salesforce.androidsdk.security.SalesforceKeyGenerator.getUniqueId(SalesforceKeyGenerator.java:90) 
        at com.salesforce.androidsdk.security.SalesforceKeyGenerator.getUniqueId(SalesforceKeyGenerator.java:79) 
        at com.salesforce.androidsdk.security.PasscodeManager.<init>(PasscodeManager.java:122) 
        at com.salesforce.androidsdk.app.SalesforceSDKManager.getPasscodeManager(SalesforceSDKManager.java:522) 
        at com.salesforce.androidsdk.ui.SalesforceActivityDelegate.onCreate(SalesforceActivityDelegate.java:60) 
        at org.mahgoub.app.base.SalesForceBaseActivity.onCreate(SalesForceBaseActivity.kt:16) 
        at org.mahgoub.app.login.LoginDoneActivity.onCreate(LoginDoneActivity.kt:23) 
        at android.app.Activity.performCreate(Activity.java:6237) 
        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1107) 
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2369) 
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2476) 
        at android.app.ActivityThread.-wrap11(ActivityThread.java) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1344) 
        at android.os.Handler.dispatchMessage(Handler.java:102) 
        at android.os.Looper.loop(Looper.java:148) 
        at android.app.ActivityThread.main(ActivityThread.java:5417) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616) 
03-11 17:03:40.929 4567-4567/org.mahgoub.app E/KeyStoreWrapper: Could not retrieve public key
    java.lang.NullPointerException: Attempt to invoke virtual method 'java.security.PublicKey java.security.cert.Certificate.getPublicKey()' on a null object reference
        at com.salesforce.androidsdk.security.KeyStoreWrapper.getPublicKey(KeyStoreWrapper.java:185)
        at com.salesforce.androidsdk.security.KeyStoreWrapper.getRSAPublicKey(KeyStoreWrapper.java:119)
        at com.salesforce.androidsdk.security.KeyStoreWrapper.getRSAPublicKey(KeyStoreWrapper.java:88)
        at com.salesforce.androidsdk.security.SalesforceKeyGenerator.generateUniqueId(SalesforceKeyGenerator.java:239)
        at com.salesforce.androidsdk.security.SalesforceKeyGenerator.getUniqueId(SalesforceKeyGenerator.java:90)
        at com.salesforce.androidsdk.security.SalesforceKeyGenerator.getUniqueId(SalesforceKeyGenerator.java:79)
        at com.salesforce.androidsdk.security.PasscodeManager.<init>(PasscodeManager.java:122)
        at com.salesforce.androidsdk.app.SalesforceSDKManager.getPasscodeManager(SalesforceSDKManager.java:522)
        at com.salesforce.androidsdk.ui.SalesforceActivityDelegate.onCreate(SalesforceActivityDelegate.java:60)
        at org.mahgoub.app.base.SalesForceBaseActivity.onCreate(SalesForceBaseActivity.kt:16)
        at org.mahgoub.app.login.LoginDoneActivity.onCreate(LoginDoneActivity.kt:23)
        at android.app.Activity.performCreate(Activity.java:6237)
        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1107)
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2369)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2476)
        at android.app.ActivityThread.-wrap11(ActivityThread.java)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1344)
        at android.os.Handler.dispatchMessage(Handler.java:102)
        at android.os.Looper.loop(Looper.java:148)
        at android.app.ActivityThread.main(ActivityThread.java:5417)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)
