### ISSUE TITLE
FCM registration error

### ISSUE THREAD

**Issue by llyrProximity** [forcedotcom/SalesforceMobileSDK-Android#2174]
Please fill out the following details:

Hi, I've seen that this issue has been closed, but I'm still experiencing this problem. I've created native app today, and I'm still seeing this error.

Version of Mobile SDK Used: 9.0.0
Issue found on Native App
OS Version: Android 10 and Android 11
Device: Samsung Tab 7

Error
```
2021-03-09 11:14:15.345 6128-6233/com.test.push E/RegIntentService: Error during FCM registration
    java.lang.IllegalArgumentException: Please set your project ID. A valid Firebase project ID is required to communicate with Firebase server APIs: It identifies your project with Google.
        at com.google.android.gms.common.internal.Preconditions.checkNotEmpty(Unknown Source:8)
        at com.google.firebase.iid.FirebaseInstanceId.checkRequiredFirebaseOptions(com.google.firebase:firebase-iid@@21.0.1:2)
        at com.google.firebase.iid.FirebaseInstanceId.getInstance(com.google.firebase:firebase-iid@@21.0.1:2)
        at com.salesforce.androidsdk.push.SFDCRegistrationIntentService.onHandleWork(SFDCRegistrationIntentService.java:62)
        at androidx.core.app.JobIntentService$CommandProcessor.doInBackground(JobIntentService.java:392)
        at androidx.core.app.JobIntentService$CommandProcessor.doInBackground(JobIntentService.java:383)
        at android.os.AsyncTask$3.call(AsyncTask.java:394)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
        at java.lang.Thread.run(Thread.java:923)
```

**Comment by bhariharan** [comment]
Do you have a way to reproduce this problem consistently? Are you using other libraries that use `Firebase` or using a newer version of `Firebase` in your app?

**Comment by bhariharan** [comment]
@llyrProximity Yeah, this is because you're using `firebase-messaging@21.0.1`. We don't support that version yet, we are aware there is some work to be done to support that version with the way we initialize `FirebaseApp`. Please use `firebase-messaging@20.1.0` instead (this is automatically included in our library).
