### ISSUE TITLE
SalesforceSDKManager: Package info could not be retrieved

### ISSUE THREAD

**Issue by johnjeremih** [forcedotcom/SalesforceMobileSDK-Android#2176]
Please fill out the following details:
This app has the SDK version 9.0.0 

**1. Version of Mobile SDK Used:** 29
**2. Issue found in Native App or Hybrid App:** Native APP
**3. OS Version:** 29
**4. Device:** pixel 2 XL
**5. Steps to reproduce:** Just running the app
**6. Actual behavior:**
**7. Expected Behavior:**
**8. Error Log:** Package info could not be retrieved

`W/SalesforceSDKManager: Package info could not be retrieved
    android.content.res.Resources$NotFoundException: String resource ID #0x0
        at android.content.res.Resources.getText(Resources.java:353)
        at android.content.res.Resources.getString(Resources.java:447)
        at android.content.Context.getString(Context.java:556)
        at com.salesforce.androidsdk.app.SalesforceSDKManager.provideAppName(SalesforceSDKManager.java:993)
        at com.salesforce.androidsdk.app.SalesforceSDKManager.getUserAgent(SalesforceSDKManager.java:1008)
        at com.salesforce.androidsdk.app.SalesforceSDKManager.getUserAgent(SalesforceSDKManager.java:981)
        at com.salesforce.androidsdk.auth.HttpAccess$UserAgentInterceptor.intercept(HttpAccess.java:179)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
        at okhttp3.internal.connection.ConnectInterceptor.intercept(ConnectInterceptor.kt:34)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
        at okhttp3.internal.cache.CacheInterceptor.intercept(CacheInterceptor.kt:95)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
        at okhttp3.internal.http.BridgeInterceptor.intercept(BridgeInterceptor.kt:83)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
        at okhttp3.internal.http.RetryAndFollowUpInterceptor.intercept(RetryAndFollowUpInterceptor.kt:76)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
        at okhttp3.internal.connection.RealCall.getResponseWithInterceptorChain$okhttp(RealCall.kt:201)
        at okhttp3.internal.connection.RealCall.execute(RealCall.kt:154)
        at com.google.firebase.perf.network.FirebasePerfOkHttpClient.execute(com.google.firebase:firebase-perf@@19.0.5:5)
        at com.salesforce.androidsdk.util.AuthConfigUtil.getMyDomainAuthConfig(AuthConfigUtil.java:72)
        at com.salesforce.androidsdk.util.AuthConfigTask.doInBackground(AuthConfigTask.java:77)
        at com.salesforce.androidsdk.util.AuthConfigTask.doInBackground(AuthConfigTask.java:44)
        at android.os.AsyncTask$2.call(AsyncTask.java:333)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:245)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1162)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636)
        at java.lang.Thread.run(Thread.java:764)`

**Comment by wmathurin** [comment]
This is just a warning that is logged here: https://github.com/forcedotcom/SalesforceMobileSDK-Android/blob/dev/libs/SalesforceSDK/src/com/salesforce/androidsdk/app/SalesforceSDKManager.java#L994.
It should not interfere with the application running.
You can override provideAppName() if you want to provide the app name in some other ways.

**Comment by johnjeremih** [comment]
@wmathurin  where do you override provideAppName() method? I also need to know how to extend the LoginActivity class
