### ISSUE TITLE
Could not retrieve public key

### ISSUE THREAD

**Issue by johnjeremih** [forcedotcom/SalesforceMobileSDK-Android#2180]
Please fill out the following details:

1. Version of Mobile SDK Used: 29
2. Issue found in Native App or Hybrid App: Native
3. OS Version: 10
4. Device: Pixel 4 XL (Emulator)
5. Steps to reproduce: Just runing the app
6. Actual behavior:
7. Expected Behavior:
8. Error Log:

`E/KeyStoreWrapper: Could not retrieve public key
    java.lang.NullPointerException: Attempt to invoke virtual method 'java.security.PublicKey java.security.cert.Certificate.getPublicKey()' on a null object reference
        at com.salesforce.androidsdk.security.KeyStoreWrapper.getPublicKey(KeyStoreWrapper.java:185)
        at com.salesforce.androidsdk.security.KeyStoreWrapper.getPublicKeyString(KeyStoreWrapper.java:193)
        at com.salesforce.androidsdk.security.KeyStoreWrapper.getRSAPublicString(KeyStoreWrapper.java:130)
        at com.salesforce.androidsdk.security.KeyStoreWrapper.getRSAPublicString(KeyStoreWrapper.java:98)
        at com.salesforce.androidsdk.push.PushService.getRSAPublicKey(PushService.java:325)
        at com.salesforce.androidsdk.push.PushService.registerSFDCPushNotification(PushService.java:281)
        at com.salesforce.androidsdk.push.PushService.onRegistered(PushService.java:202)
        at com.salesforce.androidsdk.push.PushService.performRegistrationChange(PushService.java:171)
        at com.salesforce.androidsdk.push.PushService.onHandleWork(PushService.java:161)
        at androidx.core.app.JobIntentService$CommandProcessor.doInBackground(JobIntentService.java:392)
        at androidx.core.app.JobIntentService$CommandProcessor.doInBackground(JobIntentService.java:383)
        at android.os.AsyncTask$3.call(AsyncTask.java:378)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
        at java.lang.Thread.run(Thread.java:919)`

**Comment by wmathurin** [comment]
Need more info to make some progress.
