### ISSUE TITLE
Crash on AccountSwitcherActivity.java line 61

### ISSUE THREAD

**Issue by johnjeremih** [forcedotcom/SalesforceMobileSDK-Android#2199]
Please fill out the following details:

1. Version of Mobile SDK Used: 9.0.0
2. Issue found in Native App or Hybrid App: Native
![image](https://user-images.githubusercontent.com/4177453/122574702-ed5f3200-d01d-11eb-96a0-1c63f2e857d1.png)
5. Steps to reproduce: It not happening on all the phones
6. Actual behavior:
7. Expected Behavior:
8. Error Log:
9. ```Fatal Exception: java.lang.RuntimeException: Unable to start activity ComponentInfo{com.app/com.salesforce.androidsdk.ui.AccountSwitcherActivity}: android.view.InflateException: Binary XML file line #10: Binary XML file line #10: Error inflating class android.widget.ImageView
       at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2951)
       at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3086)
       at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:78)
       at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:108)
       at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:68)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1816)
       at android.os.Handler.dispatchMessage(Handler.java:106)
       at android.os.Looper.loop(Looper.java:193)
       at android.app.ActivityThread.main(ActivityThread.java:6718)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)```

**Comment by wmathurin** [comment]
How did you generate/create your application?

**Comment by johnjeremih** [comment]
@wmathurin  what do you mean?

**Comment by wmathurin** [comment]
Did you use `forcedroid` (or `forcehybrid` or `forcereact`) to generate the application from one of our templates?

**Comment by wmathurin** [comment]
Last questions never answered. Closing.
