### ISSUE TITLE
Package info could not be retrieved

### ISSUE THREAD

**Issue by johnjeremih** [forcedotcom/SalesforceMobileSDK-Android#2200]
Please fill out the following details:

1. Version of Mobile SDK Used: v9.0.0
2. Issue found in Native App or Hybrid App: Native
3. OS Version: 8
4. Device: Samsung 
5. Steps to reproduce:
6. Actual behavior:
7. Expected Behavior:
8. Error Log:
```W/SalesforceSDKManager: Package info could not be retrieved
    android.content.res.Resources$NotFoundException: String resource ID #0x0
        at android.content.res.Resources.getText(Resources.java:353)
        at android.content.res.Resources.getString(Resources.java:447)
        at android.content.Context.getString(Context.java:556)
        at com.salesforce.androidsdk.app.SalesforceSDKManager.provideAppName(SalesforceSDKManager.java:993)
        at com.salesforce.androidsdk.app.SalesforceSDKManager.getUserAgent(SalesforceSDKManager.java:1008)
        at com.salesforce.androidsdk.app.SalesforceSDKManager.getUserAgent(SalesforceSDKManager.java:981)
        at com.salesforce.androidsdk.auth.HttpAccess$UserAgentInterceptor.intercept(HttpAccess.java:179)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
        at okhttp3.internal.connection.ConnectInterceptor.intercept(ConnectInterceptor.kt:34)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
        at okhttp3.internal.cache.CacheInterceptor.intercept(CacheInterceptor.kt:95)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
        at okhttp3.internal.http.BridgeInterceptor.intercept(BridgeInterceptor.kt:83)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
        at okhttp3.internal.http.RetryAndFollowUpInterceptor.intercept(RetryAndFollowUpInterceptor.kt:76)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
        at com.salesforce.androidsdk.rest.RestClient$OAuthRefreshInterceptor.intercept(RestClient.java:652)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
        at okhttp3.internal.connection.RealCall.getResponseWithInterceptorChain$okhttp(RealCall.kt:201)
        at okhttp3.internal.connection.RealCall.execute(RealCall.kt:154)
        at com.google.firebase.perf.network.FirebasePerfOkHttpClient.execute(FirebasePerfOkHttpClient.java:44)
        at com.salesforce.androidsdk.rest.RestClient.sendSync(RestClient.java:368)
        at com.salesforce.androidsdk.push.PushService.onSendRegisterPushNotificationRequest(PushService.java:247)
        at com.salesforce.androidsdk.push.PushService.registerSFDCPushNotification(PushService.java:288)
        at com.salesforce.androidsdk.push.PushService.onRegistered(PushService.java:202)
        at com.salesforce.androidsdk.push.PushService.performRegistrationChange(PushService.java:171)
        at com.salesforce.androidsdk.push.PushService.onHandleWork(PushService.java:161)
        at androidx.core.app.JobIntentService$CommandProcessor.doInBackground(JobIntentService.java:391)
        at androidx.core.app.JobIntentService$CommandProcessor.doInBackground(JobIntentService.java:382)
        at android.os.AsyncTask$2.call(AsyncTask.java:333)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1162)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636)
        at java.lang.Thread.run(Thread.java:764)```

**Comment by wmathurin** [comment]
How did you generate/create your application?

**Comment by johnjeremih** [comment]
I don't understand what do you mean by "How did you generate/create your application"

**Comment by wmathurin** [comment]
Did you use `forcedroid` (or `forcehybrid` or `forcereact`) to generate the application from one of our templates?

**Comment by johnjeremih** [comment]
I'm using forcedroid

**Comment by wmathurin** [comment]
What value does app_name have in app/res/values/strings.xml ?

**Comment by johnjeremih** [comment]
The name of the App

**Comment by wmathurin** [comment]
This part of the code has not changed in years and we have not seen the issue.
Could you walk us through the steps you went through:
- you generated a new application with forcedroid
- you build and ran it from Android Studio
- you get the error at launch

**Comment by wmathurin** [comment]
No answers to the last set of questions. Closing.

**Comment by johnjeremih** [comment]
@wmathurin I cannot use a new forcedroid application because doesn't support environments. Please check out this [https://github.com/forcedotcom/SalesforceMobileSDK-Android/issues/2249](URL)
