### ISSUE TITLE
java.lang.NoClassDefFoundError: Failed resolution of: Lcom/google/android/gms/common/GoogleApiAvailability;

### ISSUE THREAD

**Issue by rspapneja** [forcedotcom/SalesforceMobileSDK-Android#2201]
--------- beginning of crash
2021-06-23 05:43:20.993 14154-14154/com.varian.assist E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.varian.assist, PID: 14154
    java.lang.NoClassDefFoundError: Failed resolution of: Lcom/google/android/gms/common/GoogleApiAvailability;
        at com.salesforce.androidsdk.push.PushMessaging.checkPlayServices(PushMessaging.java:423)
        at com.salesforce.androidsdk.push.PushMessaging.register(PushMessaging.java:104)
        at com.salesforce.androidsdk.ui.OAuthWebviewHelper.addAccount(OAuthWebviewHelper.java:663)
        at com.salesforce.androidsdk.ui.OAuthWebviewHelper$BaseFinishAuthFlowTask.onPostExecute(OAuthWebviewHelper.java:574)
        at com.salesforce.androidsdk.ui.OAuthWebviewHelper$BaseFinishAuthFlowTask.onPostExecute(OAuthWebviewHelper.java:504)
        at android.os.AsyncTask.finish(AsyncTask.java:755)
        at android.os.AsyncTask.access$900(AsyncTask.java:192)
        at android.os.AsyncTask$InternalHandler.handleMessage(AsyncTask.java:772)
        at android.os.Handler.dispatchMessage(Handler.java:107)
        at android.os.Looper.loop(Looper.java:223)
        at android.app.ActivityThread.main(ActivityThread.java:7562)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:539)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:950)
     Caused by: java.lang.ClassNotFoundException: Didn't find class "com.google.android.gms.common.GoogleApiAvailability" on path: DexPathList[[zip file "/data/app/com.varian.assist-cf6iFu6xNHl_lQiHUsEdYA==/base.apk"],nativeLibraryDirectories=[/data/app/com.varian.assist-cf6iFu6xNHl_lQiHUsEdYA==/lib/arm64, /system/lib64, /system/product/lib64]]
        at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:230)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:379)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
        at com.salesforce.androidsdk.push.PushMessaging.checkPlayServices(PushMessaging.java:423) 
        at com.salesforce.androidsdk.push.PushMessaging.register(PushMessaging.java:104) 
        at com.salesforce.androidsdk.ui.OAuthWebviewHelper.addAccount(OAuthWebviewHelper.java:663) 
        at com.salesforce.androidsdk.ui.OAuthWebviewHelper$BaseFinishAuthFlowTask.onPostExecute(OAuthWebviewHelper.java:574) 
        at com.salesforce.androidsdk.ui.OAuthWebviewHelper$BaseFinishAuthFlowTask.onPostExecute(OAuthWebviewHelper.java:504) 
        at android.os.AsyncTask.finish(AsyncTask.java:755) 
        at android.os.AsyncTask.access$900(AsyncTask.java:192) 
        at android.os.AsyncTask$InternalHandler.handleMessage(AsyncTask.java:772) 
        at android.os.Handler.dispatchMessage(Handler.java:107) 
        at android.os.Looper.loop(Looper.java:223) 
        at android.app.ActivityThread.main(ActivityThread.java:7562) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:539) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:950) 
![1](https://user-images.githubusercontent.com/33872930/123099537-21a06d00-d3e7-11eb-8d6d-d079f4f17d2b.png)

**Comment by rspapneja** [comment]
I amusing native app sdk

**Comment by wmathurin** [comment]
So you ran `forcedroid` to create you native application?
