### ISSUE TITLE
SalesforceCrashInterceptor "Session expired or invalid errorCode"  INVALID_SESSION_ID

### ISSUE THREAD

**Issue by johnjeremih** [forcedotcom/SalesforceMobileSDK-Android#2204]
Hello this is Native android and I'm getting a lot of Non-fatal

![image](https://user-images.githubusercontent.com/4177453/125129172-0b73fb80-e0cd-11eb-895c-afbf65a7103d.png)
![image](https://user-images.githubusercontent.com/4177453/125129265-35c5b900-e0cd-11eb-91b3-c192f50b2801.png)

``` Non-fatal Exception: com.mine.nativeandroid.util.SalesforceCrashInterceptor$SalesforceApiException: [{"message":"Session expired or invalid","errorCode":"INVALID_SESSION_ID"}]
       at com.mine.nativeandroid.util.SalesforceCrashInterceptor.intercept(SalesforceCrashInterceptor.java:33)
       at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
       at okhttp3.logging.HttpLoggingInterceptor.intercept(HttpLoggingInterceptor.kt:221)
       at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
       at com.salesforce.androidsdk.auth.HttpAccess$UserAgentInterceptor.intercept(HttpAccess.java:181)
       at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
       at okhttp3.internal.connection.ConnectInterceptor.intercept(ConnectInterceptor.kt:34)
       at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
       at okhttp3.internal.cache.CacheInterceptor.intercept(CacheInterceptor.kt:95)
       at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
       at okhttp3.internal.http.BridgeInterceptor.intercept(BridgeInterceptor.kt:83)
       at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
       at okhttp3.internal.http.RetryAndFollowUpInterceptor.intercept(RetryAndFollowUpInterceptor.kt:76)
       at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
       at com.salesforce.androidsdk.rest.RestClient$OAuthRefreshInterceptor.intercept(RestClient.java:652)
       at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
       at okhttp3.internal.connection.RealCall.getResponseWithInterceptorChain$okhttp(RealCall.kt:201)
       at okhttp3.internal.connection.RealCall.execute(RealCall.kt:154)
       at com.google.firebase.perf.network.FirebasePerfOkHttpClient.execute(FirebasePerfOkHttpClient.java:44)
       at com.salesforce.androidsdk.rest.RestClient.sendSync(RestClient.java:368)
       at com.salesforce.androidsdk.push.PushService.onSendRegisterPushNotificationRequest(PushService.java:247)
       at com.salesforce.androidsdk.push.PushService.registerSFDCPushNotification(PushService.java:288)
       at com.salesforce.androidsdk.push.PushService.onRegistered(PushService.java:202)
       at com.salesforce.androidsdk.push.PushService.performRegistrationChange(PushService.java:171)
       at com.salesforce.androidsdk.push.PushService.onHandleWork(PushService.java:161)
       at androidx.core.app.JobIntentService$CommandProcessor.doInBackground(JobIntentService.java:391)
       at androidx.core.app.JobIntentService$CommandProcessor.doInBackground(JobIntentService.java:382)
       at android.os.AsyncTask$3.call(AsyncTask.java:394)
       at java.util.concurrent.FutureTask.run(FutureTask.java:266)
       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
       at java.lang.Thread.run(Thread.java:923) ```

**Comment by gkotula** [comment]
Hello,

It seems like `SalesforceCrashInterceptor` is picking up _every_ non-successful HTTP request, and it is not surprising that this is creating a lot of warning noise.  Many things can go wrong with any request such as timeouts, unstable wireless connectivity, etc.  Logging every single HTTP failure as an exception is expected to create a high volume of non-fatals in any logging system.

We would recommend filtering out some of the failed responses for common cases like network timeouts.  That should reduce your non-fatals count.
