### ISSUE TITLE
java.lang.IllegalArgumentException: Please set your project ID. A valid Firebase project ID is required to communicate with Firebase server APIs: It identifies your project with Google.

### ISSUE THREAD

**Issue by webaddicted** [forcedotcom/SalesforceMobileSDK-Android#2228]
Please fill out the following details:

1. Version of Mobile SDK Used: 
2. Issue found in Native App or Hybrid App:Native App
3. OS Version: Android 11
4. Device: All (POCO X3)
5. Steps to reproduce: After login salesforce SDK at mobile end then it  throw error 

**Please set your project ID. A valid Firebase project ID is required to communicate with Firebase server APIs: It identifies your project with Google.**

6. Actual behavior: Push notification token not register on salesforce. I already define
 `**<string name="androidPushNotificationClientId"></string>**` in boot config file
7. Expected Behavior: When user login then push notification token should register on salesforce.

8. Error Log:

2021-09-09 20:33:42.937 32596-32668/com.nanostuffs.apps.ceat_tyres E/**RegIntentService: Error during FCM registration
    java.lang.IllegalArgumentException: Please set your project ID. A valid Firebase project ID is required to communicate with Firebase server APIs: It identifies your project with Google.**
        at com.google.android.gms.common.internal.Preconditions.checkNotEmpty(com.google.android.gms:play-services-basement@@17.5.0:8)
        at com.google.firebase.iid.FirebaseInstanceId.checkRequiredFirebaseOptions(com.google.firebase:firebase-iid@@21.0.0:52)
        at com.google.firebase.iid.FirebaseInstanceId.getInstance(com.google.firebase:firebase-iid@@21.0.0:2)
        at com.salesforce.androidsdk.push.SFDCRegistrationIntentService.onHandleWork(**SFDCRegistrationIntentService**.java:62)
        at androidx.core.app.JobIntentService$CommandProcessor.doInBackground(JobIntentService.java:392)
        at androidx.core.app.JobIntentService$CommandProcessor.doInBackground(JobIntentService.java:383)
        at android.os.AsyncTask$3.call(AsyncTask.java:394)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
        at java.lang.Thread.run(Thread.java:923)

**Comment by bhariharan** [comment]
You're using an unsupported version  of Firebase - `21.0.0`, as indicated in the logs. Please downgrade to the version supported by Mobile SDK - `20.1.0`.

**Comment by webaddicted** [comment]
@bhariharan 

This issue is not because of Firebase version 21.0.0.
Currently I'm using 20.1.0 have a look


dependencies {
    api project(':libs:SalesforceAnalytics')
    api 'com.squareup.okhttp3:okhttp:3.12.1'
    **api 'com.google.firebase:firebase-messaging:20.1.0'**
    api 'androidx.core:core:1.2.0'
}

This version manage in libs:SalesforceSDK. and in my app gradle file I'm using BoM so I don't need to specify version.

    **implementation 'com.google.firebase:firebase-crashlytics-ktx'
    implementation 'com.google.firebase:firebase-analytics-ktx'
    implementation 'com.google.firebase:firebase-messaging-ktx'**

Please Check this issue this is very urgent issue.

**Comment by webaddicted** [comment]
@bhariharan 

Also look into this


2021-09-10 10:56:15.713 21823-21823/com.nanostuffs.apps.ceat_tyres **W/PushMessaging: Firebase hasn't been initialized yet
    java.lang.IllegalStateException: FirebaseApp with name Ceat-Assist doesn't exist. Available app names: [DEFAULT]**
        at com.google.firebase.FirebaseApp.getInstance(FirebaseApp.java:217)
        at com.salesforce.androidsdk.push.PushMessaging.initializeFirebaseIfNeeded(PushMessaging.java:163)
        at com.salesforce.androidsdk.push.PushMessaging.register(PushMessaging.java:101)
        at com.salesforce.androidsdk.ui.OAuthWebviewHelper.addAccount(OAuthWebviewHelper.java:704)
        at com.salesforce.androidsdk.ui.OAuthWebviewHelper$BaseFinishAuthFlowTask.onPostExecute(OAuthWebviewHelper.java:614)
        at com.salesforce.androidsdk.ui.OAuthWebviewHelper$BaseFinishAuthFlowTask.onPostExecute(OAuthWebviewHelper.java:544)
        at android.os.AsyncTask.finish(AsyncTask.java:771)
        at android.os.AsyncTask.access$900(AsyncTask.java:199)
        at android.os.AsyncTask$InternalHandler.handleMessage(AsyncTask.java:788)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loop(Looper.java:236)
        at android.app.ActivityThread.main(ActivityThread.java:7889)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:600)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:967)
2021-09-10 10:56:15.720 21823-21823/com.nanostuffs.apps.ceat_tyres I/FirebaseApp: Device unlocked: initializing all Firebase APIs for app Ceat-Assist
2021-09-10 10:56:15.946 21823-23589**/com.nanostuffs.apps.ceat_tyres E/RegIntentService: Error during FCM registration
    java.lang.IllegalArgumentException: Please set your project ID. A valid Firebase project ID is required to communicate with Firebase server APIs: It identifies your project with Google.**
        at com.google.android.gms.common.internal.Preconditions.checkNotEmpty(com.google.android.gms:play-services-basement@@17.5.0:8)
        at com.google.firebase.iid.FirebaseInstanceId.checkRequiredFirebaseOptions(com.google.firebase:firebase-iid@@21.0.0:52)
        at com.google.firebase.iid.FirebaseInstanceId.getInstance(com.google.firebase:firebase-iid@@21.0.0:2)
        at com.salesforce.androidsdk.push.SFDCRegistrationIntentService.onHandleWork**(SFDCRegistrationIntentService.java:62)**
        at androidx.core.app.JobIntentService$CommandProcessor.doInBackground(JobIntentService.java:392)
        at androidx.core.app.JobIntentService$CommandProcessor.doInBackground(JobIntentService.java:383)
        at android.os.AsyncTask$3.call(AsyncTask.java:394)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
        at java.lang.Thread.run(Thread.java:923)

**Comment by bhariharan** [comment]
@webaddicted That's not true. Your app is using `21.0.0`. Look at the stack trace you posted:
```
at com.google.firebase.iid.FirebaseInstanceId.checkRequiredFirebaseOptions(com.google.firebase:firebase-iid@@21.0.0:52)
        at com.google.firebase.iid.FirebaseInstanceId.getInstance(com.google.firebase:firebase-iid@@21.0.0:2)
```
Maybe it's being pulled in from one of your dependencies. You need to explicitly exclude the newer version using Gradle exclusion and include the correct version at the app layer. Newer versions require a `Project ID`, which is not yet supported. The fix is at the app layer.
