### ISSUE TITLE
com.salesforce.androidsdk.rest.ClientManager$AccountInfoNotFoundException: authtoken

### ISSUE THREAD

**Issue by as8703** [forcedotcom/SalesforceMobileSDK-Android#2266]
Please fill out the following details:

1. Version of Mobile SDK Used: 9.1.1
2. Issue found in Native App or Hybrid App: Native
3. OS Version: 8.1.0
4. Device: TC 25
6. Actual behavior: App crashing as we open the app
7. Expected Behavior: Should not crash
8. Error Log:
9. 
```
Fatal Exception: java.lang.RuntimeException: Unable to resume activity {app.spicejet.brs/app.spicejet.brs.ui.login.LoginActivity}: com.salesforce.androidsdk.rest.ClientManager$AccountInfoNotFoundException: authtoken
       at android.app.ActivityThread.performResumeActivity(ActivityThread.java:3584)
       at android.app.ActivityThread.handleResumeActivity(ActivityThread.java:3624)
       at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2865)
       at android.app.ActivityThread.-wrap11()
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1592)
       at android.os.Handler.dispatchMessage(Handler.java:106)
       at android.os.Looper.loop(Looper.java:164)
       at android.app.ActivityThread.main(ActivityThread.java:6518)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:438)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:807)
```

**Comment by bhariharan** [comment]
This exception is thrown when you attempt to call `peekRestClient()` without logging in. Please look at our implementation of `SalesforceActivity` to safely handle this or generate an app from one of our templates to get started.
