### ISSUE TITLE
Device id doesn't save automatically to Recipients List 

### ISSUE THREAD

**Issue by romanravkov** [forcedotcom/SalesforceMobileSDK-Android#2274]
1. Version of Mobile SDK Used: 9.2.0
2. Issue found in Native App or Hybrid App: React Native
3. OS Version: Android 11
4. Device: Samsung Galaxy S20
5. Steps to reproduce: Follow [instructions](https://developer.salesforce.com/docs/atlas.en-us.pushImplGuide.meta/pushImplGuide/pns_client_app_android.htm) to set up Push Notification for Android
6. Actual behavior: I can receive notification via Firebase and Salesforce if I fill device id manually
7. Expected Behavior: After login, the device id must be in the recipients list as on iOS app
8. Error Log:
![image](https://user-images.githubusercontent.com/46380664/151367005-efe79e4b-fe3b-4ad5-9626-ff4302343d7c.png)
![image](https://user-images.githubusercontent.com/46380664/151366150-674d01d4-2adf-4d9c-acd2-c38909738f9f.png)

**Comment by brandonpage** [comment]
@romanravkov What do you mean "the device id must be in the recipients list as on iOS app" ?

**Comment by romanravkov** [comment]
> @romanravkov What do you mean "the device id must be in the recipients list as on iOS app" ?
iOS sdk automatically saves device id after login. I didn't find any behavior description for android. How should it work on Android?

I found this logic in sdk's code, there we can see "Store the new token"
![image](https://user-images.githubusercontent.com/46380664/151493880-2f153aa7-25e4-406b-827a-784cd3e88db8.png)
But seem it doesn't work

**Comment by romanravkov** [comment]
@brandonpage I found a problem 
`Error during FCM registration
java.lang.IllegalArgumentException: Please set your project ID. A valid Firebase project ID is required to communicate with Firebase server APIs: It identifies your project with Google.
	at com.google.android.gms.common.internal.Preconditions.checkNotEmpty(Unknown Source:8)
	at com.google.firebase.iid.FirebaseInstanceId.checkRequiredFirebaseOptions(com.google.firebase:firebase-iid@@21.1.0:2)
	at com.google.firebase.iid.FirebaseInstanceId.getInstance(com.google.firebase:firebase-iid@@21.1.0:2)
	at com.salesforce.androidsdk.push.SFDCRegistrationIntentService.onHandleWork(SFDCRegistrationIntentService.java:62)
	at androidx.core.app.JobIntentService$CommandProcessor.doInBackground(JobIntentService.java:396)
	at androidx.core.app.JobIntentService$CommandProcessor.doInBackground(JobIntentService.java:387)
	at android.os.AsyncTask$3.call(AsyncTask.java:394)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
	at java.lang.Thread.run(Thread.java:923)
`

**Comment by bhariharan** [comment]
@romanravkov We don't support `Firebase 21.1.0` yet. You need to downgrade to `Firebase 20.1.0` to make this error go away.
