### ISSUE TITLE
Android native-  After auto logout salesforce login page is not opening until app is restarted

### ISSUE THREAD

**Issue by as8703** [forcedotcom/SalesforceMobileSDK-Android#2282]
Please fill out the following details:

1. Version of Mobile SDK Used: 9.2.0
2. Issue found in Native App or Hybrid App: Native
3. OS Version: 28
4. Device: TC25
5. Steps to reproduce:
6. Actual behavior: nothing happens
7. Expected Behavior: should go to login page
8. Error Log:  E/SyncTask: Exception thrown running sync
    com.salesforce.androidsdk.rest.RestClient$RefreshTokenRevokedException: Could not refresh token
        at com.salesforce.androidsdk.rest.RestClient$OAuthRefreshInterceptor.refreshAccessToken(RestClient.java:807)
        at com.salesforce.androidsdk.rest.RestClient$OAuthRefreshInterceptor.intercept(RestClient.java:698)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:121)
        at okhttp3.RealCall.getResponseWithInterceptorChain(RealCall.java:257)
        at okhttp3.RealCall.execute(RealCall.java:93)
        at com.salesforce.androidsdk.rest.RestClient.sendSync(RestClient.java:388)
        at com.salesforce.androidsdk.mobilesync.manager.SyncManager.sendSyncWithMobileSyncUserAgent(SyncManager.java:567)
        at com.salesforce.androidsdk.mobilesync.target.SoqlSyncDownTarget.startFetch(SoqlSyncDownTarget.java:159)
        at com.salesforce.androidsdk.mobilesync.target.SoqlSyncDownTarget.startFetch(SoqlSyncDownTarget.java:154)
        at com.salesforce.androidsdk.mobilesync.manager.SyncDownTask.runSync(SyncDownTask.java:55)
        at com.salesforce.androidsdk.mobilesync.manager.SyncTask.run(SyncTask.java:80)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1162)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636)
        at java.lang.Thread.run(Thread.java:764)
2022-02-24 16:48:06.596 1099-1222/app.spicejet.prs E/AILTNPublisher: Exception thrown while making network request
    com.salesforce.androidsdk.rest.RestClient$RefreshTokenRevokedException: Could not refresh token
        at com.salesforce.androidsdk.rest.RestClient$OAuthRefreshInterceptor.refreshAccessToken(RestClient.java:807)
        at com.salesforce.androidsdk.rest.RestClient$OAuthRefreshInterceptor.intercept(RestClient.java:698)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:121)
        at okhttp3.RealCall.getResponseWithInterceptorChain(RealCall.java:257)
        at okhttp3.RealCall.execute(RealCall.java:93)
        at com.salesforce.androidsdk.rest.RestClient.sendSync(RestClient.java:368)
        at com.salesforce.androidsdk.analytics.AILTNPublisher.publishLogLines(AILTNPublisher.java:135)
        at com.salesforce.androidsdk.analytics.AILTNPublisher.publish(AILTNPublisher.java:98)
        at com.salesforce.androidsdk.analytics.SalesforceAnalyticsManager.publishEvents(SalesforceAnalyticsManager.java:319)
        at com.salesforce.androidsdk.analytics.SalesforceAnalyticsManager.publishAllEvents(SalesforceAnalyticsManager.java:278)
        at com.salesforce.androidsdk.analytics.AnalyticsPublisherService.handleActionPublish(AnalyticsPublisherService.java:75)
        at com.salesforce.androidsdk.analytics.AnalyticsPublisherService.onHandleWork(AnalyticsPublisherService.java:63)
        at androidx.core.app.JobIntentService$CommandProcessor.doInBackground(JobIntentService.java:396)
        at androidx.core.app.JobIntentService$CommandProcessor.doInBackground(JobIntentService.java:387)
        at android.os.AsyncTask$2.call(AsyncTask.java:333)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1162)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636)
        at java.lang.Thread.run(Thread.java:764)

**Comment by as8703** [comment]
https://github.com/forcedotcom/SalesforceMobileSDK-Android/issues/1645  
The same issue is reported here and has not been solved yet. Is there any way we can get a callback for this error in our class?

**Comment by gkotula** [comment]
Hi as8703,

Apologies for taking so long to reply.  We have indeed seen this issue and we will definitely work on a fix for it; thanks for telling us about it!

**Comment by brandonpage** [comment]
This issue is not reproducible.  If you can provide steps or an example of this happening on version 12.0 we will happily reopen.
