### ISSUE TITLE
App crash with error: file is not a database: , while compiling: select count(*) from sqlite_master;

### ISSUE THREAD

**Issue by aileenxie977** [forcedotcom/SalesforceMobileSDK-Android#2284]
Please fill out the following details:

1. Version of Mobile SDK Used: 8.1.0
2. Issue found in Native App or Hybrid App: Hybrid App
3. OS Version: 9, 11
4. Device: Samsung A21S, Huawei Honor 7A
5. Steps to reproduce: click on app after installation
6. Actual behavior: crash
7. Expected Behavior: app opens
8. Error Log: 
Fatal Exception: java.lang.RuntimeException: Unable to start activity ComponentInfo{com.pepsico.latam.perfectstore/com.salesforce.androidsdk.phonegap.ui.SalesforceDroidGapActivity}: net.sqlcipher.database.SQLiteException: file is not a database: , while compiling: select count(*) from sqlite_master;
       at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3430)
       at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3614)
       at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:86)
       at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:108)
       at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:68)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2199)
       at android.os.Handler.dispatchMessage(Handler.java:112)
       at android.os.Looper.loop(Looper.java:216)
       at android.app.ActivityThread.main(ActivityThread.java:7625)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:524)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:987)

**Comment by aileenxie977** [comment]
This issue not happen to everyone even with the same version of device(Samsung A21S, Android 11)

**Comment by brandonpage** [comment]
Hi @aileenxie977,  

We recommend that you update to the newest version of the Mobile SDK since `8.1.0` is about two years old at this point.  A newer version of the Mobile SDK/Cordova/sqlcipher may have already solved this issue.

**Comment by aileenxie977** [comment]
@brandonpage thanks for youe timely relpy, we will try.

**Comment by riquier** [comment]
We are experiencing this exact same issue using `10.1.0` of the Mobile SDK, @aileenxie977 did you need to do anything else to resolve this?
