### ISSUE TITLE
Application not responding on the Login screen 

### ISSUE THREAD

**Issue by sidrabasit** [forcedotcom/SalesforceMobileSDK-Android#2364]
1. Version of Mobile SDK Used: 9.0.0
2. Issue found in Native App or Hybrid App: Native
3. OS Version:  Android v12
4. Device: Galaxy S21 Ultra 5G
5. Steps to reproduce: Navigate to Salesforce SDK LoginActivity 
6. Actual behavior: Login screen gets stuck 
7. Expected Behavior: Login screen should load 
8. Error Log:
main (waiting): tid=1 systid=6975 
       at jdk.internal.misc.Unsafe.park(Native method)
       at java.util.concurrent.locks.LockSupport.park(LockSupport.java:194)
       at java.util.concurrent.FutureTask.awaitDone(FutureTask.java:447)
       at java.util.concurrent.FutureTask.get(FutureTask.java:190)
       at android.os.AsyncTask.get(AsyncTask.java:618)
       at com.salesforce.androidsdk.ui.LoginActivity.onCreate(LoginActivity.java:114)
       at android.app.Activity.performCreate(Activity.java:8290)
       at android.app.Activity.performCreate(Activity.java:8270)
       at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1329)
       at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:4085)
       at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:4277)
       at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:103)
       at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
       at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2443)
       at android.os.Handler.dispatchMessage(Handler.java:106)
       at android.os.Looper.loopOnce(Looper.java:226)
       at android.os.Looper.loop(Looper.java:313)
       at android.app.ActivityThread.main(ActivityThread.java:8751)
       at java.lang.reflect.Method.invoke(Native method)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:571)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1135)

**Comment by gkotula** [comment]
Thank you for the bug report, we are looking at it 👍

**Comment by gkotula** [comment]
Hi,

Unfortunately this particular issue is something we cannot fix.  It is most likely occurring due to a network issue connecting to your Org during login, and this cannot be fixed by the SDK.
