### ISSUE TITLE
Android Flutter integration

### ISSUE THREAD

**Issue by alexlovar** [forcedotcom/SalesforceMobileSDK-Android#2377]
Hi, i try to integrate the sdk as a flutter plugin,  but i'm getting this error when run the app
Please fill out the following details:

1. Version of Mobile SDK Used: sfmc SDK 8.0.8
3. Issue found in Native App or Hybrid App: Hibrid
4. OS Version: Android 12
5. Device: Android emulator pixel 4
6. Steps to reproduce: 
7. Actual behavior: device is not registered on the sfcm server
8. Expected Behavior: get sfmc registration token
9. Error Log:
```
--------- beginning of main
--------- beginning of system
--------- beginning of crash
2023-01-13 00:53:08.825  9951-9991  KeyStore                pid-9951                             W  KeyStore exception
                                                                                                    android.os.ServiceSpecificException:  (code 7)
                                                                                                    	at android.os.Parcel.createExceptionOrNull(Parcel.java:2387)
                                                                                                    	at android.os.Parcel.createException(Parcel.java:2357)
                                                                                                    	at android.os.Parcel.readException(Parcel.java:2340)
                                                                                                    	at android.os.Parcel.readException(Parcel.java:2282)
                                                                                                    	at android.security.keystore.IKeystoreService$Stub$Proxy.get(IKeystoreService.java:988)
                                                                                                    	at android.security.KeyStore.get(KeyStore.java:233)
                                                                                                    	at android.security.KeyStore.get(KeyStore.java:222)
                                                                                                    	at android.security.keystore.AndroidKeyStoreSpi.engineGetCertificate(AndroidKeyStoreSpi.java:160)
                                                                                                    	at java.security.KeyStore.getCertificate(KeyStore.java:1120)
                                                                                                    	at com.salesforce.marketingcloud.sfmcsdk.components.encryption.KeyStoreWrapper.getPublicKey(KeyStoreWrapper.java:182)
                                                                                                    	at com.salesforce.marketingcloud.sfmcsdk.components.encryption.KeyStoreWrapper.getRSAPublicKey(KeyStoreWrapper.java:116)
                                                                                                    	at com.salesforce.marketingcloud.sfmcsdk.components.encryption.KeyStoreWrapper.getRSAPublicKey(KeyStoreWrapper.java:85)
                                                                                                    	at com.salesforce.marketingcloud.sfmcsdk.components.encryption.SalesforceKeyGenerator.generateUniqueId(SalesforceKeyGenerator.java:192)
                                                                                                    	at com.salesforce.marketingcloud.sfmcsdk.components.encryption.SalesforceKeyGenerator.getUniqueId(SalesforceKeyGenerator.java:95)
                                                                                                    	at com.salesforce.marketingcloud.sfmcsdk.components.encryption.SalesforceKeyGenerator.getUniqueId(SalesforceKeyGenerator.java:84)
                                                                                                    	at com.salesforce.marketingcloud.sfmcsdk.components.encryption.SalesforceKeyGenerator.generateEncryptionKey(SalesforceKeyGenerator.java:153)
                                                                                                    	at com.salesforce.marketingcloud.sfmcsdk.components.encryption.SalesforceKeyGenerator.getEncryptionKey(SalesforceKeyGenerator.java:110)
                                                                                                    	at com.salesforce.marketingcloud.sfmcsdk.components.encryption.EncryptionManager.<init>(EncryptionManager.kt:16)
                                                                                                    	at com.salesforce.marketingcloud.sfmcsdk.SFMCSdkComponents.<init>(SFMCSdkComponents.kt:48)
                                                                                                    	at com.salesforce.marketingcloud.sfmcsdk.SFMCSdk$Companion.configure$lambda-14$lambda-13(SFMCSdk.kt:129)
                                                                                                    	at com.salesforce.marketingcloud.sfmcsdk.SFMCSdk$Companion.$r8$lambda$LwdV5u_X536Smz_5rvQah3BxL4s(Unknown Source:0)
                                                                                                    	at com.salesforce.marketingcloud.sfmcsdk.SFMCSdk$Companion$$ExternalSyntheticLambda3.run(Unknown Source:6)
                                                                                                    	at java.lang.Thread.run(Thread.java:923)
2023-01-13 00:53:08.826  9951-9991  KeyStore                pid-9951                             W  KeyStore exception
                                                                                                    android.os.ServiceSpecificException:  (code 7)
                                                                                                    	at android.os.Parcel.createExceptionOrNull(Parcel.java:2387)
                                                                                                    	at android.os.Parcel.createException(Parcel.java:2357)
                                                                                                    	at android.os.Parcel.readException(Parcel.java:2340)
                                                                                                    	at android.os.Parcel.readException(Parcel.java:2282)
                                                                                                    	at android.security.keystore.IKeystoreService$Stub$Proxy.get(IKeystoreService.java:988)
                                                                                                    	at android.security.KeyStore.get(KeyStore.java:233)
                                                                                                    	at android.security.KeyStore.get(KeyStore.java:222)
                                                                                                    	at android.security.keystore.AndroidKeyStoreSpi.engineGetCertificate(AndroidKeyStoreSpi.java:165)
                                                                                                    	at java.security.KeyStore.getCertificate(KeyStore.java:1120)
                                                                                                    	at com.salesforce.marketingcloud.sfmcsdk.components.encryption.KeyStoreWrapper.getPublicKey(KeyStoreWrapper.java:182)
                                                                                                    	at com.salesforce.marketingcloud.sfmcsdk.components.encryption.KeyStoreWrapper.getRSAPublicKey(KeyStoreWrapper.java:116)
                                                                                                    	at com.salesforce.marketingcloud.sfmcsdk.components.encryption.KeyStoreWrapper.getRSAPublicKey(KeyStoreWrapper.java:85)
                                                                                                    	at com.salesforce.marketingcloud.sfmcsdk.components.encryption.SalesforceKeyGenerator.generateUniqueId(SalesforceKeyGenerator.java:192)
                                                                                                    	at com.salesforce.marketingcloud.sfmcsdk.components.encryption.SalesforceKeyGenerator.getUniqueId(SalesforceKeyGenerator.java:95)
                                                                                                    	at com.salesforce.marketingcloud.sfmcsdk.components.encryption.SalesforceKeyGenerator.getUniqueId(SalesforceKeyGenerator.java:84)
                                                                                                    	at com.salesforce.marketingcloud.sfmcsdk.components.encryption.SalesforceKeyGenerator.generateEncryptionKey(SalesforceKeyGenerator.java:153)
                                                                                                    	at com.salesforce.marketingcloud.sfmcsdk.components.encryption.SalesforceKeyGenerator.getEncryptionKey(SalesforceKeyGenerator.java:110)
                                                                                                    	at com.salesforce.marketingcloud.sfmcsdk.components.encryption.EncryptionManager.<init>(EncryptionManager.kt:16)
                                                                                                    	at com.salesforce.marketingcloud.sfmcsdk.SFMCSdkComponents.<init>(SFMCSdkComponents.kt:48)
                                                                                                    	at com.salesforce.marketingcloud.sfmcsdk.SFMCSdk$Companion.configure$lambda-14$lambda-13(SFMCSdk.kt:129)
                                                                                                    	at com.salesforce.marketingcloud.sfmcsdk.SFMCSdk$Companion.$r8$lambda$LwdV5u_X536Smz_5rvQah3BxL4s(Unknown Source:0)
                                                                                                    	at com.salesforce.marketingcloud.sfmcsdk.SFMCSdk$Companion$$ExternalSyntheticLambda3.run(Unknown Source:6)
                                                                                                    	at java.lang.Thread.run(Thread.java:923)
2023-01-13 00:53:08.826  9951-9991  KeyStoreWrapper         pid-9951                             E  Could not retrieve public key
                                                                                                    java.lang.NullPointerException: Attempt to invoke virtual method 'java.security.PublicKey java.security.cert.Certificate.getPublicKey()' on a null object reference
                                                                                                    	at com.salesforce.marketingcloud.sfmcsdk.components.encryption.KeyStoreWrapper.getPublicKey(KeyStoreWrapper.java:182)
                                                                                                    	at com.salesforce.marketingcloud.sfmcsdk.components.encryption.KeyStoreWrapper.getRSAPublicKey(KeyStoreWrapper.java:116)
                                                                                                    	at com.salesforce.marketingcloud.sfmcsdk.components.encryption.KeyStoreWrapper.getRSAPublicKey(KeyStoreWrapper.java:85)
                                                                                                    	at com.salesforce.marketingcloud.sfmcsdk.components.encryption.SalesforceKeyGenerator.generateUniqueId(SalesforceKeyGenerator.java:192)
                                                                                                    	at com.salesforce.marketingcloud.sfmcsdk.components.encryption.SalesforceKeyGenerator.getUniqueId(SalesforceKeyGenerator.java:95)
                                                                                                    	at com.salesforce.marketingcloud.sfmcsdk.components.encryption.SalesforceKeyGenerator.getUniqueId(SalesforceKeyGenerator.java:84)
                                                                                                    	at com.salesforce.marketingcloud.sfmcsdk.components.encryption.SalesforceKeyGenerator.generateEncryptionKey(SalesforceKeyGenerator.java:153)
                                                                                                    	at com.salesforce.marketingcloud.sfmcsdk.components.encryption.SalesforceKeyGenerator.getEncryptionKey(SalesforceKeyGenerator.java:110)
                                                                                                    	at com.salesforce.marketingcloud.sfmcsdk.components.encryption.EncryptionManager.<init>(EncryptionManager.kt:16)
                                                                                                    	at com.salesforce.marketingcloud.sfmcsdk.SFMCSdkComponents.<init>(SFMCSdkComponents.kt:48)
                                                                                                    	at com.salesforce.marketingcloud.sfmcsdk.SFMCSdk$Companion.configure$lambda-14$lambda-13(SFMCSdk.kt:129)
                                                                                                    	at com.salesforce.marketingcloud.sfmcsdk.SFMCSdk$Companion.$r8$lambda$LwdV5u_X536Smz_5rvQah3BxL4s(Unknown Source:0)
                                                                                                    	at com.salesforce.marketingcloud.sfmcsdk.SFMCSdk$Companion$$ExternalSyntheticLambda3.run(Unknown Source:6)
                                                                                                    	at java.lang.Thread.run(Thread.java:923)
2023-01-13 00:53:08.827  9951-9991  SalesforceKeyGenerator  pid-9951                             E  Exception thrown while getting encryption key
                                                                                                    java.lang.NullPointerException: Parameter specified as non-null is null: method kotlin.jvm.internal.Intrinsics.checkNotNullParameter, parameter keyValue
                                                                                                    	at com.salesforce.marketingcloud.sfmcsdk.util.FileUtilsKt.storeModuleKey(Unknown Source:12)
                                                                                                    	at com.salesforce.marketingcloud.sfmcsdk.components.encryption.SalesforceKeyGenerator.storeInNoBackupFile(SalesforceKeyGenerator.java:204)
                                                                                                    	at com.salesforce.marketingcloud.sfmcsdk.components.encryption.SalesforceKeyGenerator.generateUniqueId(SalesforceKeyGenerator.java:194)
                                                                                                    	at com.salesforce.marketingcloud.sfmcsdk.components.encryption.SalesforceKeyGenerator.getUniqueId(SalesforceKeyGenerator.java:95)
                                                                                                    	at com.salesforce.marketingcloud.sfmcsdk.components.encryption.SalesforceKeyGenerator.getUniqueId(SalesforceKeyGenerator.java:84)
                                                                                                    	at com.salesforce.marketingcloud.sfmcsdk.components.encryption.SalesforceKeyGenerator.generateEncryptionKey(SalesforceKeyGenerator.java:153)
                                                                                                    	at com.salesforce.marketingcloud.sfmcsdk.components.encryption.SalesforceKeyGenerator.getEncryptionKey(SalesforceKeyGenerator.java:110)
                                                                                                    	at com.salesforce.marketingcloud.sfmcsdk.components.encryption.EncryptionManager.<init>(EncryptionManager.kt:16)
                                                                                                    	at com.salesforce.marketingcloud.sfmcsdk.SFMCSdkComponents.<init>(SFMCSdkComponents.kt:48)
                                                                                                    	at com.salesforce.marketingcloud.sfmcsdk.SFMCSdk$Companion.configure$lambda-14$lambda-13(SFMCSdk.kt:129)
                                                                                                    	at com.salesforce.marketingcloud.sfmcsdk.SFMCSdk$Companion.$r8$lambda$LwdV5u_X536Smz_5rvQah3BxL4s(Unknown Source:0)
                                                                                                    	at com.salesforce.marketingcloud.sfmcsdk.SFMCSdk$Companion$$ExternalSyntheticLambda3.run(Unknown Source:6)
                                                                                                    	at java.lang.Thread.run(Thread.java:923)

```

**Comment by bhariharan** [comment]
`com.salesforce.marketingcloud.sfmcsdk` is a different product, i.e. `Salesforce Marketing Cloud SDK`. Please reach out to Salesforce Support for help.
