### ISSUE TITLE
SalesforceMobileSDK-Android v10.2.0 crashing on Android 11 devices

### ISSUE THREAD

**Issue by ankur-datamatics** [forcedotcom/SalesforceMobileSDK-Android#2379]
The SalesforceMobileSDK-Android v10.2.0 is crashing on Android 11 devices.

Here are the required details:

1. Version of Mobile SDK Used: 10.2.0
2. Issue found in Native App or Hybrid App: Native App
3. OS Version: Android 11
4. Device: Samsung Galaxy M52 5G
5. Steps to reproduce:
a, Open App, see a login screen;
b, Input username and password;
c, Click on Allow
6. Actual behaviour: App crashes after clicking on allow button
7. Expected Behavior: App goes to the landing screen after clicking on allow
8. Error Log: 
main (waiting):tid=1 systid=24265 
       at sun.misc.Unsafe.park(Unsafe.java)
       at java.util.concurrent.locks.LockSupport.park(LockSupport.java:190)
       at java.util.concurrent.FutureTask.awaitDone(FutureTask.java:450)
       at java.util.concurrent.FutureTask.get(FutureTask.java:192)
       at android.os.AsyncTask.get(AsyncTask.java:618)
       at com.salesforce.androidsdk.ui.LoginActivity.onCreate(LoginActivity.java:114)
       at android.app.Activity.performCreate(Activity.java:8363)
       at android.app.Activity.performCreate(Activity.java:8341)
       at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1329)
       at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3894)
       at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:4078)
       at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:103)
       at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
       at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2423)
       at android.os.Handler.dispatchMessage(Handler.java:106)
       at android.os.Looper.loopOnce(Looper.java:233)
       at android.os.Looper.loop(Looper.java:334)
       at android.app.ActivityThread.main(ActivityThread.java:8348)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:582)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1065)

**Comment by ankur-datamatics** [comment]
Hi @brandonpage ,
We are using the native SalesforceMobileSDK-Android solely for the purpose of login into our Android App and facing some issues with v10.2.0 of the SDK.

Upon further inspection, it has been observed that SalesforceMobileSDK-Android v10.2.0 is crashing on multiple occasions for multiple users(ranging from Android 9 to Android 13).

PFA the logs for the same procured from Firebase Crashlytics.
[SFDC_CRASH_LOGS.txt](https://github.com/forcedotcom/SalesforceMobileSDK-Android/files/10534243/SFDC_CRASH_LOGS.txt)

**Comment by ankur-datamatics** [comment]
Hi @brandonpage, we are still facing the crash issue on the official Android Versions. The majority of crashes are happening in All the Oppo, Vivo and Oneplus OEM devices having Android versions 11-13. 
Here is the list of devices:- 

MOTO G60 | 12
ONE PLUS | 11
Oppo Reno 5 pro  | 12
Vivo S1 pro | 12
POCO X3 | 13
Samsung A53 | 13
Vivo T1 5G | 12
Vivo Y33T | 12
ONE PLUS 9R | 13

Also, so far we have not encountered any crashes on Samsung and Xiaomi devices.

**Comment by jayaprakash** [comment]
I have come across similar issue. And it's because of pin pattern enabled on the app(connected app). Disabling pin was a temporary workaround.
<img width="687" alt="Screenshot 2023-02-10 at 2 07 41 PM" src="https://user-images.githubusercontent.com/108242/218043522-d4e02e92-077e-423c-9b22-c8579bd93491.png">

**Comment by ankur-datamatics** [comment]
@jayaprakash Thanks for the reply but this is already unchecked in our case.

**Comment by JohnsonEricAtSalesforce** [comment]
For status, this issue is being researched.  Stay tuned for more details and feel free to share any additional technical details.  Thanks!

**Comment by gkotula** [comment]
Hi @ankur-datamatics and to others who are monitoring this conversation, we posted some more thorough debugging steps on the thread on Salesforce Trailhead: https://trailhead.salesforce.com/trailblazer-community/feed/0D54S00000JfyGYSAZ .

**Comment by ankur-datamatics** [comment]
Hi @gkotula,
We are looking into this and will provide an update as soon as possible.

**Comment by wmathurin** [comment]
Closing the issue for lack of updates from the customer. Please re-open an issue or post to the trailblazer community if you are still having problems.

**Comment by AnuragTiwari1** [comment]
Hi @wmathurin, 

we are facing this issue on few devices for SDK 10.2.0.
devices and version info:
OEM and device: MI POCO F1
OS: Android 10 and Android 12
SDK version: 10.2.0
react native version: 0.70.10

What is happening: 
After pressing on Allow button in web view, App is getting backgrounded and when we tried to open the app from app switcher it shows the login page again. when open again by pressing app icon it works as expected and user is logged in.

Please suggest a fix or workaround as it is critical for us.
