### ISSUE TITLE
App crash after opening on android 14

### ISSUE THREAD

**Issue by roshanmtx** [forcedotcom/SalesforceMobileSDK-Android#2497]
Please fill out the following details:

1. Version of Mobile SDK Used: 11.1.0
2. Issue found in Native App or Hybrid App: React native
3. OS Version: 14
4. Device: google pixel
5. Steps to reproduce: App crashes on launch
6. Actual behavior: crash
7. Expected Behavior: app should run normally
8. Error Log:

FATAL EXCEPTION: main
                                                                                                    Process: com.apmtx.mobile, PID: 5808
                                                                                                    java.lang.RuntimeException: Unable to start activity ComponentInfo{com.apmtx.mobile/com.apmtx.mobile.MainActivity}: java.lang.RuntimeException: Requested enabled DevSupportManager, but BridgeDevSupportManager class was not found or could not be created
                                                                                                    	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3782)
                                                                                                    	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3922)
                                                                                                    	at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:103)
                                                                                                    	at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:139)
                                                                                                    	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:96)
                                                                                                    	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2443)
                                                                                                    	at android.os.Handler.dispatchMessage(Handler.java:106)
                                                                                                    	at android.os.Looper.loopOnce(Looper.java:205)
                                                                                                    	at android.os.Looper.loop(Looper.java:294)
                                                                                                    	at android.app.ActivityThread.main(ActivityThread.java:8177)
                                                                                                    	at java.lang.reflect.Method.invoke(Native Method)
                                                                                                    	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:552)
                                                                                                    	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:971)
                                                                                                    Caused by: java.lang.RuntimeException: Requested enabled DevSupportManager, but BridgeDevSupportManager class was not found or could not be created
                                                                                                    	at com.facebook.react.devsupport.DefaultDevSupportManagerFactory.create(DefaultDevSupportManagerFactory.java:97)
                                                                                                    	at com.facebook.react.ReactInstanceManager.<init>(ReactInstanceManager.java:257)
                                                                                                    	at com.facebook.react.ReactInstanceManagerBuilder.build(ReactInstanceManagerBuilder.java:357)
                                                                                                    	at com.facebook.react.ReactNativeHost.createReactInstanceManager(ReactNativeHost.java:96)
                                                                                                    	at com.facebook.react.ReactNativeHost.getReactInstanceManager(ReactNativeHost.java:42)
                                                                                                    	at com.salesforce.androidsdk.reactnative.ui.SalesforceReactActivity.shouldAskOverlayPermission(SalesforceReactActivity.java:277)
                                                                                                    	at com.salesforce.androidsdk.reactnative.ui.SalesforceReactActivity.shouldReactBeRunning(SalesforceReactActivity.java:266)
                                                                                                    	at com.salesforce.androidsdk.reactnative.ui.SalesforceReactActivityDelegate.loadReactAppOnceIfReady(SalesforceReactActivityDelegate.java:55)
                                                                                                    	at com.salesforce.androidsdk.reactnative.ui.SalesforceReactActivityDelegate.loadApp(SalesforceReactActivityDelegate.java:46)
                                                                                                    	at com.facebook.react.ReactActivityDelegate.onCreate(ReactActivityDelegate.java:106)
                                                                                                    	at com.facebook.react.ReactActivity.onCreate(ReactActivity.java:46)
                                                                                                    	at com.salesforce.androidsdk.reactnative.ui.SalesforceReactActivity.onCreate(SalesforceReactActivity.java:88)
                                                                                                    	at com.apmtx.mobile.MainActivity.onCreate(MainActivity.java:58)
                                                                                                    	at android.app.Activity.performCreate(Activity.java:8595)
                                                                                                    	at android.app.Activity.performCreate(Activity.java:8573)
                                                                                                    	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1456)
                                                                                                    	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3764)
                                                                                                    	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3922) 
                                                                                                    	at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:103) 
                                                                                                    	at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:139) 
                                                                                                    	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:96) 
                                                                                                    	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2443) 
                                                                                                    	at android.os.Handler.dispatchMessage(Handler.java:106) 
                                                                                                    	at android.os.Looper.loopOnce(Looper.java:205) 
                                                                                                    	at android.os.Looper.loop(Looper.java:294) 
                                                                                                    	at android.app.ActivityThread.main(ActivityThread.java:8177) 
                                                                                                    	at java.lang.reflect.Method.invoke(Native Method) 
                                                                                                    	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:552) 
                                                                                                    	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:971) 
                                                                                                    Caused by: java.lang.reflect.InvocationTargetException
                                                                                                    	at java.lang.reflect.Constructor.newInstance0(Native Method)
                                                                                                    	at java.lang.reflect.Constructor.newInstance(Constructor.java:343)
                                                                                                    	at com.facebook.react.devsupport.DefaultDevSupportManagerFactory.create(DefaultDevSupportManagerFactory.java:86)
                                                                                                    	at com.facebook.react.ReactInstanceManager.<init>(ReactInstanceManager.java:257) 
                                                                                                    	at com.facebook.react.ReactInstanceManagerBuilder.build(ReactInstanceManagerBuilder.java:357) 
                                                                                                    	at com.facebook.react.ReactNativeHost.createReactInstanceManager(ReactNativeHost.java:96) 
                                                                                                    	at com.facebook.react.ReactNativeHost.getReactInstanceManager(ReactNativeHost.java:42) 
                                                                                                    	at com.salesforce.androidsdk.reactnative.ui.SalesforceReactActivity.shouldAskOverlayPermission(SalesforceReactActivity.java:277) 
                                                                                                    	at com.salesforce.androidsdk.reactnative.ui.SalesforceReactActivity.shouldReactBeRunning(SalesforceReactActivity.java:266) 
                                                                                                    	at com.salesforce.androidsdk.reactnative.ui.SalesforceReactActivityDelegate.loadReactAppOnceIfReady(SalesforceReactActivityDelegate.java:55) 
                                                                                                    	at com.salesforce.androidsdk.reactnative.ui.SalesforceReactActivityDelegate.loadApp(SalesforceReactActivityDelegate.java:46) 
                                                                                                    	at com.facebook.react.ReactActivityDelegate.onCreate(ReactActivityDelegate.java:106) 
                                                                                                    	at com.facebook.react.ReactActivity.onCreate(ReactActivity.java:46) 
                                                                                                    	at com.salesforce.androidsdk.reactnative.ui.SalesforceReactActivity.onCreate(SalesforceReactActivity.java:88) 
                                                                                                    	at com.apmtx.mobile.MainActivity.onCreate(MainActivity.java:58) 
                                                                                                    	at android.app.Activity.performCreate(Activity.java:8595) 
                                                                                                    	at android.app.Activity.performCreate(Activity.java:8573) 
                                                                                                    	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1456) 
                                                                                                    	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3764) 
                                                                                                    	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3922) 
                                                                                                    	at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:103) 
                                                                                                    	at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:139) 
                                                                                                    	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:96) 
                                                                                                    	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2443) 
                                                                                                    	at android.os.Handler.dispatchMessage(Handler.java:106) 
                                                                                                    	at android.os.Looper.loopOnce(Looper.java:205) 
                                                                                                    	at android.os.Looper.loop(Looper.java:294) 
                                                                                                    	at android.app.ActivityThread.main(ActivityThread.java:8177) 
                                                                                                    	at java.lang.reflect.Method.invoke(Native Method) 
                                                                                                    	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:552) 
                                                                                                    	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:971) 
                                                                                                    Caused by: java.lang.SecurityException: com.apmtx.mobile: One of RECEIVER_EXPORTED or RECEIVER_NOT_EXPORTED should be specified when a receiver isn't being registered exclusively for system broadcasts
                                                                                                    	at android.os.Parcel.createExceptionOrNull(Parcel.java:3057)
                                                                                                    	at android.os.Parcel.createException(Parcel.java:3041)
                                                                                                    	at android.os.Parcel.readException(Parcel.java:3024)
                                                                                                    	at android.os.Parcel.readException(Parcel.java:2966)
                                                                                                    	at android.app.IActivityManager$Stub$Proxy.registerReceiverWithFeature(IActivityManager.java:5684)
                                                                                                    	at android.app.ContextImpl.registerReceiverInternal(ContextImpl.java:1852)
                                                                                                    	at android.app.ContextImpl.registerReceiver(ContextImpl.java:1792)
2023-11-30 14:35:04.248  5808-5808  AndroidRuntime          com.apmtx.mobile                     E  	at android.app.ContextImpl.registerReceiver(ContextImpl.java:1780)
                                                                                                    	at android.content.ContextWrapper.registerReceiver(ContextWrapper.java:755)
                                                                                                    	at com.facebook.react.devsupport.DevSupportManagerBase.reload(DevSupportManagerBase.java:1101)
                                                                                                    	at com.facebook.react.devsupport.DevSupportManagerBase.reloadSettings(DevSupportManagerBase.java:721)
                                                                                                    	at com.facebook.react.devsupport.DevSupportManagerBase.setDevSupportEnabled(DevSupportManagerBase.java:593)
                                                                                                    	at com.facebook.react.devsupport.DevSupportManagerBase.<init>(DevSupportManagerBase.java:206)
                                                                                                    	at com.facebook.react.devsupport.BridgeDevSupportManager.<init>(BridgeDevSupportManager.java:78)
                                                                                                    	... 31 more
                                                                                                    Caused by: android.os.RemoteException: Remote stack trace:
                                                                                                    	at com.android.server.am.ActivityManagerService.registerReceiverWithFeature(ActivityManagerService.java:13927)
                                                                                                    	at android.app.IActivityManager$Stub.onTransact(IActivityManager.java:2570)
                                                                                                    	at com.android.server.am.ActivityManagerService.onTransact(ActivityManagerService.java:2720)
                                                                                                    	at android.os.Binder.execTransactInternal(Binder.java:1339)
                                                                                                    	at android.os.Binder.execTransact(Binder.java:1275)

**Comment by wmathurin** [comment]
What Android API are you targeting?
It should work if you target 33 (Android 13). 
React Native 0.70.14 does not support targeting 34 (Android 14) - see https://github.com/facebook/react-native/issues/41288.

NB: We are planning to support the latest React Native in our next version of Mobile SDK (12.0).

**Comment by roshanmtx** [comment]
Yes I am targeting for Android 14

@wmathurin when we can expect next version (any approx. timeline)

**Comment by wmathurin** [comment]
Early 2024.

**Comment by roshanmtx** [comment]
@wmathurin This is getting critical for out client, can you please share approx. time (in Jan or Feb 2024).

**Comment by wmathurin** [comment]
More like Spring 2024. Do they need to target 34. You can target 33 and run on 34.

**Comment by roshanmtx** [comment]
@wmathurin any update on new release ?

**Comment by wmathurin** [comment]
Still shooting for Spring (April or May).

**Comment by va1bhav** [comment]
@wmathurin Is this part of SDK v12? 
cc : @bbirman

**Comment by wmathurin** [comment]
Yes
