### ISSUE TITLE
Salesforce not compatible with gradlew 8.3.2

### ISSUE THREAD

**Issue by johnjeremih** [forcedotcom/SalesforceMobileSDK-Android#2554]
I was wondering when this repository will support 8.3.2. Currently I'm having this error.

`getBuildConfigValue failed 
                                                                                                    java.lang.ClassNotFoundException: com.native.nativeandroid.BuildConfig
                                                                                                    	at java.lang.Class.classForName(Native Method)
                                                                                                    	at java.lang.Class.forName(Class.java:454)
                                                                                                    	at java.lang.Class.forName(Class.java:379)
                                                                                                    	at com.salesforce.androidsdk.app.e.F(SourceFile:1)
                                                                                                    	at com.salesforce.androidsdk.app.e.k0(SourceFile:1)
                                                                                                    	at com.salesforce.androidsdk.app.e.l0(SourceFile:1)
                                                                                                    	at com.salesforce.androidsdk.app.e.K0(SourceFile:1)
                                                                                                    	at com.salesforce.androidsdk.app.e.g0(SourceFile:1)
                                                                                                    	at com.salesforce.androidsdk.app.e.f0(SourceFile:1)
                                                                                                    	at com.salesforce.androidsdk.app.e.h0(SourceFile:1)
                                                                                                    	at com.native.nativeandroid.NativeApplication.onCreate(Unknown Source:16)
                                                                                                    	at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1277)
                                                                                                    	at android.app.ActivityThread.handleBindApplication(ActivityThread.java:6759)
                                                                                                    	at android.app.ActivityThread.-$$Nest$mhandleBindApplication(Unknown Source:0)
                                                                                                    	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2133)
                                                                                                    	at android.os.Handler.dispatchMessage(Handler.java:106)
                                                                                                    	at android.os.Looper.loopOnce(Looper.java:201)
                                                                                                    	at android.os.Looper.loop(Looper.java:288)
                                                                                                    	at android.app.ActivityThread.main(ActivityThread.java:7872)
                                                                                                    	at java.lang.reflect.Method.invoke(Native Method)
                                                                                                    	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
                                                                                                    	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:936)
                                                                                                    Caused by: java.lang.ClassNotFoundException: com.native.nativeandroid.BuildConfig`

`Exception thrown while instantiating class
                                                                                                    java.lang.InstantiationException: java.lang.Class<m6.a> cannot be instantiated
                                                                                                    	at java.lang.Class.newInstance(Native Method)
                                                                                                    	at com.salesforce.androidsdk.analytics.a.g(SourceFile:1)
                                                                                                    	at com.salesforce.androidsdk.analytics.a.f(SourceFile:1)
                                                                                                    	at com.salesforce.androidsdk.analytics.AnalyticsPublishingWorker.p(SourceFile:1)
                                                                                                    	at androidx.work.Worker$a.run(Unknown Source:2)`

`Work [ id=e5be6a56-030f-406a-90e7-ce8d786a85a7, tags={ com.salesforce.androidsdk.push.PushNotificationsRegistrationChangeWorker } ] failed because it threw an exception/error (Ask Gemini)
                                                                                                    java.util.concurrent.ExecutionException: java.lang.InstantiationException: java.lang.Class<t6.e> cannot be instantiated
                                                                                                    	at androidx.work.impl.utils.futures.a.i(SourceFile:1)
                                                                                                    	at androidx.work.impl.utils.futures.a.get(SourceFile:1)
                                                                                                    	at androidx.work.impl.K$b.run(Unknown Source:4)
                                                                                                    	at D0.s$a.run(SourceFile:3)
                                                                                                    	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1137)
                                                                                                    	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:637)
                                                                                                    	at java.lang.Thread.run(Thread.java:1012)
                                                                                                    Caused by: java.lang.InstantiationException: java.lang.Class<t6.e> cannot be instantiated
                                                                                                    	at java.lang.Class.newInstance(Native Method)
                                                                                                    	at com.salesforce.androidsdk.push.PushNotificationsRegistrationChangeWorker.p(SourceFile:1)
                                                                                                    	at androidx.work.Worker$a.run(Unknown Source:2)
                                                                                                    	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1137) 
                                                                                                    	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:637) 
                                                                                                    	at java.lang.Thread.run(Thread.java:1012) `

**Comment by wmathurin** [comment]
8.3.2 of what library?

Also could you try again with the latest version of Mobile SDK (12.0) that we just released?

**Comment by brandonpage** [comment]
@johnjeremih I believe you mean **Gradle** 8.3.2, correct?  We upgraded Gradle to `8.2` in Mobile SDK 12.0 please try that and let us know if the issue persists.

**Comment by johnjeremih** [comment]
What kotlin_version do you guys have?

**Comment by brandonpage** [comment]
We are compiling with Kotlin `1.9.20`, however ([as you can see here](https://github.com/forcedotcom/SalesforceMobileSDK-Android/blob/3a2a95fa7e2d1c375edd2a5f6e06e971728d7920/build.gradle.kts#L22)) we are backwards compatible to Kotlin `1.6`.

**Comment by johnjeremih** [comment]
@brandonpage @wmathurin I still get the same errors. I believe it is related to R8 because it works fine when I run it with a debug build, but when I set it to release with **minifyEnabled** true and **shrinkResources** true. Then it crashes.

**Comment by johnjeremih** [comment]
I found out what the real issue was. here it is https://github.com/forcedotcom/SalesforceMobileSDK-Android/issues/2558
