### ISSUE TITLE
Push notification un-registration failed RefreshTokenRevokedException: Could not refresh token

### ISSUE THREAD

**Issue by johnjeremih** [forcedotcom/SalesforceMobileSDK-Android#2599]
Please fill out the following details:

1. Version of Mobile SDK Used:   12.0.0
2. Issue found in Native App or Hybrid App: native
3. OS Version: v34
4. Device: Pixel 8 Pro
5. Steps to reproduce: After login out, I'm getting this error 
![image](https://github.com/user-attachments/assets/c540744e-273c-41f3-8254-08dc965e249d)

6. Actual behavior:
7. Expected Behavior:
8. Error Log:
```
Push notification un-registration failed
                                                                                                    com.salesforce.androidsdk.rest.RestClient$RefreshTokenRevokedException: Could not refresh token
                                                                                                    	at com.salesforce.androidsdk.rest.RestClient$c.a(Unknown Source:151)
                                                                                                    	at com.salesforce.androidsdk.rest.RestClient$c.intercept(Unknown Source:97)
                                                                                                    	at bj.g.a(Unknown Source:125)
                                                                                                    	at com.salesforce.androidsdk.rest.RestClient$c.intercept(Unknown Source:20)
                                                                                                    	at bj.g.a(Unknown Source:125)
                                                                                                    	at com.salesforce.androidsdk.rest.RestClient$c.intercept(Unknown Source:20)
                                                                                                    	at bj.g.a(Unknown Source:125)
                                                                                                    	at aj.g.h(Unknown Source:100)
                                                                                                    	at aj.g.f(Unknown Source:41)
                                                                                                    	at com.salesforce.androidsdk.rest.RestClient.b(Unknown Source:187)
                                                                                                    	at com.salesforce.androidsdk.push.b.c(Unknown Source:50)
                                                                                                    	at com.salesforce.androidsdk.push.b.d(Unknown Source:147)
                                                                                                    	at com.salesforce.androidsdk.push.PushNotificationsRegistrationChangeWorker.f(Unknown Source:429)
                                                                                                    	at androidx.work.e.run(Unknown Source:2)
                                                                                                    	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
                                                                                                    	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:644)
                                                                                                    	at java.lang.Thread.run(Thread.java:1012)
```

**Comment by johnjeremih** [comment]
Nevermind, I wasn't registering the push notifications in the first place
