### ISSUE TITLE
Unable to build with Android targetSdkVersion above 34.

### ISSUE THREAD

**Issue by ryukooo** [forcedotcom/SalesforceMobileSDK-Android#2601]
Please fill out the following details:

To update your Android application after 31/08/2024 from Google Play,
We are working on the targetSdkVersion, which needs to be 34 or higher.
https://support.google.com/googleplay/android-developer/answer/11926878

SalesforceSDK error during build.
Can you please check if the SDK also needs to be supported?

Alternatively, please let us know how to deal with this.
I believe the following is a similar issue.
#2497

Thank you very much.

Version of Mobile SDK Used: 11.1.0
Issue found in Native App or Hybrid App: Native App
OS Version: 14
Device: google pixel
Steps to reproduce: App crashes on launch
Actual behavior: crash
Expected Behavior: app should run normally
Error Log:

FATAL EXCEPTION: main
                                                                                                    Process: yyyy, PID: 2338
                                                                                                    java.lang.RuntimeException: Unable to create application xxx: java.lang.SecurityException: yyyy: One of RECEIVER_EXPORTED or RECEIVER_NOT_EXPORTED should be specified when a receiver isn't being registered exclusively for system broadcasts
                                                                                                    	at android.app.ActivityThread.handleBindApplication(ActivityThread.java:7003)
                                                                                                    	at android.app.ActivityThread.-$$Nest$mhandleBindApplication(Unknown Source:0)
                                                                                                    	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2236)
                                                                                                    	at android.os.Handler.dispatchMessage(Handler.java:106)
                                                                                                    	at android.os.Looper.loopOnce(Looper.java:205)
                                                                                                    	at android.os.Looper.loop(Looper.java:294)
                                                                                                    	at android.app.ActivityThread.main(ActivityThread.java:8177)
                                                                                                    	at java.lang.reflect.Method.invoke(Native Method)
                                                                                                    	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:552)
                                                                                                    	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:971)
                                                                                                    Caused by: java.lang.SecurityException: yyyy: One of RECEIVER_EXPORTED or RECEIVER_NOT_EXPORTED should be specified when a receiver isn't being registered exclusively for system broadcasts
                                                                                                    	at android.os.Parcel.createExceptionOrNull(Parcel.java:3057)
                                                                                                    	at android.os.Parcel.createException(Parcel.java:3041)
                                                                                                    	at android.os.Parcel.readException(Parcel.java:3024)
                                                                                                    	at android.os.Parcel.readException(Parcel.java:2966)
                                                                                                    	at android.app.IActivityManager$Stub$Proxy.registerReceiverWithFeature(IActivityManager.java:5684)
                                                                                                    	at android.app.ContextImpl.registerReceiverInternal(ContextImpl.java:1852)
                                                                                                    	at android.app.ContextImpl.registerReceiver(ContextImpl.java:1792)
                                                                                                    	at android.app.ContextImpl.registerReceiver(ContextImpl.java:1780)
                                                                                                    	at android.content.ContextWrapper.registerReceiver(ContextWrapper.java:755)
                                                                                                    	at com.salesforce.androidsdk.app.SalesforceSDKManager.<init>(SalesforceSDKManager.java:295)
                                                                                                    	at com.salesforce.androidsdk.app.SalesforceSDKManager.init(SalesforceSDKManager.java:377)
                                                                                                    	at com.salesforce.androidsdk.app.SalesforceSDKManager.initNative(SalesforceSDKManager.java:413)
                                                                                                    	at xxx.onCreate(MainApplication.kt:24)
                                                                                                    	at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1316)
                                                                                                    	at android.app.ActivityThread.handleBindApplication(ActivityThread.java:6998)
                                                                                                    	at android.app.ActivityThread.-$$Nest$mhandleBindApplication(Unknown Source:0) 
                                                                                                    	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2236) 
                                                                                                    	at android.os.Handler.dispatchMessage(Handler.java:106) 
                                                                                                    	at android.os.Looper.loopOnce(Looper.java:205) 
                                                                                                    	at android.os.Looper.loop(Looper.java:294) 
                                                                                                    	at android.app.ActivityThread.main(ActivityThread.java:8177) 
                                                                                                    	at java.lang.reflect.Method.invoke(Native Method) 
                                                                                                    	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:552) 
                                                                                                    	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:971) 
                                                                                                    Caused by: android.os.RemoteException: Remote stack trace:
                                                                                                    	at com.android.server.am.ActivityManagerService.registerReceiverWithFeature(ActivityManagerService.java:13927)
                                                                                                    	at android.app.IActivityManager$Stub.onTransact(IActivityManager.java:2570)
                                                                                                    	at com.android.server.am.ActivityManagerService.onTransact(ActivityManagerService.java:2720)
                                                                                                    	at android.os.Binder.execTransactInternal(Binder.java:1339)
                                                                                                    	at android.os.Binder.execTransact(Binder.java:1275)339)
                                                                                                    	at android.os.Binder.execTransact(Binder.java:1275)

**Comment by brandonpage** [comment]
Hi @ryukooo I assure you this issue was fixed in Mobile SDK 11.1. The only exception (that you see in your linked issue) is for React Native consumers because we held the necessary RN library upgrade until 12.0 due to a breaking change.  

Are you sure you are using 11.1?  The line numbers from SalesforceSDKManager in you stacktrace appear to match `11.0.1` not `11.1.0`.

**Comment by ryukooo** [comment]
@brandonpage  Thank you.
Sorry, I am using 11.0.1.
I will try 11.1.0.

**Comment by ryukooo** [comment]
Build was possible.
Thank you very much.
