### ISSUE TITLE
App Crash with InflateException in ActionMenuItemView

### ISSUE THREAD

**Issue by clea-smudge** [forcedotcom/SalesforceMobileSDK-Android#2612]
Please fill out the following details:

1. Version of Mobile SDK Used: 11.1.0
2. Issue found in Native App or Hybrid App: Native
3. OS Version: 34
4. Device: Pixel 8 Pro
5. Steps to reproduce: 

- Log in to the app.
- Enter the PIN for the app lock.
- The app crashes after entering the PIN, then immediately displays the app lock screen again, prompting for the PIN once more. This process repeats in a loop (entering PIN -> crash -> enter PIN again).
Note: The login seems to succeed, as I can see ClientInfo. I also have this in the code: SalesforceReactSDKManager.getInstance().setUseWebServerAuthentication(false)

6. Actual behavior: Crashing due to an InflateException
7. Expected Behavior: Not crash
8. Error Log:

```
FATAL EXCEPTION: main
                 Process: {package_name}, PID: 11043
                 android.view.InflateException: Binary XML file line #30 in {package_name}:layout/abc_action_menu_item_layout: Binary XML file line #30 in {package_name}:layout/abc_action_menu_item_layout: Error inflating class androidx.appcompat.view.menu.ActionMenuItemView
                 Caused by: android.view.InflateException: Binary XML file line #30 in {package_name}:layout/abc_action_menu_item_layout: Error inflating class androidx.appcompat.view.menu.ActionMenuItemView
                 Caused by: java.lang.reflect.InvocationTargetException
                 	at java.lang.reflect.Constructor.newInstance0(Native Method)
                 	at java.lang.reflect.Constructor.newInstance(Constructor.java:343)
                 	at android.view.LayoutInflater.createView(LayoutInflater.java:866)
                 	at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:1018)
                 	at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:973)
                 	at android.view.LayoutInflater.inflate(LayoutInflater.java:667)
                 	at android.view.LayoutInflater.inflate(LayoutInflater.java:538)
                 	at androidx.appcompat.view.menu.BaseMenuPresenter.createItemView(BaseMenuPresenter.java:166)
                 	at androidx.appcompat.view.menu.BaseMenuPresenter.getItemView(BaseMenuPresenter.java:185)
                 	at androidx.appcompat.widget.ActionMenuPresenter.getItemView(ActionMenuPresenter.java:193)
                 	at androidx.appcompat.widget.ActionMenuPresenter.flagActionItems(ActionMenuPresenter.java:469)
                 	at androidx.appcompat.view.menu.MenuBuilder.flagActionItems(MenuBuilder.java:1179)
                 	at androidx.appcompat.view.menu.BaseMenuPresenter.updateMenuView(BaseMenuPresenter.java:95)
                 	at androidx.appcompat.widget.ActionMenuPresenter.updateMenuView(ActionMenuPresenter.java:226)
                 	at androidx.appcompat.view.menu.MenuBuilder.dispatchPresenterUpdate(MenuBuilder.java:289)
                 	at androidx.appcompat.view.menu.MenuBuilder.onItemsChanged(MenuBuilder.java:1062)
                 	at androidx.appcompat.view.menu.MenuBuilder.startDispatchingItemsChanged(MenuBuilder.java:1093)
                 	at androidx.appcompat.app.AppCompatDelegateImpl.preparePanel(AppCompatDelegateImpl.java:2045)
                 	at androidx.appcompat.app.AppCompatDelegateImpl.doInvalidatePanelMenu(AppCompatDelegateImpl.java:2289)
                 	at androidx.appcompat.app.AppCompatDelegateImpl$2.run(AppCompatDelegateImpl.java:275)
                 	at android.os.Handler.handleCallback(Handler.java:958)
                 	at android.os.Handler.dispatchMessage(Handler.java:99)
                 	at android.os.Looper.loopOnce(Looper.java:205)
                 	at android.os.Looper.loop(Looper.java:294)
                 	at android.app.ActivityThread.main(ActivityThread.java:8177)
                 	at java.lang.reflect.Method.invoke(Native Method)
                 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:552)
                 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:971)
                 Caused by: java.lang.UnsupportedOperationException: Failed to resolve attribute at index 5: TypedValue{t=0x2/d=0x7f040011 a=-1}, theme={InheritanceMap=[id=0x7f12015c{package_name}:style/SalesforceChildren], Themes=[{package_name}:style/SalesforceChildren, forced, {package_name}:style/Theme.AppCompat.Empty, forced, android:style/Theme.DeviceDefault.Light.DarkActionBar, forced]}
                 	at android.content.res.TypedArray.getColorStateList(TypedArray.java:600)
                 	at android.widget.TextView.readTextAppearance(TextView.java:4251)
                 	at android.widget.TextView.<init>(TextView.java:1249)
                 	at android.widget.TextView.<init>(TextView.java:1149)
                 	at androidx.appcompat.widget.AppCompatTextView.<init>(AppCompatTextView.java:115)
                 	at androidx.appcompat.view.menu.ActionMenuItemView.<init>(ActionMenuItemView.java:71)
                 	at androidx.appcompat.view.menu.ActionMenuItemView.<init>(ActionMenuItemView.java:67)
                 	at java.lang.reflect.Constructor.newInstance0(Native Method) 
                 	at java.lang.reflect.Constructor.newInstance(Constructor.java:343) 
                 	at android.view.LayoutInflater.createView(LayoutInflater.java:866) 
                 	at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:1018) 
                 	at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:973) 
                 	at android.view.LayoutInflater.inflate(LayoutInflater.java:667) 
                 	at android.view.LayoutInflater.inflate(LayoutInflater.java:538) 
                 	at androidx.appcompat.view.menu.BaseMenuPresenter.createItemView(BaseMenuPresenter.java:166) 
                 	at androidx.appcompat.view.menu.BaseMenuPresenter.getItemView(BaseMenuPresenter.java:185) 
                 	at androidx.appcompat.widget.ActionMenuPresenter.getItemView(ActionMenuPresenter.java:193) 
                 	at androidx.appcompat.widget.ActionMenuPresenter.flagActionItems(ActionMenuPresenter.java:469) 
                 	at androidx.appcompat.view.menu.MenuBuilder.flagActionItems(MenuBuilder.java:1179) 
                 	at androidx.appcompat.view.menu.BaseMenuPresenter.updateMenuView(BaseMenuPresenter.java:95) 
                 	at androidx.appcompat.widget.ActionMenuPresenter.updateMenuView(ActionMenuPresenter.java:226) 
                 	at androidx.appcompat.view.menu.MenuBuilder.dispatchPresenterUpdate(MenuBuilder.java:289) 
                 	at androidx.appcompat.view.menu.MenuBuilder.onItemsChanged(MenuBuilder.java:1062) 
                 	at androidx.appcompat.view.menu.MenuBuilder.startDispatchingItemsChanged(MenuBuilder.java:1093) 
                 	at androidx.appcompat.app.AppCompatDelegateImpl.preparePanel(AppCompatDelegateImpl.java:2045) 
                 	at androidx.appcompat.app.AppCompatDelegateImpl.doInvalidatePanelMenu(AppCompatDelegateImpl.java:2289) 
                 	at androidx.appcompat.app.AppCompatDelegateImpl$2.run(AppCompatDelegateImpl.java:275) 
                 	at android.os.Handler.handleCallback(Handler.java:958) 
                 	at android.os.Handler.dispatchMessage(Handler.java:99) 
                 	at android.os.Looper.loopOnce(Looper.java:205) 
                 	at android.os.Looper.loop(Looper.java:294) 
                 	at android.app.ActivityThread.main(ActivityThread.java:8177) 
                 	at java.lang.reflect.Method.invoke(Native Method) 
                 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:552) 
                 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:971) 

```

It appears that the crash is caused by an issue in the SDK while inflating a specific view (ActionMenuItemView). Could you please review the issue and provide guidance on how we can resolve this? If you need any additional information, feel free to reach out. Thank you for your support!

**Comment by clea-smudge** [comment]
I found the issue. For anyone who encounters this in the future, the problem was that my MainActivity theme was still set to `@style/SalesforceChildren` in the AndroidManifest.xml file, which caused the crash. Changing the theme to `@style/SalesforceSDK` resolved the issue.
