### ISSUE TITLE
Could not refresh token

### ISSUE THREAD

**Issue by johnjeremih** [forcedotcom/SalesforceMobileSDK-Android#2623]
Please fill out the following details:

1. Version of Mobile SDK Used: 12.0.0
2. Issue found in Native App or Hybrid App: native
3. OS Version: 34
4. Device: Pixel 8 Pro
5. Steps to reproduce: trying to log out with this function.
![image](https://github.com/user-attachments/assets/53f16b0f-7bfc-43e8-bd02-0429e723f4ab)
6. Error Log:

```
2024-09-27 17:16:51.505 16714-16773 OpenGLRenderer          com...demo.nativeandroid.uat  E  Unable to match the desired swap behavior.
2024-09-27 17:16:55.595 16714-16954 PushService             com...demo.nativeandroid.uat  E  Push notification un-registration failed (Ask Gemini)
                                                                                                    com.salesforce.androidsdk.rest.RestClient$RefreshTokenRevokedException: Could not refresh token
                                                                                                    	at com.salesforce.androidsdk.rest.RestClient$OAuthRefreshInterceptor.refreshAccessToken(RestClient.java:825)
                                                                                                    	at com.salesforce.androidsdk.rest.RestClient$OAuthRefreshInterceptor.intercept(RestClient.java:707)
                                                                                                    	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
                                                                                                    	at com.salesforce.androidsdk.rest.RestClient$OAuthRefreshInterceptor.intercept(RestClient.java:690)
                                                                                                    	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
                                                                                                    	at com.salesforce.androidsdk.rest.RestClient$OAuthRefreshInterceptor.intercept(RestClient.java:690)
                                                                                                    	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
                                                                                                    	at okhttp3.internal.connection.RealCall.getResponseWithInterceptorChain$okhttp(RealCall.kt:205)
                                                                                                    	at okhttp3.internal.connection.RealCall.execute(RealCall.kt:158)
                                                                                                    	at com.salesforce.androidsdk.rest.RestClient.sendSync(RestClient.java:374)
                                                                                                    	at com.salesforce.androidsdk.push.PushService.onSendUnregisterPushNotificationRequest(PushService.kt:319)
                                                                                                    	at com.salesforce.androidsdk.push.PushService.unregisterSFDCPushNotification(PushService.kt:336)
                                                                                                    	at com.salesforce.androidsdk.push.PushService.onUnregistered(PushService.kt:149)
                                                                                                    	at com.salesforce.androidsdk.push.PushService.performRegistrationChange(PushService.kt:89)
                                                                                                    	at com.salesforce.androidsdk.push.PushNotificationsRegistrationChangeWorker.doWork(PushNotificationsRegistrationChangeWorker.kt:88)
                                                                                                    	at androidx.work.Worker$1.run(Worker.java:82)
                                                                                                    	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
                                                                                                    	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:644)
                                                                                                    	at java.lang.Thread.run(Thread.java:1012)
2024-09-27 17:16:55.760 16714-17080 PushService             com...demo.nativeandroid.uat  E  Push notification un-registration failed (Ask Gemini)
                                                                                                    com.salesforce.androidsdk.rest.RestClient$RefreshTokenRevokedException: Could not refresh token
                                                                                                    	at com.salesforce.androidsdk.rest.RestClient$OAuthRefreshInterceptor.refreshAccessToken(RestClient.java:825)
                                                                                                    	at com.salesforce.androidsdk.rest.RestClient$OAuthRefreshInterceptor.intercept(RestClient.java:707)
                                                                                                    	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
                                                                                                    	at com.salesforce.androidsdk.rest.RestClient$OAuthRefreshInterceptor.intercept(RestClient.java:690)
                                                                                                    	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
                                                                                                    	at com.salesforce.androidsdk.rest.RestClient$OAuthRefreshInterceptor.intercept(RestClient.java:690)
                                                                                                    	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
                                                                                                    	at okhttp3.internal.connection.RealCall.getResponseWithInterceptorChain$okhttp(RealCall.kt:205)
                                                                                                    	at okhttp3.internal.connection.RealCall.execute(RealCall.kt:158)
                                                                                                    	at com.salesforce.androidsdk.rest.RestClient.sendSync(RestClient.java:374)
                                                                                                    	at com.salesforce.androidsdk.push.PushService.onSendUnregisterPushNotificationRequest(PushService.kt:319)
                                                                                                    	at com.salesforce.androidsdk.push.PushService.unregisterSFDCPushNotification(PushService.kt:336)
                                                                                                    	at com.salesforce.androidsdk.push.PushService.onUnregistered(PushService.kt:149)
                                                                                                    	at com.salesforce.androidsdk.push.PushService.performRegistrationChange(PushService.kt:89)
                                                                                                    	at com.salesforce.androidsdk.push.PushNotificationsRegistrationChangeWorker.doWork(PushNotificationsRegistrationChangeWorker.kt:88)
                                                                                                    	at androidx.work.Worker$1.run(Worker.java:82)
                                                                                                    	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
                                                                                                    	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:644)
                                                                                                    	at java.lang.Thread.run(Thread.java:1012)
2024-09-27 17:16:56.002   603-1065  Transition              system_server                        E  Trying to add a ready-group twice: Display{#0 state=ON size=1344x2992 ROTATION_0}
2024-09-27 17:16:56.848 16714-16773 OpenGLRenderer          com...demo.nativeandroid.uat  E  Unable to match the desired swap behavior.
2024-09-27 17:16:59.005   603-1694  TaskPersister           system_server                        E  File error accessing recents directory (directory doesn't exist?).
```

**Comment by brandonpage** [comment]
Thanks for reporting.  The error is harmless and should be fixed by #2615, which will be part of Mobile SDK 12.2.
