### ISSUE TITLE
Logout while SyncDown - Android

### ISSUE THREAD

**Issue by androidNttdata** [forcedotcom/SalesforceMobileSDK-Android#838]
It seems that there is an issue with the logout method while a SyncDown is taking place. To reproduce this behaviour a poor internet connection is needed. With this a logout during a syncDown will cause the following exception:

com.salesforce.androidsdk.smartstore.store.SmartStore$SmartStoreException: Soup: syncs_soup does not exist
            at com.salesforce.androidsdk.smartstore.store.SmartStore.update(SmartStore.java:838)
            at com.salesforce.androidsdk.smartstore.store.SmartStore.update(SmartStore.java:821)
            at com.salesforce.androidsdk.smartsync.util.SyncState.save(SyncState.java:172)
            at com.salesforce.androidsdk.smartsync.manager.SyncManager.updateSync(SyncManager.java:273)
            at com.salesforce.androidsdk.smartsync.manager.SyncManager.syncDownSoql(SyncManager.java:427)
            at com.salesforce.androidsdk.smartsync.manager.SyncManager.syncDown(SyncManager.java:381)
            at com.salesforce.androidsdk.smartsync.manager.SyncManager.access$000(SyncManager.java:70)
            at com.salesforce.androidsdk.smartsync.manager.SyncManager$1.run(SyncManager.java:217)
            at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1080)
            at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:573)
            at java.lang.Thread.run(Thread.java:841)
02-24 14:16:44.885   6237-10310/com.nttdata E/AndroidRuntime﹕ FATAL EXCEPTION: pool-15-thread-1

**Comment by bhariharan** [comment]
Logout triggers deletion of all soups as part of the cleanup. In this case, since the ```syncDown``` operation is in progress during logout, the ```syncDown``` will fail, since logout has removed the soups it requires and any other state corresponding to that user, including the access and refresh tokens. At this point, ```syncDown``` or any other operation is bound to fail. Logout should be called only when no requests or operations are in flight.

**Comment by androidNttdata** [comment]
Hi,

that's all right and I do not expect to get a refresh on non-existing soups while no user is logged in. But I do think that this exception should be caught appropriately inside the SDK. For whatever reason I am not able to catch this Exception in my syncDown method, which causes the application to crash!

**Comment by androidNttdata** [comment]
I wanna share my further experiences with syncDown and I hope this is getting fixed soon!

Besides the fact that a syncDown cannot take place after a user has logged out, there is one big question mark for me!
Why am I not able to catch the exception that is thrown inside the salesforce's SDK?

I am calling the syncDown method like this:
try {
SyncState syncState = syncMgr.syncDown(target, options, ContactObject.CONTACT_SOUP, new SyncManager.SyncUpdateCallback() {
				@Override
				public void onUpdate(SyncState sync) {
					handleSyncUpdate(sync);
				}
			});
} catch (Exception e) {
  e.printStackTrace();
}

If the SDK method throws an exception, it won't be caught by the catch(Exception e) block and the app crashes!

Why is that exception not caught? Is it because it runs in its own threat?

**Comment by bhariharan** [comment]
@androidNttdata The exception needs to be caught inside the callback:

```
try {
    handleSyncUpdate(sync);
} catch (Exception e) {
    e.printStackTrace();
}
```
