### ISSUE TITLE
Cannot Log In - User Data not getting saved

### ISSUE THREAD

**Issue by Nemisis** [forcedotcom/SalesforceMobileSDK-Android#865]
Hello, 

I have seen this error periodically from time to time and am not sure how to go about fixing it. What happens is the following: 

  1. I will be logged into the app and manually log out by calling `SalesforceSDKManager.getInstance().logout(activity, true);`. 
  2. I will log in. It will work and I will get logged into the application. 
  3. I will re-logout like step 1 above. 
  4. When I log back in (same account as step 2), it will not redirect me to the login page again. 

I have traced it to the `UserAcountManager#getCurrentAccount()` method: 

	public Account getCurrentAccount() {
        final Account[] accounts = accountManager.getAccountsByType(accountType);
        if (accounts == null || accounts.length == 0) {
        	return null;
        }

        // Reads the stored user ID and org ID.
        final SharedPreferences sp = context.getSharedPreferences(CURRENT_USER_PREF,
				Context.MODE_PRIVATE);
        final String storedUserId = sp.getString(USER_ID_KEY, "");
        final String storedOrgId = sp.getString(ORG_ID_KEY, "");
        for (final Account account : accounts) {
        	if (account != null) {

        		// Reads the user ID and org ID from account manager.
                final String orgId = SalesforceSDKManager.decryptWithPasscode(accountManager.getUserData(account,
                		AuthenticatorService.KEY_ORG_ID), SalesforceSDKManager.getInstance().getPasscodeHash());
        		final String userId = SalesforceSDKManager.decryptWithPasscode(accountManager.getUserData(account,
        				AuthenticatorService.KEY_USER_ID), SalesforceSDKManager.getInstance().getPasscodeHash());
                        // FROM ariets: From time to time, the userId and orgId returned here is null
        		if (storedUserId.trim().equals(userId)
        				&& storedOrgId.trim().equals(orgId)) {
        			return account;
        		}
        	}
        }
		return null;
	}

As stated in the code above, sometimes, the returned `userId` and returned `orgId` are returning null because the following exception is thrown: 

    04-08 16:11:52.705  29677-29677/com.evariant.prm.go.sandbox W/Encryptor:decrypt﹕ error during decryption
    javax.crypto.BadPaddingException: pad block corrupted
            at com.android.org.bouncycastle.jcajce.provider.symmetric.util.BaseBlockCipher.engineDoFinal(BaseBlockCipher.java:739)
            at javax.crypto.Cipher.doFinal(Cipher.java:1239)
            at com.salesforce.androidsdk.security.Encryptor.decrypt(Encryptor.java:302)
            at com.salesforce.androidsdk.security.Encryptor.decrypt(Encryptor.java:140)
            at com.salesforce.androidsdk.app.SalesforceSDKManager.decryptWithPasscode(SalesforceSDKManager.java:933)
            at com.salesforce.androidsdk.accounts.UserAccountManager.getCurrentAccount(UserAccountManager.java:191)
            at com.salesforce.androidsdk.rest.ClientManager.getAccount(ClientManager.java:209)
            at com.salesforce.androidsdk.rest.ClientManager.getRestClient(ClientManager.java:107)
            at com.evariant.prm.go.salesforce.SalesforceActionBarActivity.onResume(SalesforceActionBarActivity.java:85)
            at com.evariant.prm.go.ui.BaseActivity.onResume(BaseActivity.java:149)
            at android.app.Instrumentation.callActivityOnResume(Instrumentation.java:1210)
            at android.app.Activity.performResume(Activity.java:5505)
            at android.app.ActivityThread.performResumeActivity(ActivityThread.java:2936)
            at android.app.ActivityThread.handleResumeActivity(ActivityThread.java:2975)
            at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2368)
            at android.app.ActivityThread.access$900(ActivityThread.java:161)
            at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1265)
            at android.os.Handler.dispatchMessage(Handler.java:102)
            at android.os.Looper.loop(Looper.java:157)
            at android.app.ActivityThread.main(ActivityThread.java:5356)
            at java.lang.reflect.Method.invokeNative(Native Method)
            at java.lang.reflect.Method.invoke(Method.java:515)
            at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1265)
            at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1081)
            at dalvik.system.NativeStart.main(Native Method)
    04-08 16:11:52.705  29677-29677/com.evariant.prm.go.sandbox W/Encryptor:decrypt﹕ error during decryption
    java.lang.ArrayIndexOutOfBoundsException: length=31; index=117
            at com.salesforce.androidsdk.security.Encryptor.decrypt(Encryptor.java:307)
            at com.salesforce.androidsdk.security.Encryptor.decrypt(Encryptor.java:140)
            at com.salesforce.androidsdk.app.SalesforceSDKManager.decryptWithPasscode(SalesforceSDKManager.java:933)
            at com.salesforce.androidsdk.accounts.UserAccountManager.getCurrentAccount(UserAccountManager.java:193)
            at com.salesforce.androidsdk.rest.ClientManager.getAccount(ClientManager.java:209)
            at com.salesforce.androidsdk.rest.ClientManager.getRestClient(ClientManager.java:107)
            at com.evariant.prm.go.salesforce.SalesforceActionBarActivity.onResume(SalesforceActionBarActivity.java:85)
            at com.evariant.prm.go.ui.BaseActivity.onResume(BaseActivity.java:149)
            at android.app.Instrumentation.callActivityOnResume(Instrumentation.java:1210)
            at android.app.Activity.performResume(Activity.java:5505)
            at android.app.ActivityThread.performResumeActivity(ActivityThread.java:2936)
            at android.app.ActivityThread.handleResumeActivity(ActivityThread.java:2975)
            at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2368)
            at android.app.ActivityThread.access$900(ActivityThread.java:161)
            at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1265)
            at android.os.Handler.dispatchMessage(Handler.java:102)
            at android.os.Looper.loop(Looper.java:157)
            at android.app.ActivityThread.main(ActivityThread.java:5356)
            at java.lang.reflect.Method.invokeNative(Native Method)
            at java.lang.reflect.Method.invoke(Method.java:515)
            at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1265)
            at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1081)
            at dalvik.system.NativeStart.main(Native Method)

This occurs within this method: 

    public static String decrypt(String data, String key) {
        if (key == null || data == null) {
            return data;
        }
        try {

            // Decode with base64.
            byte[] keyBytes = Base64.decode(key, Base64.DEFAULT);
            byte[] dataBytes = Base64.decode(data, Base64.DEFAULT);

            // Decrypt with aes256.
            byte[] decryptedData = decrypt(dataBytes, 0, dataBytes.length, keyBytes);
            String decryptedString = new String(decryptedData, 0, decryptedData.length, UTF8);
            return decryptedString;
        } catch (Exception ex) {
            Log.w("Encryptor:decrypt", "error during decryption", ex);
        }
        return null;
    }

Unfortunately, I am at a loss as to what to do here. Any help would be great.

**Comment by bhariharan** [comment]
Which version of the Mobile SDK are you using?

**Comment by bhariharan** [comment]
In ```AndroidManifest.xml``` of the ```SalesforceSDK``` project, remove the following line:

```android:process=":auth"```.

We fixed this issue in [this](https://github.com/forcedotcom/SalesforceMobileSDK-Android/pull/794/files) pull request. Feel free to reopen this issue if you still see the same problem.

**Comment by Nemisis** [comment]
I did just that. My `AndroidManifest.xml` looks like this: 

    
        <service android:exported="true"
            android:name="com.salesforce.androidsdk.auth.AuthenticatorService">
            <intent-filter>
                <action android:name="android.accounts.AccountAuthenticator" />
            </intent-filter>
            <meta-data android:name="android.accounts.AccountAuthenticator"
                android:resource="@xml/authenticator" />
        </service>

And I am still getting an error where I am not able to log back in. When the user clicks "Allow", I am able to trace it to the following method: 

    public RestClient peekRestClient() {
        return peekRestClient(getAccount());
    }

 `getAccount()` calls through to `UserAcountManager#getCurrentAccount()`: 

	public Account getCurrentAccount() {
        final Account[] accounts = accountManager.getAccountsByType(accountType);
        if (accounts == null || accounts.length == 0) {
        	return null;
        }

        // Reads the stored user ID and org ID.
        final SharedPreferences sp = context.getSharedPreferences(CURRENT_USER_PREF,
				Context.MODE_PRIVATE);
        final String storedUserId = sp.getString(USER_ID_KEY, "");
        final String storedOrgId = sp.getString(ORG_ID_KEY, "");
        for (final Account account : accounts) {
        	if (account != null) {

        		// Reads the user ID and org ID from account manager.
                final String orgId = SalesforceSDKManager.decryptWithPasscode(accountManager.getUserData(account,
                		AuthenticatorService.KEY_ORG_ID), SalesforceSDKManager.getInstance().getPasscodeHash());
        		final String userId = SalesforceSDKManager.decryptWithPasscode(accountManager.getUserData(account,
        				AuthenticatorService.KEY_USER_ID), SalesforceSDKManager.getInstance().getPasscodeHash());
        		if (storedUserId.trim().equals(userId)
        				&& storedOrgId.trim().equals(orgId)) {
        			return account;
        		}
        	}
        }
		return null;
	}

Again, it returns null here and never finds the account, even though the `accounts` array contains accounts. As such, the `peekRestClient` method receives a null Account, so it kicks me back out to the login.

**Comment by bhariharan** [comment]
Can you uninstall the app and reinstall it, before trying?

**Comment by Nemisis** [comment]
Ah, I Think that was it. Thanks.

**Comment by Nemisis** [comment]
Okay, this seemed to have fixed my issue. However, now another error is happening and I am not sure what is happening. These are the steps: 

 1. I am logged into my account. 
 2. I logout using the `SalesforceSDKManager.getInstance().logout(activity, true)` method. 
 3. I repeat steps 1 & 2 a few times without fail. 
 4. Then, suddenly, when I click "Allow", it does nothing and the screen goes white (the progress indicator does not become visible at all). 

I debugged through the code and found that in the `shouldOverrideUrlLoading()` method, it does the following: 

		@Override
        public boolean shouldOverrideUrlLoading(WebView view, String url) {
			boolean isDone = url.replace("///", "/").toLowerCase(Locale.US).startsWith(loginOptions.oauthCallbackUrl.replace("///", "/").toLowerCase(Locale.US));
            if (isDone) {
                Uri callbackUri = Uri.parse(url);
                Map<String, String> params = UriFragmentParser.parse(callbackUri);
                String error = params.get("error");
                // Did we fail?
                if (error != null) {
                    String errorDesc = params.get("error_description");
                    onAuthFlowError(error, errorDesc);
                }
                // Or succeed?
                else {
                    TokenEndpointResponse tr = new TokenEndpointResponse(params);
                    onAuthFlowComplete(tr);
                }
            }
            return isDone;
        }

When my callback URL is loaded, it successfully goes into the `isDone` if block. In `onAuthFlowComplete(tr)`, it calls `FinishAuthtask`. However, it never actually executes that task. 

Now, the odd thing is, I added a log statement in there to see if maybe something was wonky with my IDE's debugging tool. When I compiled, re-ran the app again in debug mode and the task was executed. Any idea why it will not execute from time to time?

**Comment by bhariharan** [comment]
@Nemisis Interesting! I've never come across that. Could be a quirk in the IDE in debug mode. I have no clue.

**Comment by Nemisis** [comment]
Well, this does happen when I run the app in normal (not debug) mode. I am able to reliably reproduce this. Logging in and out will cause this to happen. I would close the app (back all the way out) and swipe it away from the Recents menu and am still unable to enter the app after log in. I noticed that the only way to get into the app is to do the following: 

 1. Go into the android Settings app. 
 2. Click "Apps" 
 3. Find the app I am working on and click on it. 
 4. Click "Force Stop" 
 5. Click OK

After I do that, I can then log into the application successfully.  

Perhaps I should open a new issue?

**Comment by bhariharan** [comment]
Can you reproduce this issue on any of our sample apps? Sure, a new issue is better for tracking.

**Comment by Nemisis** [comment]
Yeah, I reproduced it within the "Template App". I will create a new issue.

**Comment by Nemisis** [comment]
Added new issue: #868
