### ISSUE TITLE
HttpAccess IntentReceiverLeaked Exception

### ISSUE THREAD

**Issue by JamesKarl** [forcedotcom/SalesforceMobileSDK-Android#937]
It throws always throw an **IntentReceiverLeaked** Exception at the following bold line. 

public HttpAccess(Context app, String userAgent) {
        this.userAgent = userAgent;

        // Only null in tests.
        if (app == null) {
            conMgr = null;
        } else {

            // Registers a receiver to handle network changes.
            app.registerReceiver(this, new IntentFilter(ConnectivityManager.CONNECTIVITY_ACTION));

            // Gets the connectivity manager and current network type.
            conMgr = (ConnectivityManager) app.getSystemService(Context.CONNECTIVITY_SERVICE);
        }
} 

**The call stack is as bellow:**
android.app.IntentReceiverLeaked: Activity com.ppmshare.assistant.Home has leaked IntentReceiver com.salesforce.androidsdk.auth.HttpAccess@418d4480 that was originally registered here. Are you missing a call to unregisterReceiver()?
            at android.app.LoadedApk$ReceiverDispatcher.<init>(LoadedApk.java:850)
            at android.app.LoadedApk.getReceiverDispatcher(LoadedApk.java:616)
            at android.app.ContextImpl.registerReceiverInternal(ContextImpl.java:1391)
            at android.app.ContextImpl.registerReceiver(ContextImpl.java:1371)
            at android.app.ContextImpl.registerReceiver(ContextImpl.java:1365)
            at android.content.ContextWrapper.registerReceiver(ContextWrapper.java:446)
            **at com.salesforce.androidsdk.auth.HttpAccess.<init>(HttpAccess.java:108)**
            at com.salesforce.androidsdk.auth.HttpAccess.init(HttpAccess.java:90)
            at com.salesforce.androidsdk.app.SalesforceSDKManager.initInternal(SalesforceSDKManager.java:313)
            at com.salesforce.androidsdk.app.SalesforceSDKManager.init(SalesforceSDKManager.java:295)
            at com.salesforce.androidsdk.app.SalesforceSDKManager.initNative(SalesforceSDKManager.java:366)
            at com.ppmshare.assistant.Home.initSalesforce(Home.java:76)
            at com.ppmshare.assistant.Home.onCreate(Home.java:47)
            at android.app.Activity.performCreate(Activity.java:5234)
            at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1087)
            at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2302)
            at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2388)
            at android.app.ActivityThread.access$900(ActivityThread.java:148)
            at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1319)
            at android.os.Handler.dispatchMessage(Handler.java:99)
            at android.os.Looper.loop(Looper.java:137)
            at android.app.ActivityThread.main(ActivityThread.java:5473)
            at java.lang.reflect.Method.invokeNative(Native Method)
            at java.lang.reflect.Method.invoke(Method.java:525)
            at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:875)
            at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:691)
            at dalvik.system.NativeStart.main(Native Method)

**Comment by wmathurin** [comment]
We will investigate. Thanks.

**Comment by JamesKarl** [comment]
Great ! Thanks for your great effort.

**Comment by bhariharan** [comment]
@JamesKarl When does it throw this exception?

**Comment by bhariharan** [comment]
This is not reproducible at our end. Feel free to reopen if you have repro steps.
